### ISSUE TITLE
Problem with "automatic sniping"

### ISSUE THREAD

**Issue by Kachime** [PocketMobsters/PokeMobBot#104]
Here's my PokeMobBot config :

> "DelaySnipePokemon": 1000,
> "MinDelayBetweenSnipes": 60000,
> "MinPokeballsToSnipe": 20,
> "MinPokeballsWhileSnipe": 0,
> "PokemonToSnipe": {
>   "Locations": null,
>   "Pokemon": null
> },
> "SnipeAtPokestops": true,
> "SnipeIgnoreUnknownIv": true,
> "SnipeLocationServer": "localhost",
> "SnipeLocationServerPort": 16969,
> "UseSnipeLocationServer": true,
> "UseTransferIvForSnipe": false,

PogoLocationFeeder is working : 

> Listening...
> New connection from 127.0.0.1:60340
> Channel: coordsbots ID: Wigglytuff, Lat:54.864583966988, Lng:-6.2801153641931, IV:87
> Expires: 31/07/2016 18:01:45 

PokeMobBot is running well, except for sniping where i get the following error message every 60sec, then bot reconnect (sorry it's in french) : 

> [17:51:16] System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
>    à PoGo.PokeMobBot.Logic.Tasks.SnipePokemonTask.<>c__DisplayClass5_1.<Execute>b__0(SniperInfo q) dans C:\Users\Trent\Documents\GitHub\PokeMobBot\PoGo.PokeMobBot.Logic\Tasks\SnipePokemonTask.cs:ligne 134
>    à System.Linq.Enumerable.WhereListIterator1.MoveNext()
>    à System.Collections.Generic.List1..ctor(IEnumerable1 collection)
>    à System.Linq.Enumerable.ToList[TSource](IEnumerable1 source)
>    à PoGo.PokeMobBot.Logic.Tasks.SnipePokemonTask.<Execute>d__5.MoveNext() dans C:\Users\Trent\Documents\GitHub\PokeMobBot\PoGo.PokeMobBot.Logic\Tasks\SnipePokemonTask.cs:ligne 133

Thanks for your help

**Comment by DurtyFree** [comment]
Sniping isn't quite stable at the moment, we are working on this. Stay tuned

**Comment by Kachime** [comment]
Ok Tanks :)

**Comment by Kachime** [comment]
Whatever, sorry for the post, i think i solve my problem.
An empty pokemon list is giving this error

> "Pokemon": null

Maybe it should be improved and if list is empty, then catch everyting
