### ISSUE TITLE
pokemon to ignore not working correctly?

### ISSUE THREAD

**Issue by Amonsoul** [PocketMobsters/PokeMobBot#105]

**Comment by mvegter197** [comment]
Found the problem, it DOES skip/ignore the pokemons, but there is no event for skipping pokemons, so instead of showing it in the console it only writes it to the log.

**Comment by eddyueue** [comment]
Works.
  "UsePokemonToNotCatchFilter": true,
  "PokemonsToIgnore": [
    "rattata"
   ]

**Comment by mvegter197** [comment]
It works:
https://gyazo.com/0303ec64bd3a107ba9eeb51372ee2025

**Comment by Amonsoul** [comment]
Thank You
