### ISSUE TITLE
Pokeballs not recycling as they should

### ISSUE THREAD

**Issue by joeyhasbeenhere** [PocketMobsters/PokeMobBot#111]
For instance when I set "TotalAmountOfPokeballsToKeep": 150 the bot will recycle the normal Pokeballs first, which leads to eventually 0 Pokeballs and a lot of Great and Ultra balls. There should be an option to set the total amount of each kind of Pokeball.

**Comment by joeyhasbeenhere** [comment]
Will it automatically use a great ball if there are no pokeballs left? If so, this issue can be ignored.

**Comment by eddyueue** [comment]
Yes.
[https://github.com/PocketMobsters/PokeMobBot/blob/7a7973f30fbde939bf470b17fcec6d2b8603618e/PoGo.PokeMobBot.Logic/Tasks/CatchPokemonTask.cs#L192-L237]
