### ISSUE TITLE
The type or namespace name 'IApiFailureStrategy' could not be found

### ISSUE THREAD

**Issue by Savikas** [PocketMobsters/PokeMobBot#117]
Hey,

What's up with source? 

The type or namespace name 'IApiFailureStrategy' could not be found
The type or namespace name 'ApiOperation' could not be found

**Comment by mvegter197** [comment]
Which version are you using release or dev?

**Comment by Savikas** [comment]
Dev / Source code

**Comment by mvegter197** [comment]
@Savikas Me too. And I didn't experience it.

**Comment by Savikas** [comment]
Hmm, 

See: http://prntscr.com/bzv6yf

**Comment by mvegter197** [comment]
@Savikas full width please, so we can see file and line number!

**Comment by Savikas** [comment]
http://prntscr.com/bzv8y2

**Comment by mvegter197** [comment]
@Savikas I'm not able to find the error, could you download the source again, and compile it?

**Comment by Savikas** [comment]
Have tried like 9 times, same error all the time. http://prntscr.com/bzvc5p

**Comment by mvegter197** [comment]
@Savikas could you show or type the directives!

**Comment by Savikas** [comment]
Sorry, what you mean by that?

**Comment by mvegter197** [comment]
Press the + sign next to: using directives, it is at the top.

**Comment by domiSchenk** [comment]
you have to update the submodule Pocket-API.

this should work: `git submodule update`

or if this does not work change to this directory and make `git pull`

**Comment by mvegter197** [comment]
@domiSchenk You were just before me, I started removing the directives, to narrow down the error. Seems you were faster :stuck_out_tongue_winking_eye:

**Comment by domiSchenk** [comment]
had the same problem yesterday :-D

**Comment by Savikas** [comment]
PoGo.NecroBot.Logic.dll now it can't find that file. If I try to build it, then this same old error, but actually this error is fixed.. wtf?

**Comment by Savikas** [comment]
Fixed error

**Comment by Savikas** [comment]
Can you please add multibot support?

**Comment by mvegter197** [comment]
@Savikas create a new issue
