### ISSUE TITLE
Berrys

### ISSUE THREAD

**Issue by McTschecker** [PocketMobsters/PokeMobBot#121]
Can you please implement the Feature of using Berrys on Catch?

**Comment by lyrex** [comment]
It currently is using berries under certain conditions.  
The following conditions have to be met:  
Either the catch probability has to be lower and the CP must be over 350 or the IV must be over KeepMinIvPercentage.  
  
Is there a need to some explicit configuration parameters for it?

**Comment by McTschecker** [comment]
I think its good with a explict config and a Information that it used the Berry!  And a Good Thing cool be too if it don't Catch the first time it Auto use a Berry if the Chance is bellow e. G.  60% to not waste balls!

**Comment by lyrex** [comment]
#154

**Comment by McTschecker** [comment]
Thanks
