### ISSUE TITLE
(ERROR) Account not verified! Exiting...

### ISSUE THREAD

**Issue by ZoleeHU** [PocketMobsters/PokeMobBot#124]
It only happens with ptc login, not with google login

E: Screenshot: http://prnt.sc/bzvu4f

**Comment by crazynever** [comment]
The old template had it as
"AuthType": "ptc",
"GoogleRefreshToken": null,
"PtcUsername": "",
**"PtcPassword": "*",**
"GoogleUsername": null,
"GooglePassword": null

The new one
"AuthType": "ptc",
"GooglePassword": null,
"GoogleRefreshToken": null,
"GoogleUsername": null,
**"PtcPassword": "*",**
"PtcUsername": "*"

**Comment by ZoleeHU** [comment]
@crazynever Omfg, thank you so much! :)
