### ISSUE TITLE
PokeMobBot.wiki

### ISSUE THREAD

**Issue by xXDolemiteXx** [PocketMobsters/PokeMobBot#125]
I was going through the Wiki and found something that needs to be updated.

Looks like something was missed when updating the Chat-&-Rules.md; line 25 still reads Necronomicon.

**Comment by mvegter197** [comment]
Not the only thing:
https://github.com/PocketMobsters/PokeMobBot/search?q=Necro&type=Code&utf8=%E2%9C%93

**Comment by eaxling7** [comment]
The config page is also missing an explanation on the teleportation feature.

**Comment by DurtyFree** [comment]
Thanks for reporting:)
