### ISSUE TITLE
Too frequent bulk evolution

### ISSUE THREAD

**Issue by rrelict** [PocketMobsters/PokeMobBot#129]
There is too frequent bulk evolution:
![evolution_timeout_](https://cloud.githubusercontent.com/assets/8160881/17278266/c8358770-5761-11e6-89ba-8c74b128eccf.png)
Config:
"DelayBetweenPlayerActions": 5000,
"UseLuckyEggsMinPokemonAmount": 100,
"UseLuckyEggsWhileEvolving": true

May be we need the _DelayPocemonEvolution_ parameter?

**Comment by DurtyFree** [comment]
Duplicate of #138
