### ISSUE TITLE
(ERROR) Account not verified

### ISSUE THREAD

**Issue by Txger** [PocketMobsters/PokeMobBot#134]
i set it all up but if i start PokeMobBot it says that my account isn't verified.
But it defenetly is. I am playing on it on my phone right now and all works. even the days before... please help.

**Comment by trialTrail** [comment]
Please provide more details. Is this a PTC (Pokemon Trainers Club) or Google account you are using? 
Can you post a screenshot of your entire exception?

**Comment by Txger** [comment]
I sure can. I am using my PTC Account to log in.

http://imgur.com/a/XMhOV 

this is all that happens :/

**Comment by crazynever** [comment]
The old template had it as
"AuthType": "ptc",
"GoogleRefreshToken": null,
"PtcUsername": "",
"PtcPassword": "*",
"GoogleUsername": null,
"GooglePassword": null

The new one
"AuthType": "ptc",
"GooglePassword": null,
"GoogleRefreshToken": null,
"GoogleUsername": null,
"PtcPassword": "*",
"PtcUsername": "*"

**Comment by Txger** [comment]
Oh thank you very much it works now
