### ISSUE TITLE
Evolving Delay

### ISSUE THREAD

**Issue by littlemonster1** [PocketMobsters/PokeMobBot#138]
it would be nice if we could implement a delay for evolving similar to transferring

I am not 100% sure if this fixes it, therefore I refrain from doing a PR and post it here instead, according to how I understand the other codes this should do it (of course, the DelayEvolvePokemon variable needs to be added in the settings)

It would be a plus if there could be a randomizer added to it! (e.g. either another variable where one chooses the milliseconds to randomize the range - like 5000, so the range is X +/- 5000. or a percentage based random function)

within the EvolvePokemonTask.cs

foreach (var pokemon in pokemonToEvolve)
                {

                    var evolveResponse = await session.Client.Inventory.EvolvePokemon(pokemon.Id);

                    if (session.LogicSettings.Teleport)
                        await Task.Delay(session.LogicSettings.DelayEvolvePokemon);
                    else
                        DelayingUtils.Delay(session.LogicSettings.DelayBetweenPlayerActions, 0);

**Comment by trialTrail** [comment]
on it.
