### ISSUE TITLE
Account Not Verified

### ISSUE THREAD

**Issue by Ranoo12345** [PocketMobsters/PokeMobBot#14]
I tried what I saw in the previous answers

{
  "AuthType": "ptc",
  "GooglePassword": null,
  "GoogleRefreshToken": null,
  "GoogleUsername": null,
  "PtcUsername": "*****",
  "PtcPassword": "*****"
}

But it didnt work and still said not verified. What should I do?

**Comment by crazynever** [comment]
Checks if you did not reverse the location of the password and user in file auth

**Comment by Ranoo12345** [comment]
But its not reversed in what I pasted here right? Its already been swapped.

**Comment by crazynever** [comment]
The old template had it as
"AuthType": "ptc",
"GoogleRefreshToken": null,
"PtcUsername": "**",
"PtcPassword": "***",
"GoogleUsername": null,
"GooglePassword": null

The new one
"AuthType": "ptc",
"GooglePassword": null,
"GoogleRefreshToken": null,
"GoogleUsername": null,
"PtcPassword": "****",
"PtcUsername": "****"

**Comment by Ranoo12345** [comment]
Ah it works now thanks.
