### ISSUE TITLE
Advance Time

### ISSUE THREAD

**Issue by eaxling7** [PocketMobsters/PokeMobBot#140]
If your Advance time is over 24 hrs it just rolls over. (Ex. 25hr level up time shows as 1hr).

**Comment by DurtyFree** [comment]
Can other people confirm this please?

**Comment by eaxling7** [comment]
[http://hnng.moe/f/FHH](url) 
I need roughly 1.1 mil XP to evolve.
43,000 (XP/h) x 25 (The number it should be showing) = roughly 1.1 mil XP
