### ISSUE TITLE
Fastest bot ever !

### ISSUE THREAD

**Issue by mfron** [PocketMobsters/PokeMobBot#148]
![sans titre](https://cloud.githubusercontent.com/assets/11887274/17279308/0068df52-5771-11e6-8391-9cee0205466b.png)
https://github.com/mfron/Pokemon-Go-Bot

**Comment by mfron** [comment]
@UntilSunrise  T_T
let them choice a best bot ^^

**Comment by UntilSunrise** [comment]
This shouldnt be in the issue section...
