### ISSUE TITLE
100% transfers..... high cp throws for lower cp's

### ISSUE THREAD

**Issue by ThaRebel** [PocketMobsters/PokeMobBot#152]
[23:15:05] Snorlax	- CP: 2223  IV: 100.00%   [Best CP: 513  IV: 100.00%] (Candies: 247)

It throws a 100% Snorlax CP2223 away for a 100% Snorlax CP 513

I've had bunch of high cp pokemons with 100% and it will exchange it with a lower cp one. WHy?

**Comment by Zerotask** [comment]
I guess this is the option: "PrioritizeIvOverCp": true

**Comment by panzer168** [comment]
Always put your best pokemon as favourite.. so it doesn't get thrown away..

**Comment by ThaRebel** [comment]
I will write a code that checks the same %IV while it differs in CP. if A CP=> B CP keep, else transfer A

**Comment by shiznid12** [comment]
How is this an issue? If you set your MinIV% to 95%, it will keep BOTH Snorlax.

If you set your MinCP to 1000, it will keep BOTH SNORLAX, because they are both above the IV threshold. No settings, that I'm away of, would make you get rid of the higher CP Snorlax. My inventory is full of Snorlax, whether they be 500cp or 2500cp, specifically because they are above 95% IV.

**Comment by ThaRebel** [comment]
[10:29:50] Dragonite	- CP: 1600  IV: 100.00%   [Best CP: 155  IV: 100.00%] (Candies: 94)

**Comment by ThaRebel** [comment]
if (duplicatePokemon.Cp >=
                    session.Inventory.GetPokemonTransferFilter(duplicatePokemon.PokemonId).KeepMinCp ||
                    PokemonInfo.CalculatePokemonPerfection(duplicatePokemon) >
                    session.Inventory.GetPokemonTransferFilter(duplicatePokemon.PokemonId).KeepMinIvPercentage)
                {

seems legit. but something still goes wrong

**Comment by ThaRebel** [comment]
[14:42:45] (TRANSFERED) Dragonite       - CP: 1000  IV: 100.00%   [Best CP: 155  IV: 100.00%] (Candies: 12)

mincp =1001
minIV = 100%

How is this an issue???? sherlock

**Comment by shiznid12** [comment]
With those settings, it should keep both technically..

**Comment by ThaRebel** [comment]
Well maybe its the 100% setting.

PokemonInfo.CalculatePokemonPerfection(duplicatePokemon) >

should be 
PokemonInfo.CalculatePokemonPerfection(duplicatePokemon) >=

I dont want to keep em both. I want to trade in the least cp for the high one with same IV. I changed code, let's hope it doesnt occur anyt more.

**Comment by DurtyFree** [comment]
This is config related. Please ask in the Discord.
