### ISSUE TITLE
[Request] Pokemon name translation (de, fr, ja, ko, zh) 

### ISSUE THREAD

**Issue by GraspGG** [PocketMobsters/PokeMobBot#157]
Somewhen after botting - the backpack is filled with pokemon - when real live spotting, catching and fighting at arenas starts, it would be helpful to have the pokemon have the correct, interface language related names.

As far as i know, french, german, japanese, korean and chinese language pokemon names are existing beside english.

Autorename is a great bot feature, but gets useless and confusing as soon as one of the users is leaving the house  and catches pokemon having non english names... Then the user has to run/autosort the bot before he has a clean backpack again. 

It would be much easier and cleaner if the pokemon names could get autorenamed into the interface language corresponding names.

EDIT:
Im just thinking/guessing ... Having english pokemon names might have some disdvantages:
- If people at arenas see english pokemon names here in germany, that might look strange. If its only one, thats okay (tourists), but as more bot users get more often into arenas that does look suspicious for sure
- Nantic just had to filter all players whose pokemon names does not have interface corresponding languages (if they want to select the bot users)!? Catching a pokemon through the app does always name them using the interface language.

**Comment by MadEyez** [comment]
One possible [source ](http://www.pokewiki.de/Pok%C3%A9mon-Liste)for the translations.

**Comment by DurtyFree** [comment]
Will be implemented in #208
