### ISSUE TITLE
Using UltraBalls on weak pokemon

### ISSUE THREAD

**Issue by Phoo7** [PocketMobsters/PokeMobBot#159]
Hello guys, first of all, sorry for posting here, I did try the chat suggested but it put me in the wrong place I think?

So, I've just got this up and running after a bit of a headache, but first thing I noticed is that it uses ultra balls on very weak pokemon.

In my config file I have these set:
  "UseGreatBallAboveCp": 500,
  "UseUltraBallAboveCp": 1000,

Now, there was no option for PokeBalls.

I have tried
  "UsePokeBalllAboveCp": 1,
  "UsePokeBallBelowCp": 499,

Thank you for your time and help in advance :)

**Comment by ricekrispy408** [comment]
You can't just write UsePokeBallAbove and give it a value and expect the bot to recognize it.

**Comment by Phoo7** [comment]
Thank you for the reply. I've never done coding before, and I know this is probably very basic stuff, but I went with what I thought would be correct and it obviously isn't.

Would you please let me know what I should use to catch pokemon below 500cp using pokeballs?

Thank you

**Comment by Akaa** [comment]
I've also been having this issue. I believe I fixed it but unsure why this is the case.
I believe in the default files, you are prioritizing IV over CP.

So you should modify the lines that say

UsegreatballaboveIV : 0.0
useultraballaboveIV: 0.0

This fixed it for me
