### ISSUE TITLE
Having lessthan one pokemon

### ISSUE THREAD

**Issue by She3p** [PocketMobsters/PokeMobBot#162]
Hi, anychance of making the bot remove all pokemon below CP/IV filter regardless if they're the only one of its kind?

**Comment by lyrex** [comment]
Have you tried to set KeepMinDuplicatePokemon to zero?

**Comment by She3p** [comment]
yes it returns a null error. my friend added it to an old source code but been so many updates sicne then i cant even run his edit to clean my poke storeage.

**Comment by DurtyFree** [comment]
Use the newest version and set the KeepMinDuplicatePokemon to 1
