### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by Craduco** [PocketMobsters/PokeMobBot#164]
Hi,

I get this error:  https://gyazo.com/83d14ecbf6d5edd16a1f9500b895a3fc
And this is my auth: https://gyazo.com/8e19c587e43ebf6e5a1c67a506576e5c
Please help me, it won't work.﻿

**Comment by Nothingst** [comment]
Easy， just go your config and edit the Auth.json file， Fill out the Google account and password。 don't missing  “ ” between you account and passwd。   example   "GoogleUsername": "qqqqq@gmail.com",

**Comment by Jazed** [comment]
If you're still having issues after the above give this format a try:

`{
  "AuthType": "google",
  "GoogleRefreshToken": null,
  "PtcUsername": null,
  "PtcPassword": null,
  "GoogleUsername": "aaaa@gmail.com",
  "GooglePassword": "password"
}
`

**Comment by Nothingst** [comment]
@Jazed do u know how to open 2 different .exe in one？

**Comment by Craduco** [comment]
@Jazed Thanks man it works finally! Do you know any good coords?

**Comment by Jazed** [comment]
@Nothingst You'll have to copy the folders and run them separately. We'll probably be adding multi-bot support in the near future along with a web UI.

**Comment by Jazed** [comment]
@Craduco Please use the Discord for that information.
