### ISSUE TITLE
Pokemon GO Discord?

### ISSUE THREAD

**Issue by Craduco** [PocketMobsters/PokeMobBot#169]
Not sure if I should open a issue for this but I don't know how else to contact people on here, whats the name of the discord for pokemon coords?

**Comment by FreddyLIE** [comment]
https://github.com/5andr0/PogoLocationFeeder/wiki

**Comment by Jazed** [comment]
https://discord.gg/8msqsWV

**Comment by beealeaf** [comment]
@Jazed Thats discord link doesn't work.
