### ISSUE TITLE
Suggestion:  Additional sources for sniping info

### ISSUE THREAD

**Issue by jakesmurf** [PocketMobsters/PokeMobBot#17]
Since Pokevision spends so much time being down, and a sniping bot setup wastes a lot of time when this happens, I suggest that you implement alternate sources of pokemon locations.  

A possible source of info would be skiplagged's pokemon map.  It's API returns information similar to how pokevision does and I've never seen it go down as of yet.  

API example

http://skiplagged.com/api/pokemon.php?bounds=40.76356269219236,-73.98657795715332,40.7854671345488,-73.95812508392333
bounds = bound_lower_left_lat,bound_lower_left_lng,bound_upper_right_lat,bound_upper_right_lng

**Comment by UntilSunrise** [comment]
duplicate
