### ISSUE TITLE
Missing files?? When trying to run source! HELP!

### ISSUE THREAD

**Issue by johnpyp** [PocketMobsters/PokeMobBot#171]
Hello,

I've been getting errors every time with the latest Source Code and RocketAPI as of 8:07 EST. 
Whenever I try to run it in VS 2015, I get these errors: https://gyazo.com/698ea84eabd7ab1528230ed292d3cb97

My process for getting to that point:

1) Download both files.
2) Take the -master folder for the bot and put it on desktop.
3) Put the contents of Pokemon-Go-Rocket-API-Master into the Pokemon-Go-Rocket-API Folder
4) Run VS 2015 and open PokeMobBot.sln as a solution.
5) Set it as the startup project
6) Ctrl + F5

Then I get the errors in the image. Interestingly, my friend did the exact same process and sent me the files BEFORE step 4 (as to not create any new files from running the program) and it worked with no errors. I also tried only copying the RocketAPI folder from my friend's files and that worked too (in my source code copy) which leads me to believe something is wrong with my RocketAPI. Please help! Thanks.

**Comment by Throw9984** [comment]
Same issue here, I tried a copy of the Pokemon-Go-Rocket-API I was using in a working build of an older Necro version copied to this PokeMobBot and it worked. I'm not sure how this all works, but I'm thinking maybe the current Rocket-API is broken or PokeMobBot isn't referencing something right for the newer Rocket-API build?

**Comment by johnpyp** [comment]
Another user figured out the Rocket API link on the wiki wasn't correct because PokeMobBot made a specialized version of it, so here is a version that works: https://github.com/eslindsey/Pokemon-Go-Rocket-API/tree/yamashi-30-min-fix
