### ISSUE TITLE
using all my ultra balls

### ISSUE THREAD

**Issue by faris2000** [PocketMobsters/PokeMobBot#172]
i am currently using this and its using ultra balls no matter what, HELP PLEASE!.
  "UseGreatBallAboveCp": 500,
  "UseUltraBallAboveCp": 800,
  "UseMasterBallAboveCp": 1500,
  "UseGreatBallBelowCatchProbability": 0.35,
  "UseUltraBallBelowCatchProbability": 0.25,
  "UseMasterBallBelowCatchProbability": 0.20,

**Comment by N3evin** [comment]
Yeah i am having the same problem. It just kept on using ultraball.

"UseGreatBallAboveCp": 750,
"UseUltraBallAboveCp": 1000,
"UseMasterBallAboveCp": 1500,
"UseGreatBallAboveIv": 100,
"UseUltraBallAboveIv": 100,
"UseGreatBallBelowCatchProbability": 0.0,
"UseUltraBallBelowCatchProbability": 0.0,
"UseMasterBallBelowCatchProbability": 0.0,

**Comment by faris2000** [comment]
ya like im catching under 100cp pokemon with ultraballs

**Comment by faris2000** [comment]
even great balls too though
 [06:08:17] (PKMN) (CatchSuccess) | (Normal) Pidgey Lvl: 4 CP: (59/71) IV: 39.00% | Chance: 78.21% | 66.43m dist | with a GreatBall (4 left). | Candies: 8

**Comment by DurtyFree** [comment]
This is config related. Ask in the Discord for help.
