### ISSUE TITLE
[BUG] Ignore filter does not work

### ISSUE THREAD

**Issue by Arturk4** [PocketMobsters/PokeMobBot#173]
Bot catches Pidgeys, Weedles and so on despite being in the ignore filter in the config.

**Comment by Fenixxia** [comment]
Show your config

**Comment by rherartt** [comment]
"UsePokemonToNotCatchFilter": true, are you using this?

**Comment by Arturk4** [comment]
@rherartt I did not see this option, thank's man. I was looking for something with ignore. Sorry for the inconvenience. Solved.
