### ISSUE TITLE
Can't run after initial run?

### ISSUE THREAD

**Issue by rjsmith1012** [PocketMobsters/PokeMobBot#178]
![capture](https://cloud.githubusercontent.com/assets/18706364/17282117/638f41ee-5770-11e6-84b1-c840cda47db3.PNG)

So I'm having this issue after inputting my info in the auth.json file. Any help? I can't get past this screen.

**Comment by devian223** [comment]
Check whether you haven't removed any comma in the auth or config file

**Comment by mvegter197** [comment]
@rjsmith1012 Could you make a screenshot of everything, as it seems we are missing the top part of the error, where it states the file, and line number.

**Comment by DurtyFree** [comment]
This is config related.
Please ask in our Discord for help.

Take a look at our Wiki how to configure the Bot properly: https://github.com/PocketMobsters/PokeMobBot/wiki
