### ISSUE TITLE
Sniping does not work ?

### ISSUE THREAD

**Issue by midoom** [PocketMobsters/PokeMobBot#18]
Hi, sniping does not work, scan failure.

**Comment by terassiel** [comment]
All nests have changed as of July 29. It might not show any Pokemons for you because they no longer are there

**Comment by aeryl1999** [comment]
use the pokesnipers for online sniper location

**Comment by JustinWayneFly** [comment]
Yeah I can confirm this is an issue with manual and automatic locations.

**Comment by jakesmurf** [comment]
I believe the sniper uses Pokevision to scan for pokemon.  So long as pokevision is down, the sniper doesn't seem to work at all.

**Comment by demonoodle** [comment]
yeah , although I have been using manual location , the program still say " no pokemon find to snipe! "

**Comment by swc-tine** [comment]
I believe it's due to pokevision shutting down and it uses their API ?

**Comment by aeryl1999** [comment]
for now lets just settle for discord sniping :v:
