### ISSUE TITLE
Bot not recycling inventory

### ISSUE THREAD

**Issue by dtlewis511** [PocketMobsters/PokeMobBot#183]
Bot is ignoring the values I have set for Max Pokeballs, Revives and potions and filling up my inventory until I get Inventory is Full message when hitting Pokestops.  I tried various values with the Recycle at % as well and still won't recycle.

**Comment by bluereinz** [comment]
the bot is ignoring razz berry to recycle. potions, revives and balls are recycled normally

**Comment by opixboyz** [comment]
I have same problem when necrobot update 0.5.0 the last one, my inventory always full and  always using ultraball when i catch every single pokemon even though it had written UseGreatBallAboveCp": 750,
  "UseUltraBallAboveCp": 2000,
  "UseMasterBallAboveCp": 2200, 
Won't work at all.

**Comment by bluereinz** [comment]
if you are using the latest release of pokemobbot, just lower the razz berry setting (cp, iv and catch probability). i set mine to 800 cp, 60 iv and 50 catch probability.

**Comment by siimveskilt** [comment]
Not recycling anything for me, reverting back to the old version ..

**Comment by lgndz** [comment]
Can confirm adjusting the razz tolerence works. Cheap workaround, but Ill take it

**Comment by DurtyFree** [comment]
This will actually be fixed with the new release coming this evening.
