### ISSUE TITLE
Item Recycling Suggestion

### ISSUE THREAD

**Issue by Zeonymous** [PocketMobsters/PokeMobBot#188]
Like the previous versions before the development changed hands, there should be an individual item recycle value for these items;
Pokeballs
Greatballs
Ultraballs
Potions
SuperPotions
HyperPotions

Keeping the top only is restricting, and causes problems within the bot, Item Overflow, having X Ball for X Pokemon, then not having what you need to go out on the street, if you want to set it up that way for when you have the time to go out.

There are many reasons why this should not be restricted to 3 values alone "Potions/Balls/Revives" but the main ones are the inability to configure it for a specific and perfect build based on inventory space.

My config:
      "Key": "itemPokeBall",
      "Value": 155
    },
    {
      "Key": "itemGreatBall",
      "Value": 155
    },
    {
      "Key": "itemUltraBall",
      "Value": 155
    },
    {
      "Key": "itemMasterBall",
      "Value": 3000
    },
    {
      "Key": "itemPotion",
      "Value": 25
    },
    {
      "Key": "itemSuperPotion",
      "Value": 75
    },
    {
      "Key": "itemHyperPotion",
      "Value": 100
    },
    {
      "Key": "itemMaxPotion",
      "Value": 105
    },
    {
      "Key": "itemRevive",
      "Value": 20
    },
    {
      "Key": "itemMaxRevive",
      "Value": 20

But with

  "TotalAmountOfPokeballsToKeep": 0,
  "TotalAmountOfPotionsToKeep": 0,
  "TotalAmountOfRevivesToKeep": 0,

set to 0, and all of the other values set correctly, it still uses the hardcoded settings to do as it please, rather than the user. With them set higher, it only takes the best in each category.

Even if these values are deleted, they are written back in.

Can there be a separate option put in here to toggle on/off whether you want to use the TransferFilter, or the As-Is filter?

Thank you very much for reading.

**Comment by masterpowers** [comment]
what does your config do anyway?

**Comment by Zeonymous** [comment]
It makes it so you can manually select the amount of items you have before it recycles the said items.

I think it *Might* be working since my last update, its just conflicting with the master code.

I know for a fact it is not recycling PokeBalls at the set amount, because I was over 370 Pokeballs, and it wouldn't recycle.

**Comment by masterpowers** [comment]
is there a way to recycle berries i got so many

**Comment by Zeonymous** [comment]
I cant do anything until I get word from the devs, until then I'm over cap on everything I don't need, and none of what I do need.

**Comment by lgndz** [comment]
Just set the usage tolerance so that it basically spams them at pokemon.
Only fix until devs get it tightened up

**Comment by littlemonster1** [comment]
if I understand correctly you want to split the three commands again into many?
I do not understand your argumentation for that. Better management for going out on the street? what issue is it if you have great pokeballs instead of normal pokeballs? 

I think keeping
"TotalAmountOfPokeballsToKeep": 0,
"TotalAmountOfPotionsToKeep": 0,
"TotalAmountOfRevivesToKeep": 0,
is the best option, with the values being modifiable.

You will never get hurt on the street using a better item.
But maybe I just misunderstood your proposal.

**Comment by Zeonymous** [comment]
No, because it doesn't recycle intelligently.

I woke up with 300 berries, and 2 Pokeballs, with all kinds of different unwanted potions, when I have the cap set to 100, and there were more than 100 in a few slots.

Absolutely not. No, no way, no how.

The current build is a nightmare under item management.

An even bigger nightmare in "HelpMe" when trying to help people with the same issue I havn't been able to figure out for 3 days going on.

Side Note:

Thank you DurtyFree for going over this, I hope this can apply to Berries as well.

Thank you so much.

**Comment by Fenixxia** [comment]
I used a variety of customization options and control.
As a user, I found it easier and (very importantly) clear the previous management option. Where each item was specified ceiling.
Now, we have provided a ceiling for the category item. Maybe it's a more flexible setup for professionals. But for the average user it is more difficult at times. Because of this, and so many problems with the processing.

**Comment by littlemonster1** [comment]
It is definitely a smarter and better option if it works. I agree the update has had issues, but all the arguments here for it so far have more or less been: it worked before and now it does not. Yes, there has been an issue and yes, it is supposed to recycle correctly with the coming update again.

**Comment by Zeonymous** [comment]
Just a shame I cant have more user control.
