### ISSUE TITLE
Bit confuse on PokeBall and Potions to keep

### ISSUE THREAD

**Issue by TehChozinOne** [PocketMobsters/PokeMobBot#19]
It doesn't let me choose what type of PokeBall I want to keep. If it means just ordinary PokeBall then where can I set to keep for other balls?

Also I don't need any potions but if I set to 0 it throw error "Potion to keep amount less than 1"

**Comment by Luc4z** [comment]
me too , mostly it become like pokeballx200 greatballx0 ultraballx0 and inventory was full and we can only carry pokeball but not those better one , can we set balls amount that we wanna keep ? like based on different kind not whole balls in one number

**Comment by LordAzuRa** [comment]
I had the same concern when I updated to the last version of Necrobot before it got canceled and became PokeMobBot.

I fixed it by taking the values of an older Necrobot version and adding them to PokeMobBot's config files.

**Under :**   "ItemRecycleFilter": [
**Add:**
    {
      "Key": "itemPokeBall",
      "Value": 50
    },
    {
      "Key": "itemGreatBall",
      "Value": 75
    },
    {
      "Key": "itemUltraBall",
      "Value": 125
    },
    {
      "Key": "itemMasterBall",
      "Value": 100
    },


You're welcome :)

**Comment by cherzong** [comment]
@Luc4z Add this below "ItemRecycleFilter" in config.json and configure it to your liking. Also for "TotalAmountOfPokebalsToKeep" in config.json add all the values of your pokeballs together, so it's 300 for the example below.

{
      "Key": "itemPokeBall",
      "Value": 100
    },
    {
      "Key": "itemGreatBall",
      "Value": 100
    },
    {
      "Key": "itemUltraBall",
      "Value": 100
    },

**Comment by cherzong** [comment]
@LordAzuRa also change "TotalAmountOfPokebalsToKeep" to the total values of the pokeballs so 250, not counting masterball since you can't obtain it yet.

**Comment by crazynever** [comment]
Put in the code that solves:
`{
      "Key": "itemPokeBall",
      "Value": 40
    },
    {
      "Key": "itemGreatBall",
      "Value": 50
    },
    {
      "Key": "itemUltraBall",
      "Value": 100
    },
    {
      "Key": "itemPotion",
      "Value": 20
    },
    {
      "Key": "itemHyperPotion",
      "Value": 30
    },
    {
      "Key": "itemMaxPotion",
      "Value": 75
    },
    {
      "Key": "itemRevive",
      "Value": 25
    },`
