### ISSUE TITLE
translation.hu.json always shows modified

### ISSUE THREAD

**Issue by eslindsey** [PocketMobsters/PokeMobBot#191]
This issue has been confirmed by several users in the #development channel.

Performing a `git status` always shows the file `translation.hu.json` as modified, even after a `git reset --hard HEAD`. This prevents rebasing or pulling from the upstream master, and severely hampers development.

My suspicion based on the `git-diff` is that there is a line ending problem causing `git` to always think the file has been changed.

[translation.hu.json.diff.txt](https://github.com/PocketMobsters/PokeMobBot/files/393000/translation.hu.json.diff.txt)

**Comment by DurtyFree** [comment]
I dont actually have this problem, try to refork.

**Comment by eslindsey** [comment]
Resolved by re-forking.
