### ISSUE TITLE
You're outside of your defined radius! Walking to start

### ISSUE THREAD

**Issue by artsy23** [PocketMobsters/PokeMobBot#193]
guys how do i fix "You're outside of your defined radius! Walking to start"

**Comment by Fenixxia** [comment]
This occasionally happens when you work a sniper. You should restart the client. Also, check the settings for the range 1000-2500 will be enough.

**Comment by Muzurio** [comment]
This even happens when you have range set to 1000. It only seems to happen when the bot is more or less restarting (after the 30 minutes loop) and you just happen to be sniping at that time.

Restarting the bot does indeed solve it without being softbanned.

**Comment by DurtyFree** [comment]
Not a code related issue.

**Comment by artsy23** [comment]
my only solution to this is to completely restart the executable by using  autorestarter.
