### ISSUE TITLE
bot uses ultraballs when not suppose to

### ISSUE THREAD

**Issue by AzNJDM** [PocketMobsters/PokeMobBot#194]
the bot uses my ultra balls when i have it set to 1000cp up and IV above 95 and BelowCatchProbability 0.4.
it uses to catch pokemon that is [00:31:52] (CatchSuccess) | (Normal) Rattata Lvl: 18 CP: (255/299) IV: 49.54% | Chance: 35.29% | 32.24m dist | with a UltraBall (34 left). | Candies: 243
why is it doing that?

**Comment by ruturajvy** [comment]
Reduce the catch probability threshold.
Rattata 255 cp may have 35.29% probability(or chance) as shown in the description.
Hope this helped.

**Comment by AzNJDM** [comment]
I just tried reducing the threshold to 0.01 but it still uses my ultra balls. 

I was also wondering if the catch probability has anything to do with the prioritizing over iv

**Comment by DurtyFree** [comment]
Do other people experience the same issue?

**Comment by Nicte** [comment]
I did run out of ultraballs, but I was not aware of the catch probability threshold (i was using v 1.0). I did indeed check my "UseUltraBallAboveCp" setting and even increased it to 1500. Anyway, it would use it on 800 cp pokemons. Great balls happened the same. I have it set for 1000 cp and it used it on pokemons below that threshold.

Sorry I don't have any log that can show it. If it happens again I will try to take a screenshot. Also, will try with latest version.

**Comment by KeePoFF** [comment]
[12:03:29] (PKMN) (CatchSuccess) | (Normal) Voltorb Lvl: 18 CP: (403/431) IV: 73.00% | Chance: 35.29% | 45.36m dist | with a UltraBall (97 left). | Candies: 189.. Here is log of mine. I set the use of utraball to be for over 1600 CP but still continue to catch that low pokemons...

**Comment by AzNJDM** [comment]
after this recent update it has fixed the issues the bot is now using normal pokeballs and the ultra and great when its suppose to
