### ISSUE TITLE
Evolving 30 pokemons using lucky egg

### ISSUE THREAD

**Issue by gelistir** [PocketMobsters/PokeMobBot#196]
Rather than holding 1 pidgey (12) candies, I can catch many pidgeys, so I will easily run an evolving 30 pidgeys or other pokemons using lucky egg for xp increase. However, mob bot transfers that kind of pokemons due to duplicate pokemon to hold =1.

**Comment by SwordStroker** [comment]
so you are saying it needs to evolve it and transfer ?

**Comment by gelistir** [comment]
if bot holds many pokemons which require less candies (12 candies), lucky egg feature can run more and one can boosts xp easily.

**Comment by gelistir** [comment]
as a feature, dont transfer pidgeys, spearrow untill i would have 1 of them, so pidgey X 10, spearrow x 10, and X x 10, total of 30 pokemons will easily start an evolving process using lucky egg with a gain of 30k XP

**Comment by vapp13** [comment]
You have to set this value "KeepPokemonsThatCanEvolve" to "true". The bot will ignore the value in "KeepMinDuplicatePokemon" but only for the pokemons listed on "PokemonsToEvolve". So you can acumulate 30 Pidgey and others pokemons to use with Lucky Egg

**Comment by gelistir** [comment]
Thank you very much :)

**Comment by vapp13** [comment]
Btw, set this value "UseLuckyEggsMinPokemonAmount" to 50 (depend on your pokemon inventory capability) . So the bot will keep pokemons and candy up to 50 (between all your pokemons listed on "PokemonsToEvolve") before trying to use the Lucky Egg, so you know for sure that you'll get 50k exp at least.
