### ISSUE TITLE
(INFO) Playing as ...  when recycling

### ISSUE THREAD

**Issue by wooward** [PocketMobsters/PokeMobBot#200]
Last version used to list how many pokeballs you currently had before recycling.  Please change it back instead of (INFO) Playing as ...

**Comment by bmdr38** [comment]
There should be both the "playing as ..." and your pokeball inventory.  The reason why the "playing as ..." bits show up is because your profile is refreshed for the stardust check for upgrading, and in that process of doing that, it likes to spit that out.

**Comment by wooward** [comment]
v1.0.1 does not print out the pokeball inventory for me.  Which file can I look at to inspect the code?  Thanks.

**Comment by moredhel92** [comment]
I want the same pls
