### ISSUE TITLE
[BUG?] PokemonTransferFilter (List) - Not working properly

### ISSUE THREAD

**Issue by jinkawasaki333** [PocketMobsters/PokeMobBot#203]
The bot is not transferring Pokemons that should be transferred.

Here is my setting:

```
"KeepMinCp": 1500,
"KeepMinDuplicatePokemon": 1,
"KeepMinIvPercentage": 95.0,
"TransferDuplicatePokemon": true,
"PokemonsTransferFilter": {
 "Snorlax": {
      "KeepMinCp": 2000,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 4
    }
 }
```

But here is what I got:

![image](https://cloud.githubusercontent.com/assets/7829862/17286705/2385fe9e-5806-11e6-94b4-65010243b835.png)

As you can see, it is keeping 21 Snorlax with CP above 2000, regardless of the low IV; and with IV above 80% regardless of the low CP. Isn't it supposed to fulfill both condition?
The "KeepMinDuplicatePokemon" is also not quite working as it is keeping more than 4 Snorlaxes.

**Comment by isaychris** [comment]
The logic is using an OR operator for KeepMinCP and KeepMinIV

**Comment by jinkawasaki333** [comment]
@isaychris In that way, there is no perfect solution to filter out the "trash"?

**Comment by carminaburana123** [comment]
Dude where did you get all those snorlaxes?

**Comment by jinkawasaki333** [comment]
@carminaburana123 I thought so at first, but after seeing the database, I doubt so. Probably the update is only for  **_### Pokemon Upgrading Logic Improvements_**, and not for general config.

P.S.: I'm throwing away Snorlax under 2300 CP. I'd love to transfer those to you, but you have to push Niantic to enable trading soon  xD 
P.P.S.: I just turned the sniping on, and it gets Snorlax by itself.

**Comment by Fenixxia** [comment]
That would get rid of such a large number of pokemon you need to install the beyond the options in the filter. It is also possible you have an individual filter on this type of pokemon. This filter ignores the overall filter.

**Comment by carminaburana123** [comment]
@jinkawasaki333  what is your GPX file?

**Comment by DurtyFree** [comment]
This is known, see #98
