### ISSUE TITLE
I WANT TO USE A SPECIFY POKEBALL

### ISSUE THREAD

**Issue by smancio17** [PocketMobsters/PokeMobBot#207]
When I find Charmander(for example) bot uses pokeball.... But i want to use megaball or ultraball... How can i do that?

**Comment by lgndz** [comment]
you cant

not supported somehow

**Comment by vapp13** [comment]
Add charmander to "PokemonToUseMasterball":  [  ]

**Comment by vapp13** [comment]
By default there is not  "PokemonToUseUltraball": [ ], but you can give it a try. Good Luck ;)

**Comment by smancio17** [comment]
I don't have masterball... I want to catch with greatball or ultraball

**Comment by vapp13** [comment]
I haven't try this but try to add at the bottom of the config doc:
"PokemonToUseGreatball": [
     "charmander"
 ]
Make sure to add this lines before the last bracket "}"

**Comment by smancio17** [comment]
I'll try... Do you know someplaces where i can find lots of dratini?

**Comment by vapp13** [comment]
https://github.com/PocketMobsters/PokeMobBot/wiki/Locations-&-GPX-Route-Files

There's several Dranitis nests on the list. Have a look into the Starting Location coordinates.

**Comment by smancio17** [comment]
Thanks a lot!

**Comment by mennas** [comment]
"UseGreatBallAboveCp": 1000,
  "UseUltraBallAboveCp": 2000,
  "UseMasterBallAboveCp": 3000,
  "UseBerryMinCp": 1500,
  "UseBerryMinIv": 85.0,
  "UseBerryBelowCatchProbability": 25,
  "TotalAmountOfPokeballsToKeep": 300,
  "TotalAmountOfPotionsToKeep": 2,
  "TotalAmountOfRevivesToKeep": 2,
  "UseGreatBallAboveIv": 70,
  "UseUltraBallAboveIv": 90,
  "UseGreatBallBelowCatchProbability": 25.0,
  "UseUltraBallBelowCatchProbability": 15.0,
  "UseMasterBallBelowCatchProbability": 1.0,
  "RecycleInventoryAtUsagePercentage": 0.0,



You can try it

**Comment by DurtyFree** [comment]
This is not a place for configuration related issues.
