### ISSUE TITLE
SOME PLACES WITH POKEMON

### ISSUE THREAD

**Issue by smancio17** [PocketMobsters/PokeMobBot#209]
In Milan..."Parco Sempione" there are lots of Charmender.....another place with other pokemon?

**Comment by Kalashnikitty** [comment]
This is an Issue tracker not Q&A.
And your Caps is broken.

**Comment by smancio17** [comment]
ah..OMG sorry... Is there a q&a... I'm new member...

**Comment by Kalashnikitty** [comment]
Read the wiki

chat about the bot: https://discord.gg/8msqsWV

**Comment by DurtyFree** [comment]
This is not a issue.
