### ISSUE TITLE
Recycling Items

### ISSUE THREAD

**Issue by snl1** [PocketMobsters/PokeMobBot#213]
Hello,

is it possible to tell the PokeMobBot to recycle/delete potions, revives etc.? if so, how? 

i always got my inventory full because he keeps all thos shitty potions and like 200 pokeballs even if i changed the value in the config to 50 pokeballs to keep..

**Comment by xfaustx** [comment]
Have same issue right now... mby delete them on start at least?

**Comment by DurtyFree** [comment]
There is currently a bug with recycling items, should be fixed in the newest release coming this evening.
