### ISSUE TITLE
Change the logic

### ISSUE THREAD

**Issue by Fenixxia** [PocketMobsters/PokeMobBot#214]
transfer [14:32:23] Snorlax	 (CP:1423|IV:100.00%) bcs [best (CP:978|IV:100.00%)]  
transfer [14:32:24] Snorlax	 (CP:2223|IV:100.00%) bcs [best (CP:978|IV:100.00%)] 

tranfer [15:36:55] Snorlax	 (CP:1423|IV:100.00%) bcs [best (CP:2223|IV:100.00%)] WHAT???
tranfer [15:36:55] Snorlax	 (CP:2223|IV:100.00%) bcs [best (CP:1067|IV:100.00%)] what-what??
transfer Weezing	 (CP:1157|IV:100.00%)bcs [best (CP:643|IV:100.00%)] 
transfer [15:36:39] Jolteon	 (CP:1712|IV:100.00%) bcs[best (CP:611|IV:100.00%)] 

What was the principle applied in such an exchange? Because these pokemon were caught later than the one that is left? He inventory number is less? The serial number on the tops of the pokemon less?

When performing a basic condition test should go in the parameter LV, not CP.
Because CP etol combinatorial data record of common pokemon. And LV is the level of development regarding the pokemon trainer. CP will be higher at each level with the same IV

**Comment by kyfranky** [comment]
yes please fix the logic masta

**Comment by eslindsey** [comment]
Fixing now.
