### ISSUE TITLE
Berry not recycling, big problem

### ISSUE THREAD

**Issue by KurtCocain** [PocketMobsters/PokeMobBot#219]
I have 300~ berries on all my accounts and no pokeballs, this is a problem because All my accounts are unnammed and never logged on. I need a quick fix to make it recycle proprely =[

**Comment by Fenixxia** [comment]
https://github.com/PocketMobsters/PokeMobBot/issues/216

**Comment by KurtCocain** [comment]
@Fenixxia Did you quote because there's already an issue for it or because there's supposed to be a fix in it? Cause I don't see it :<

**Comment by DurtyFree** [comment]
This should be addressed in the newest release, coming this evening.
