### ISSUE TITLE
Sniping

### ISSUE THREAD

**Issue by legend6868** [PocketMobsters/PokeMobBot#234]
Hello everyone,

Does the snipe function work for everyone?

It does not work for me. Please help.

**Comment by mvegter197** [comment]
@legend6868  Are you using release or dev version?

**Comment by legend6868** [comment]
@mvegter197 Hi mvegter, I used https://github.com/PocketMobsters/PokeMobBot/releases this version.

**Comment by mvegter197** [comment]
@legend6868 Then that is correct sniping has been fixed but not yet released.

**Comment by legend6868** [comment]
@mvegter197 I'm just wondering that when it will be released.

**Comment by DurtyFree** [comment]
Sniping is currently in work, the next release will address this issue. ( Which will be released today )
