### ISSUE TITLE
(ERROR) FarmPokestopsTask

### ISSUE THREAD

**Issue by icrona** [PocketMobsters/PokeMobBot#237]
![image](https://cloud.githubusercontent.com/assets/19201715/17298629/f08a6d8e-5834-11e6-8aab-417c458905f8.png)

**Comment by Apocalyptov4** [comment]
I'm having the same problem....

**Comment by johnsiah91** [comment]
try changing the default coordinates, I changed it and it is working now.

**Comment by MariusNV** [comment]
Me too. Maybe is because my inventory is full? Do you guys have it aswell?

**Comment by johnsiah91** [comment]
pretty sure it is not inventory, because I threw some stuff away and it still failed.

**Comment by lancerts** [comment]
Yes, i have the issue "inventory is full". However, it happens since the update. I have used the bot and it is fine. But in the morning, i used the updated version and ran into this issue.

**Comment by DurtyFree** [comment]
This will be addressed in the next version.
