### ISSUE TITLE
UseGreatBallAboveCp

### ISSUE THREAD

**Issue by vadimkara** [PocketMobsters/PokeMobBot#24]
"UseGreatBallAboveCp": 1500,
I rise the value o keep greatballs, but bot keeps catching with tem under this value.

**Comment by crazynever** [comment]
You have normal pokeballs?

**Comment by vadimkara** [comment]
yes near 100

**Comment by Zenithxm** [comment]
this happend to me too, pokeball 200 and greatball 15

**Comment by chriszhangz** [comment]
I've already make a pull request to fix this problem.
[https://github.com/PocketMobsters/PokeMobBot/pull/16](url)

**Comment by UntilSunrise** [comment]
fixed
