### ISSUE TITLE
"PokeMobBot stop working" #63

### ISSUE THREAD

**Issue by xfaustx** [PocketMobsters/PokeMobBot#240]
https://github.com/PocketMobsters/PokeMobBot/issues/63
Same stuff.
![1](https://cloud.githubusercontent.com/assets/20742596/17300162/df2cacde-5819-11e6-9655-321055c34ac4.jpg)

**Comment by MystK** [comment]
https://github.com/NecronomiconCoding/NecroBot

This is the link to the real link

**Comment by DurtyFree** [comment]
Should be addressed in the new release coming this evening
