### ISSUE TITLE
What's with the "PRESS a KEY TO CONTINUE" ??

### ISSUE THREAD

**Issue by jawad90** [PocketMobsters/PokeMobBot#241]
i bet nobody likes it especially when the servers are down and it tries to reconnect and stay waiting for someone to press a key while the user is sleeping .....:D

**Comment by fazzertron** [comment]
You can disable that - it's in the config file as:
```StartupWelcomeDelay (Value):
When PokeMobBot runs, if this is set to 'true', it will ask for you to verify the coordinates before proceeding. Setting it to 'false' will skip this prompt.```

Check the config wiki in future :-)

It's there because when the bot auto updates, it used to just restart and you could in the default location and get banned.

**Comment by DurtyFree** [comment]
You can actually disable it by disabling StartupWelcomeDelay, will be default false in the next release.

**Comment by jawad90** [comment]
lol my bad.... thanks guys

**Comment by jawad90** [comment]
so i should keep it on then so the coords wont change

**Comment by fazzertron** [comment]
Your choice. With the soft ban bypass ability, it's not so necessary now.

**Comment by jawad90** [comment]
awesome !! thx man
