### ISSUE TITLE
Transfer all pokemon below IV/CP settings

### ISSUE THREAD

**Issue by She3p** [PocketMobsters/PokeMobBot#256]
Hi this thread was closed so I think I didnt explain correctly.
https://github.com/PocketMobsters/PokeMobBot/issues/162

I want the bot to transfer all pokemon below IV/CP settings. So if I have the settings of 5000CP and 90IV and I catch one snorlax who is 2500CP 87IV and while I have no other snorlax in my inventory I want it to transfer this snorlax as he doesnt meet my minimum requirments.

**Comment by Kondeek** [comment]
Try this:
In TransferFilter set for snorlax
"KeepMinCp": 5000,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 0

**Comment by She3p** [comment]
i want it for all pokemon, but 0 returns a error.

**Comment by She3p** [comment]
Update: 0 now empties all pokes below threshold.

**Comment by Kondeek** [comment]
So idk, just keep this 1 snorlax with 
"KeepMinDuplicatePokemon": 1, i think its not a big deal

**Comment by Kondeek** [comment]
Btw. u will never get a snorlax with 5000 cp xD max is ~3100
