### ISSUE TITLE
Bot doesn't recycle Razz Berry Item

### ISSUE THREAD

**Issue by 4vizz** [PocketMobsters/PokeMobBot#260]
Since today I have problem because bot stoped recycling Razz Berry item. I set it to 80 and when I log in PoGo on smartphone after "Inventory is full" I saw ~240 Razz Berry. Other items like pokeballs, revives & potions aren't problem

**Comment by olafmeister** [comment]
will be fixed in the new release

**Comment by 4vizz** [comment]
Okay, thanks for reply
