### ISSUE TITLE
Typos in Inventory.cs

### ISSUE THREAD

**Issue by dakre18** [PocketMobsters/PokeMobBot#262]
This only affects Inventory.cs to my knowledge.

Around line 236, in the function GetItemsToRecycle(ISession session), the first variable is named "itemsToRecylce" instead of "itemsToRecycle."

Around line 501, there's a comment with the same typo "// Recylce all of this type."

Does not affect functionality.

**Comment by DurtyFree** [comment]
Fixed, thanks!:)
