### ISSUE TITLE
PTC servers are down

### ISSUE THREAD

**Issue by eslindsey** [PocketMobsters/PokeMobBot#266]
This is a known issue. Please _**do not**_ report it, or post about it in the Discord chat. It is not related to the bot, and service will resume once their servers are back up again. In the mean time, you should still be able to use Google authentication. Thanks!

**Comment by LNSDISCORDER** [comment]
me3 why dev, why your shit code not let me log!

**Comment by DurtyFree** [comment]
Check pokemonstatus  websites.
