### ISSUE TITLE
CANNOT WORK ON VPS while Working perfectly on PC

### ISSUE THREAD

**Issue by rollzhang** [PocketMobsters/PokeMobBot#27]
VPS: Windows Server 2012R2
Here's the log.
http://imgur.com/W9JDdW1

**Comment by septemus** [comment]
VPSes have been blocked.

**Comment by rollzhang** [comment]
@septemus  any solution for unblock?

**Comment by lilsizzle** [comment]
I have been blocked on VPS too, any solutions for this?

**Comment by SchniggSchnagg** [comment]
could you tell me a way for a free VPS - i'm on a mac and want to run the bot

**Comment by TimIsOverpowered** [comment]
Use a VPN

**Comment by PseudoPort** [comment]
Make sure your vps has .NET installed. I manage to run 2 bots right now in my AWS using winserver 2012R2

**Comment by Starfola** [comment]
What VPN are you guys using? Can't seem to run a vpn on my aws vps.

**Comment by Cliipz** [comment]
VPS works fine just use a VPN im currently on Mullvad vpn.
@SchniggSchnagg there is nothing like a free vps just pay the 5-10$ for a month at digitalocean.

**Comment by mafimchen** [comment]
@PseudoPort which version of .NET you install? win2012 has .NET by default, and cannot install .NET 4.5 as higher version exist.
