### ISSUE TITLE
Bot spaming [Debug] commands

### ISSUE THREAD

**Issue by Akimata** [PocketMobsters/PokeMobBot#271]
bot constantly spamming this type of message 
[22:19:32] (DEBUG) Looking for incense Pokemon...
[22:19:34] (DEBUG) Looking for Pokemon...
[22:19:34] (DEBUG) Looking for incense Pokemon...
[22:19:35] (DEBUG) Looking for Pokemon...

**Comment by DurtyFree** [comment]
Did you compile the version yourself?

**Comment by Akimata** [comment]
yes i dowloaded files and compiled them by myself, becouse at release version i have some sort of error at startup

**Comment by DurtyFree** [comment]
You need to compile it as release version, not debug. Google that

**Comment by Akimata** [comment]
thx stupid thing, its working properly now

**Comment by DurtyFree** [comment]
No problem, you are welcome:)
