### ISSUE TITLE
Unable to authorize with google OR ptc

### ISSUE THREAD

**Issue by DarkenHmK** [PocketMobsters/PokeMobBot#273]
Initially, I edited auth.JSON to utilize ptc, entered my credentials, and left the google fields 'null'. 

I tried running pokemobbot, and it still attempted to log me in with Google. Said I needed to enter google acct and password. 

I've re-edited auth.JSON, set the login type to google, with updated google credentials, and left the ptc stuff 'null'. 

It still tries to log in with google, but continues to say I've not entered an email or password.

**Comment by Ambushed91** [comment]
{
  "AuthType": "ptc",
  "GoogleRefreshToken": null,
  "GoogleUsername": null,
  "GooglePassword": null,
  "PtcUsername": "Username",
  "PtcPassword": "Password"
}

**Comment by DarkenHmK** [comment]
Indeed, I formatted auth.JSON just like this, but it continued to attempt to log in with google instead. 

I've since tried switching auth.JSON to my google credentials, with no success in either format.

**Comment by DarkenHmK** [comment]
My current auth.JSON looks exactly like this, but with my own credentials. 

{
"AuthType": "google",
"GoogleRefreshToken": null,
"PtcUsername": null,
"PtcPassword": null,
"GoogleUsername": "ReachForTheSkies@gmail.com",
"GooglePassword": "howdyhowdyhowdy"
}

**Comment by DarkenHmK** [comment]
I've now switched it back for ptc, and it still attempts to login with google. 

{
"AuthType": "ptc",
"GoogleRefreshToken": null,
"GoogleUsername": null,
"GooglePassword": null,
"PtcUsername": "My info",
"PtcPassword": "My info"
}

I am unable to connect successfully with either ptc or google, but it attempts to log with google whichever way I set it.

**Comment by DurtyFree** [comment]
Please try to get help at the Discord and check our wiki.
This place is not for config related errors.
