### ISSUE TITLE
bot crashed - w7 x64

### ISSUE THREAD

**Issue by jumitate** [PocketMobsters/PokeMobBot#274]
hi all, 
the bot just crashed - print screen here: http://www.awesomescreenshot.com/image/1442664/de9c09a0082f15bb68eabd15392726ef

full details of error below:
Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	PokeMobBot.exe
  Problem Signature 02:	1.0.0.0
  Problem Signature 03:	579eb6c8
  Problem Signature 04:	Pokemon.Go.Rocket.API
  Problem Signature 05:	1.0.0.0
  Problem Signature 06:	579eac8f
  Problem Signature 07:	16c
  Problem Signature 08:	456
  Problem Signature 09:	WOIYAB3JHC0Z01RKTCEHDRWGNRJMZ2B2
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

Please advise if you need additional info.

Best

**Comment by DurtyFree** [comment]
We can not resolve that. Please try to google your problem ( As it seems to be OS related, not software related )

**Comment by jumitate** [comment]
you might be right, but from what i see, there is a specific problem with the .exe of the bot, not with the system itself as no other processes crashes like the bot did.
it might be a specific condition that is triggered, but it may be that the bot is not stable enough.
