### ISSUE TITLE
[Ok or Bug] Dump table

### ISSUE THREAD

**Issue by Fenixxia** [PocketMobsters/PokeMobBot#275]
Dump data does not fall into a single cell. All in one cell of one column.
As it should be? Or is it a bug?

![5](https://cloud.githubusercontent.com/assets/20652928/17308423/9a679d24-5842-11e6-8fed-830ac7d9d81c.jpg)

**Comment by imthe666st** [comment]
Import it as a CSV, not copy/paste.

**Comment by Fenixxia** [comment]
I don't copy/paste. This type is the file created by the bot. Is this normal?
What is it better than the Notepad file?

**Comment by imthe666st** [comment]
Usually there should be an option to import a table as CSV file, that will separate the columns by the comma. Google Spreadsheet has such a feature for example.

**Comment by Fenixxia** [comment]
Successfully. Thank you. Close.
