### ISSUE TITLE
Cannot authorize

### ISSUE THREAD

**Issue by Xen00x** [PocketMobsters/PokeMobBot#277]
Hi! Bot was working fine, till it crashed and afterwards i cannot connect using PTC. I tried to reinstall bot but this not helped. Tried on two different machines. With Pokemon GO app i could connect with this account.

Initializing Rocket logger at time 8/1/2016 11:57:24 PM...
[23:57:25] Perfect! You already have the newest Version 1.0.1
[23:57:25] Logging in using Ptc
[23:57:40] PTC Servers are probably down OR your credentials are wrong. Try google
[23:57:40] Trying again in 20 seconds...

**Comment by jumitate** [comment]
same problem here, also crashed, then it returns this:
http://www.awesomescreenshot.com/image/1442694/6c949b23756351e755e7fd73d8113796

i made no changes to the config file or auth file.

thanks

**Comment by Fenixxia** [comment]
http://ispokemongodownornot.com/   The authorization server has problems. And you too for that.

**Comment by Xen00x** [comment]
Thanks! Seems i was lucky to login after that with Pokemon GO app :D

**Comment by Fenixxia** [comment]
Please close the query if we all agreed.
