### ISSUE TITLE
Issue resolved.

### ISSUE THREAD

**Issue by DarkenHmK** [PocketMobsters/PokeMobBot#284]
Issue resolved. Thank you kindly. :)

**Comment by lyrex** [comment]
It doesn't help anybody if you open an issue here with no information at all.
If you need any help with the bot, check out our Discord at https://discord.gg/8msqsWV and join the channel #helpme.
Issues are for bug reports and not for help inquiries. You won't get any specific help here.

**Comment by DarkenHmK** [comment]
My previous post was far more detailed, but, again, was deleted. 

I was trying to report a bug, which I outlined in great detail, only to be forced to start another thread. It felt somewhat silly to re-type everything I just posted, only to have it get deleted again.

Thank you all the same for the Discord information. :)
