### ISSUE TITLE
Program will continue after a key press?

### ISSUE THREAD

**Issue by FuckItAll** [PocketMobsters/PokeMobBot#302]
Wondering if you could make this an option to start the bot back up, I occasionally get a few errors and the bot will stop untill i press a key. This could be quite annoying when you wake up and see that your bot hasn't done much overnight
ex: http://prntscr.com/c0fmtl

**Comment by Ambushed91** [comment]
"StartupWelcomeDelay": false,

**Comment by FuckItAll** [comment]
Ohh, thats what that option was for?
