### ISSUE TITLE
razz berries not recycling

### ISSUE THREAD

**Issue by proud2bandy** [PocketMobsters/PokeMobBot#310]
For some reason, the razz berries in my inventory won't get recycled. I tried setting the recycle filter to 50 but I still have over 50 razz berries.

**Comment by littlemonster1** [comment]
should have been fixed through PR #295

**Comment by marcosabruna** [comment]
Same here. Been getting full items with over 200 of them all the time.

**Comment by techyowl** [comment]
yeah getting the same results

**Comment by Daylend** [comment]
I've mentioned this issue in #345
