### ISSUE TITLE
(Attention) Encounter problem : EncounterPokemonFled

### ISSUE THREAD

**Issue by CraftworldEldar** [PocketMobsters/PokeMobBot#323]
Since updating keep getting this error message.. any suggestions ?

**Comment by zhu8808** [comment]
same here

**Comment by jawad90** [comment]
same we dont even now the meaning of it

**Comment by vfuyong** [comment]
guess it is a new bug

**Comment by uab2411** [comment]
I am getting this too

**Comment by vfuyong** [comment]
this is happening very frequently..

**Comment by howcanihelp** [comment]
This is not a bot error as some people playing it on their phones are having the same issue. When they try to click on a pokemon they disappear.

**Comment by vfuyong** [comment]
Interestingly, I tried to use 1.0.1 I still see the same problem, but it is less frequent?

**Comment by zhu8808** [comment]
change another location

**Comment by vfuyong** [comment]
hmm...i am using a preferred GFX file at the moment. I verified that 1.0.1 does show much fewer errors.

**Comment by vertixy** [comment]
switched back to an old bot (spegeli) and everything seems to run fine again? 
or probably the error isn't reported in the old bot?

**Comment by vfuyong** [comment]
guys, try set walking speed to 5km/h to have a test. My first test seems to run fine.

**Comment by Daylend** [comment]
This issue is being discussed further in #350
