### ISSUE TITLE
You asked for a log of the error:

### ISSUE THREAD

**Issue by Fenixxia** [PocketMobsters/PokeMobBot#329]
![er](https://cloud.githubusercontent.com/assets/20652928/17315430/18616e18-5874-11e6-92b7-574de0e3404f.jpg)
![er2](https://cloud.githubusercontent.com/assets/20652928/17315500/a25e2fa2-5874-11e6-9e48-fb87daeb9007.jpg)

Is this normal? debug-debug-debug....
![er3](https://cloud.githubusercontent.com/assets/20652928/17315511/b5db85ca-5874-11e6-9686-2aceb4c3820b.jpg)

**Comment by CraftworldEldar** [comment]
Same issue how to hide the Debug notification?

**Comment by Aymendje** [comment]
I think it was corrected in the latest commit in dev [db964d8e0e4cda27053d5758c2d1815219b848c7](https://github.com/PocketMobsters/PokeMobBot/commit/db964d8e0e4cda27053d5758c2d1815219b848c7) and shoud be corrected in next release.
So ignore it and wait or recompile
