### ISSUE TITLE
Can't build dev, submodule not available

### ISSUE THREAD

**Issue by FraserKillip** [PocketMobsters/PokeMobBot#333]
Hey,

Is the yamashi Pokemon-Go-Rocket-API a private repo now? I get the following error on the 'development' branch as of commit 2efc2c50703461afc851f05cae4136cf7984a8c9
Note: this occurred before the commit but still exists at the stated commit

$ git submodule update
remote: Repository not found.
fatal: repository 'https://github.com/yamashi/Pokemon-Go-Rocket-API/' not found
Unable to fetch in submodule path 'Pokemon-Go-Rocket-API'

**Comment by bmdr38** [comment]
yamashi's repo is no longer referenced in the submodule anyways.

Pull latest, then git submodule update --init --recursive followed by git pull --recurse-submodule (just to be safe) should fix your problem.

Alternatively, get a fresh clone.

**Comment by FraserKillip** [comment]
Re-clone fixed it thanks, git was failing to update the submodule link.
