### ISSUE TITLE
502 Bad Gateway Issue?

### ISSUE THREAD

**Issue by Cappeen** [PocketMobsters/PokeMobBot#336]
Does anyone know what this "502 Bad Gateway: Server is under heavy load!" Thing is, and how to fix it? thanks.

**Comment by Daylend** [comment]
That's either SkipLagged or PokeSniper's servers being unable to keep up with all the traffic. AKA, they're offline.

There's no fix, since it's nothing on our end. We may switch to other APIs at some point.
