### ISSUE TITLE
Constant Debug Spamming

### ISSUE THREAD

**Issue by PKMWM1** [PocketMobsters/PokeMobBot#338]
Ever since I relaunched PokeMobBot and it updated, it now outputs many lines of debugtext, "looking for Pokemon". I don't know why this is happening and I have no idea how to fix it. I don't know hot to "compile" or build another version. Help is very much appreciated.

**Comment by jinkawasaki333** [comment]
@PKMWM1 Try the latest release (https://github.com/PocketMobsters/PokeMobBot/releases/tag/v1.1.3). It's fix, kinda.. Instead of Debug spam, it gives "(Attention) Encounter problem: EncounterNotFound".

**Comment by marcosabruna** [comment]
Hmm it won't let me open the new release. It crashes and coming comes up when i open it.

**Comment by jinkawasaki333** [comment]
Could you attach your print screen just before it crashes?

**Comment by Aymendje** [comment]
@jinkawasaki333 working fine for me, but I used the config files of 1.1.0

**Comment by eslindsey** [comment]
#195 causes Debug level logging automatically for internal releases. Probably somebody forgot to switch to Release before packaging. The debug notices shouldn't be in future releases.
@DurtyFree
