### ISSUE TITLE
PokeMobBot.exe.config connectionStrings

### ISSUE THREAD

**Issue by Zerotask** [PocketMobsters/PokeMobBot#349]
I saw there is a new file in the root called connectionStrings PokeMobBot.exe.config adn there is a tag connectionStrings with placeholder

`<connectionStrings>
    <add name="Pogo"
         connectionString="DatasetId = YOUR_DATASET_ID; CertificateFilePath = C:\Path\To\Your\Certificate\File-privatekey.p12; ServiceAccountId = your-service-account-email@developer.gserviceaccount.com; CertificatePassword = notasecret" />
  </connectionStrings>`

Do we must change here anything?

**Comment by Daylend** [comment]
No, I wouldn't change any of that. As far as I know that has to do with the certificate we're using for the websocket.
