### ISSUE TITLE
Necrobot Update

### ISSUE THREAD

**Issue by Zerotask** [PocketMobsters/PokeMobBot#35]
Hey all, I've got an update of NecroBot  a few minutes ago and when I looked up the github project page I saw that the project was hacked or something like that and now I'm insecure about my auth.json if they have read / send it to a server.

**Comment by pokepleb** [comment]
It wasn't hacked.

Straight from Discord chat:
"TL;DR Necro was holding us back, we have elected a new project lead and will no longer be working with Necro. So we have forked all of the work into a new repo and rebranded. The bot will remain free! Extra info: The new version will be faster and teleporting has been added!"

**Comment by Zerotask** [comment]
Thank you for the fast reply. :)
And this is the new official repo? And the new project lead is PocketMobsters?

**Comment by maartenpeels** [comment]
And, your authwill NEVER be send to/seen by others.

**Comment by EyesReye** [comment]
Wait @maartenpeels Can Necro hack my account? since i filled in the Username+password?

**Comment by maartenpeels** [comment]
No they can't! Otherwise i wouldn't be using it

**Comment by EyesReye** [comment]
Okay,
