### ISSUE TITLE
Encounter Problem: EncounterNotFound

### ISSUE THREAD

**Issue by yomy28** [PocketMobsters/PokeMobBot#350]
its been giving to me a lot of encounter problems since the update

**Comment by darkangel89** [comment]
pokesnipers.com did not providing any rare pokemon coordinates anymore, turn off your pokesniper server option. it makes you cant snipe anything.

**Comment by Daylend** [comment]
I'm trying to get to the bottom of this. So far it seems like location might have something to do with it. Can you please post your default coordinates?

**Comment by vertixy** [comment]
Have been using Sydney coordinates
"DefaultLatitude": -33.859215,
"DefaultLongitude": 151.2129155,
"DefaultAltitude": 6.2,

Same coordinates work fine on other accounts. Same coordinates work fine on old spegeli bot too.
