### ISSUE TITLE
(ATTENTION) SkipLagged is down or SnipeRequestTimeoutSeconds is too small!

### ISSUE THREAD

**Issue by icrona** [PocketMobsters/PokeMobBot#354]
"SnipeRequestTimeoutSeconds": 5,

**Comment by Cappeen** [comment]
skiplagged is down for maintenence dont worry

**Comment by Walawalawala** [comment]
cappeen, is there somewhere I can check for when it goes back up?

**Comment by Daylend** [comment]
Mentioned in #341. You can check if it's up by visiting this link: https://skiplagged.com/api/pokemon.php?bounds=50.042207,-110.677313,50.041707,-110.676313

If it lists pokemon, it's up.
