### ISSUE TITLE
Never Snipe any Pokemon at all

### ISSUE THREAD

**Issue by icrona** [PocketMobsters/PokeMobBot#360]
right config..
lastest release..

pogofeeder got the data from channel but i never snipe any pokemon
![image](https://cloud.githubusercontent.com/assets/19201715/17318905/3330e4ea-58b4-11e6-9551-edf86d13ac6a.png)

is it because of pokesnipers ? or.. ?

**Comment by Daylend** [comment]
Mentioned in issue #341
