### ISSUE TITLE
[Suggestion] Duplicate Transferring Algorithm Addendum

### ISSUE THREAD

**Issue by userix** [PocketMobsters/PokeMobBot#364]
I would like to suggest an additional filter option when transferring duplicates.  Is it possible to have a maximum number of a specific species kept, in addition to current filter options?  And also apply it as a global option too? 

 For instance, if I have Eevee set to transfer out at` min CP:900, min IV:95, minDuplicatestokeep: 2`,  it will keep all Eevees that are over CP 900, so it's possible I will have a cluttered storage of 20+ Eevees over 900 CP, since they all pass the current transfer logic.

I tried setting the CP filter to an arbitrarily high number like CP:9000, min IV:950, minDuplicatestokeep: 2 to see if this would do what I want, but turns out, it will automatically transfer out the newly captured monster even though it might have a CP that is greater than the minimum 2 species I already have in inventory.  

It would be great if a maximum # of each species to be kept in addition to the current transfer logic can be implemented.  That way I can have it transfer out all Eevees that fail the criteria and yet keep a max of two >900 CP Eevees, instead of an infinite number of Eevees over 900 CP.

**Comment by Valmere** [comment]
minduplicate is already an option.
