### ISSUE TITLE
Are "UseGreatBallAboveCp" and "UseUltraBallAboveCp" supposed to be removed in 1.1.3? And a couple of concerns.

### ISSUE THREAD

**Issue by ArmsAsuncion** [PocketMobsters/PokeMobBot#368]
The settings seems to be gone.

Also, can you guys clear things up about the new "UseGreatBallBelowCatchProbability", "UseUltraBallBelowCatchProbability", and "UseMasterBallBelowCatchProbability"?

I tried putting 22% (22.0) for UseGreatBallBelowCatchProbability, and 10% (10.0) for "UseUltraBallBelowCatchProbability", however, this setting seem to be using all Ultra balls.

However, I read that is was supposed to be below 1, so I changed them to 0.22 and 0.10. It used a Great ball to a Magikarp with 50%+ chance, and used a Pokeball to a Charmander with 21% chance. What gives?

A little tip: Can you update the Wiki to include the changes for the config if you're not going to explain it in the change logs. It just makes people confused.

**Comment by MadEyez** [comment]
@ArmsAsuncion
You have to put in the values "0.22" and "0.1" instead of "22.0" and "10.0".
The range is from 0.00 to 1.00.

**Comment by ArmsAsuncion** [comment]
@MadEyez Well, as you see, I already tried that. I said:

> However, I read that is was supposed to be below 1, so I changed them to 0.22 and 0.10. It used a Great ball to a Magikarp with 50%+ chance, and used a Pokeball to a Charmander with 21% chance. What gives?

**Comment by ArmsAsuncion** [comment]
Here's an example. It also uses Great Ball to a 100% Chance Pokemon.

Edit: I think I know what caused it. The default setting ""UseGreatBallAboveIv": 0 causes it, like it was before for CP.

![image](https://cloud.githubusercontent.com/assets/16745791/17321496/740aab6a-58cb-11e6-88fc-a975a98371ab.png)

**Comment by MadEyez** [comment]
Hm... either you edited your comment while I was answering or I didn't read the hole comment...

What was the IV rating? Maybe these additional settings where causing the usage.

**Comment by ArmsAsuncion** [comment]
@MadEyez Yeah. I think I found what caused it. The "UseGreatBallAboveIv" and "UseUltraBallAboveIv" aren't supposed to be 0. That causes the bot to use Ultraballs on all Pokemon (In my case, I set "UseUltraBallAboveIv" to 98, and left "UseGreatBallAboveIv" 0, which used up all my Great balls and used a Pokeball instead on a Charmander with 21% chance.)

**Comment by toliman** [comment]
Perhaps a config parser might be an added step to check values are in the correct ranges when loading or merging/upgrading the config to a new version.

**Comment by ArmsAsuncion** [comment]
Yeah. Maybe they could just use percentage values as universal values for catch rates. Then the program could just divide it by 100.

**Comment by pokepleb** [comment]
@ArmsAsuncion Yes they should. How are we supposed to know its 0 - 1 instead of 0 - 100 when the last makes a lot more sense duh.
