### ISSUE TITLE
preview of changes in config file

### ISSUE THREAD

**Issue by jumitate** [PocketMobsters/PokeMobBot#371]
Dear Team,

Do you think it would be possible to "record" a bot session with all the events (pokestops visited, pokemons catches/etc.) in order to better understand and test each change in the config file? (or maybe use the bot logs to replay an already ended session)

usually it takes up to 1h to understand how a particular change in the config affects the behavior of the bot - overall performance (xp, what the bot is doing and how, etc.) - so maybe a way of simulating how config changes affect how the bot works would be useful.

Thank you

**Comment by eslindsey** [comment]
Replay this where/how? It sounds like the bot log is exactly what you're looking for: open it up in Notepad and go through it, to see what the bot did.

**Comment by jumitate** [comment]
@eslindsey - thanks for your reply. I am not interested in the log to see what actions happened, but as a way to understand how the bot acted under certain settings in config.

changing the config settings would then mean having to leave the bot run again for ~1h to see how the bot acts under updated settings and instead of leaving the bot to run, to just re-play the last log under the new settings - which can run faster that the actual 1h you would need to understand if the new settings are what you intended to set.

it's just a simulation using different config files to build the one you need for that specific moment in the shortest time possible.

**Comment by eslindsey** [comment]
Ah, I understand now, that makes sense. This would be an interesting feature, but I think it would be impossible since so many of the settings actually change how the bot behaves, and what information it receives from the server. For example, changing the `Teleport` value would prevent you from replaying, because it changes how the bot actually moves, and hence what data it gets from the server.

**Comment by jumitate** [comment]
but if you already have a teleport run of 2h, and you still want to have teleport enabled but do a change that would not impact much, just slightly....

anyway it's just an ideea that would solve a lot of the discussions we're having about different config settings/etc.

thanks
