### ISSUE TITLE
[Bug] When AutoUpdate=false bot shows wrong coords

### ISSUE THREAD

**Issue by MrJokerer** [PocketMobsters/PokeMobBot#374]
When I have autoupdate turned off and start the bot it only loads up the default coords and will not load the coords from the config.  I dont know if it goes to all default settings because I never run it. Was wondering if this happens to anyone else or if its my problem

**Comment by guay0ta** [comment]
can u share the upper part of your config? I got autoupdate turned off and for me everything works fine..

**Comment by MrJokerer** [comment]
"AutoUpdate": true,
  "TransferConfigAndAuthOnUpdate": true,
  "DumpPokemonStats": false,
  "AmountOfPokemonToDisplayOnStart": 10,
  "StartupWelcomeDelay": true,
  "TranslationLanguageCode": "en",
  "WebSocketPort": 14251,
  "Teleport": false,
  "DefaultLatitude": 40.76486,
  "DefaultLongitude": -73.972785,
  "DefaultAltitude": 10.0,
  "WalkingSpeedInKilometerPerHour": 20.0,
  "MaxSpawnLocationOffset": 10,
  "MaxTravelDistanceInMeters": 2500,
  "UseGpxPathing": false,
  "GpxFile": "GPXPath.GPX",


It might not be because of that but I noticed it happening after I started to mess with that.  Turning it back true doesnt always fix it.  Sometimes i just have to wait a little bit and then it shows correct cords

**Comment by guay0ta** [comment]
Exactly. "MaxSpawnLocationOffset": 0 would result in Lat: 40.76486, Long: -73.972785

**Comment by eslindsey** [comment]
Close issue, please.

**Comment by MrJokerer** [comment]
thanks
