### ISSUE TITLE
Gpx-Pathing doesn't follow enitre path

### ISSUE THREAD

**Issue by myrmos** [PocketMobsters/PokeMobBot#375]
When I use GPX-Pathing, the bot stops at seemingly random points to follow the path, but reverts to the starting location.

[route.txt](https://github.com/PocketMobsters/PokeMobBot/files/395992/route.txt)

**Comment by littlemonster1** [comment]
repetition of #229

**Comment by pzinsta** [comment]
I am getting a similar problem with gpx pathing. After 30 minutes of running, an error message appears in the log 

`Niantic Servers unstable, throttling API Calls.`

(this is related to #179, which must have been fixed)

the bot seems to go on "walking", but looks like it doesn't follow the path anymore and somehow returns to the starting point instead.

```
Version: 1.1.3
"AuthType": "ptc"
```
