### ISSUE TITLE
Debug spam every second

### ISSUE THREAD

**Issue by Leigha888** [PocketMobsters/PokeMobBot#376]
[02:38:54] (DEBUG) Looking for Pokemon...
[02:38:55] (DEBUG) Looking for incense Pokemon...
[02:38:55] (DEBUG) Looking for Pokemon...
[02:38:56] (DEBUG) Looking for incense Pokemon...

Literally every second spamming this.

**Comment by mvegter197** [comment]
@Leigha888 You need to build it as a release instead of debug.

**Comment by Leigha888** [comment]
Can you simplify that for me because I dont have a clue what you mean

**Comment by mvegter197** [comment]
@Leigha888 Did you download the source code or the release?

**Comment by Leigha888** [comment]
The release

**Comment by mvegter197** [comment]
@Leigha888 I downloaded the latest release and I don't have this problem.

**Comment by Leigha888** [comment]
I just redownload and issue resolved. Idk why it did that, strange af.
