### ISSUE TITLE
2-step authorization

### ISSUE THREAD

**Issue by xardover** [PocketMobsters/PokeMobBot#38]
Sorry for the previous post, but i have another issue.

How do i exactly login with 2-step google authorization?

I created an app code (Other as device yes), pasted code in GoogleRefreshToken with "" but its not working.

Here the screenshot of auth.json: http://i.imgur.com/AZSG12R.png
And console: http://i.imgur.com/7DM5t4I.png

**Comment by NinjaKemuri** [comment]
This code should be placed into the password field.
Replace your password with the app code; leave refresh token blank.

**Comment by xardover** [comment]
Thanks, this should be clarified in instructions

**Comment by imyhxy** [comment]
use a app password
