### ISSUE TITLE
a way to check bot inventory

### ISSUE THREAD

**Issue by jumitate** [PocketMobsters/PokeMobBot#381]
Dear Team,

Can you please in the next version add a way to check the bot inventory (from logs or from CMD window) as opening the app on mobile to check and maybe discard some items would bring the bot back to your device location rather that putting the bot offline and then online again in the same location.

thank you

**Comment by mossimokim** [comment]
You can check it by disabling location(Turn off GPS) on your mobile device and opening the app. It will not change your location.

**Comment by jumitate** [comment]
you are right, but unfortunately google uses info like the wireless network or gsm triangulation (if you use data) to pin-point you together with IMEI and other device identification.

my current setup is laptop connected to BT-WIFI hot spot - I can asume that laptop doesn't provide all those nasty info that the app i feeding back to google and anyway mobile devices running Android scan for BT devices or Wi-FI network to pin-point location even if you disable them in android privacy feature - they also have account history, etc.

so it would be helpful to be able to see account inventory from logs or the command prompt.

thanks

**Comment by mossimokim** [comment]
@jumitate Nothing you said is something new. I was just trying to help you with your issue "**opening the app on mobile to check and maybe discard some items would bring the bot back to your device location rather that putting the bot offline and then online again in the same location**"
Your hot spot can't be triangulated you say?

**Comment by jumitate** [comment]
@mossimokim - you are right, nothing i said is new. i appreciate your feedback and i agree it can be a quick solution (thank you for this) - but this would expose the account to teleportation which i want to prevent. 

I am using BT-WiFi hotspots as they use dynamic IPs and they actually bounce to several locations. As google doesn't have access to BT routers (i hope) it cannot (or it can?) do a triangulation based on other wireless networks that intersect with the hotspot I am connected to....

**Comment by jumitate** [comment]
v1.3.1 displays your inventory so this can be closed - thank you

![image](https://cloud.githubusercontent.com/assets/20780918/17326676/b032b70c-58aa-11e6-85ad-c604181148dc.png)
