### ISSUE TITLE
Berries are not being thrown away

### ISSUE THREAD

**Issue by megaDrummerxxl** [PocketMobsters/PokeMobBot#392]
The bot just throw away pokeballs, potions etc but no berries, what inevitably overflows the inventory making it impossible to loot pokestops

**Comment by jinkawasaki333** [comment]
@megaDrummerxxl What release version are you using?

**Comment by megaDrummerxxl** [comment]
Where can I see that? I believe it to be the newest one, because auto update is turned on and at startup it says that I've already got the newest version

**Comment by vapp13** [comment]
I'm using the release version v1.1.3 and is not working for me neither.
My config is "TotalAmountOfBerriesToKeep": 30

**Comment by megaDrummerxxl** [comment]
![berry](https://cloud.githubusercontent.com/assets/19912590/17326143/a6737580-58af-11e6-8f6e-e6a04e362bfe.png)
There's also never a output that would say that berries have been deleted

**Comment by pokepleb** [comment]
As a temporary fix you can add 
    {
      "Key": "itemRazzBerry",
      "Value": 30
    }
To your ItemRecycleFilter array

**Comment by megaDrummerxxl** [comment]
that's already in the config file

**Comment by eslindsey** [comment]
Duplicate of #345 
Please check for issues before making a new one, thanks!

**Comment by megaDrummerxxl** [comment]
true, sorry!
thanks for the help anyways, now it seems to work. Just downloaded the newest version and set it up fresh
