### ISSUE TITLE
TotalAmountOfXToKeep is not respected

### ISSUE THREAD

**Issue by pokepleb** [PocketMobsters/PokeMobBot#395]
Having those items removed by default from ItemRecycleFilter, I thought it would be handled automatically just by those 3 settings (TotalAmountOfPokeballsToKeep, TotalAmountOfPotionsToKeep and TotalAmountOfRevivesToKeep) which sounds pretty neat. However those values are not respected. I have the following settings:

  "TotalAmountOfPokeballsToKeep": 140,
  "TotalAmountOfPotionsToKeep": 80,
  "TotalAmountOfRevivesToKeep": 60,
  "RecycleInventoryAtUsagePercentage": 80.0,

And no pokeballs or potions or revives inside ItemRecycleFilter but the bot doesn't seem to recycle anything. (I ended up with 299 pokeballs, 103 revives, 112 potions, some super potions and around 50 razz berries along with some misc stuff having an overflowing inventory 600+ of 350 showing up on my phone).

Using the latest release.

**Comment by vapp13** [comment]
RecycleInventoryAtUsagePercentage must be 0.8 instead of 80.0. I don't know if that's causing the issue.

**Comment by pokepleb** [comment]
I will try it, if that's the case it clearly needs to change since it states percentage. And to be honest we should have unified settings across the whole bot so all values will be percentages instead of 0 - 1 (#368). Like it is now, its really senseless and confusing.

**Comment by Zer0t3ch** [comment]
@vapp13 This seems to fix it for me. The wiki implied that using that number would override the constant numbers set for individual items, though. Does it override those or does it just set the filled percentage at which recycling is triggered.

**Comment by Zer0t3ch** [comment]
@pokepleb There's nothing wrong with using a 0-1 decimal scale for percentages, but it needs to be made more clear, either in a comment in the configs, or on the wiki.

**Comment by pokepleb** [comment]
@Zer0t3ch that's why it should be 0-100, because its more clear alone, without people needing to think, look, or search up wiki after they've bugged their own bot with settings

**Comment by vfuyong** [comment]
I am using 0.9 and most of the time, potions/revives are not recycled. Although sometimes it does.
