### ISSUE TITLE
Bot stop working after some (random) time 

### ISSUE THREAD

**Issue by erasem** [PocketMobsters/PokeMobBot#396]
Bot stop working/updating status after some time but resumes when i press Ctrl+C, check screenshot.

![untitled](https://cloud.githubusercontent.com/assets/9110977/17326223/ce6a85ae-58a7-11e6-97c0-50e1a991f649.png)

**Comment by hendrawd** [comment]
I have the same problem too, why Ctrl+C? Isn't is just quit the command prompt?

**Comment by Valmere** [comment]
Open a new issue if the problem persists after the next release
