### ISSUE TITLE
Sniper not working as expected

### ISSUE THREAD

**Issue by jordyvandomselaar** [PocketMobsters/PokeMobBot#399]
Whenever I start pokemobbot it'll say `(INFO) [Sniper] Sniping a Nidoqueen with 60 IV at 34.005966,-118.490366...` But it doesn't catch it?

**Comment by mennas** [comment]
same question here

**Comment by colaxio** [comment]
same

**Comment by jordyvandomselaar** [comment]
After watching it for a bit I have concluded that it sometimes takes up to 10 seconds before it catches it, it might take a while but it usually does get it even after walking away

**Comment by SuperAero** [comment]
theres also the chance that the coords supplied are fake

**Comment by jordyvandomselaar** [comment]
I guess that's also possible

**Comment by chauhan-rahul** [comment]
doesnt work for me too!
