### ISSUE TITLE
nothing about gym in bot

### ISSUE THREAD

**Issue by rajitbansal** [PocketMobsters/PokeMobBot#40]
[Search for gyms/pokestops/spawns]

where to get the gyms the bot has searched for ??

**Comment by Zerotask** [comment]
Consider that placing Pokemon in gyms could reveal you as a (gps) hacker. 
When I was conquering gyms in the night I was at a lonely place, placed a Pokemon in it and few seconds later another lad of my team placed his Pokemon, too and there was no human around me. You can simply report that people.

**Comment by rajitbansal** [comment]
that i got i mean it finds the gym right? so where to get the coordinates of gym it finds
