### ISSUE TITLE
LookingForLurePokemon not working

### ISSUE THREAD

**Issue by littlemonster1** [PocketMobsters/PokeMobBot#400]
It only checks for Lure Pokemon once at startup and after that it does not call the function or calls it incorrectly, at least the function is not run anymore since I cannot find another print. I guess it is only supposed to check at pokestops? might be connected to currentFortData since this is the only information difference between lure, incense and nearby pokemon and nearby and incense seem to run fine.

**Comment by eslindsey** [comment]
The Pokestops in question must have active lure modules; if they don't, you will not see the bot checking for lured Pokemon.

**Comment by mystery69** [comment]
https://github.com/PocketMobsters/PokeMobBot/blob/development/PoGo.PokeMobBot.Logic/Tasks/FarmPokestopsTask.cs#L169-L172
