### ISSUE TITLE
PokeSnipers doesn't work. 

### ISSUE THREAD

**Issue by halvors** [PocketMobsters/PokeMobBot#401]
I get the following error when enabling both: "SnipeAtPokestops": true and "UsePokeSnipersLocationServer": true

``
[13:45:19] [Sniper] Scanning for Snipeable Pokemon at 47.5014969,-122.0959568...
[13:45:19] System.NullReferenceException: Objektreferanse er ikke satt til en objektforekomst.
   ved PoGo.PokeMobBot.Logic.Tasks.SnipePokemonTask.SnipeScanForPokemon(ISession session, Location location) i G:\GIT_Projects\PokeMobBot\PoGo.PokeMobBot.Logic\Tasks\SnipePokemonTask.cs:linje 368
[13:45:19] System.Net.WebException: Den eksterne serveren returnerte feilen (503) Server ikke tilgjengelig.
   ved System.Net.HttpWebRequest.GetResponse()
   ved PoGo.PokeMobBot.Logic.Tasks.SnipePokemonTask.PokeSniperScanForPokemon(ISession session, Location location) i G:\GIT_Projects\PokeMobBot\PoGo.PokeMobBot.Logic\Tasks\SnipePokemonTask.cs:linje 439
[13:45:19] [Sniper] No Pokemon found to snipe!
``

**Comment by DeadlyOG** [comment]
Pretty sure the pokesnipers server is not running. Even if you turn off 'usepokesniperslocationserver' and use pokefeeder instead, you still get a server connection issue. However other sources are still posting to pokefeeder so you can still get some snipes in at least.
