### ISSUE TITLE
weird characters for Nidoran

### ISSUE THREAD

**Issue by jumitate** [PocketMobsters/PokeMobBot#404]
Hi Team,

Please see below how special characters are not being displayed properly.

![image](https://cloud.githubusercontent.com/assets/20780918/17327618/f79f2584-58b0-11e6-9847-37da90106d6b.png)

Thanks

**Comment by eslindsey** [comment]
Duplicate of #346 and fixed by #361 
Please check for previous (possibly closed) issues before reporting them, thanks!

**Comment by jumitate** [comment]
i will check for future posts. thank you
