### ISSUE TITLE
Error - current operation cancelled

### ISSUE THREAD

**Issue by jumitate** [PocketMobsters/PokeMobBot#405]
Hi Team,

The following error happened and the bot basically restarted from the previous pokestop - can you please confirm this is normal?

![image](https://cloud.githubusercontent.com/assets/20780918/17327679/55a37784-58b1-11e6-9a9c-24422314c43e.png)

Thank You

**Comment by Valmere** [comment]
Bot doesn't store your last location and if it restarts it will go back to the beginning.
