### ISSUE TITLE
[Suggestion] Add MinimizeToSystemTray property in config

### ISSUE THREAD

**Issue by dogramacigokhan** [PocketMobsters/PokeMobBot#406]
Add MinimizeToSystemTray property in config to enable / disable minimize application to system tray.

**Comment by eslindsey** [comment]
This is not an option for a Console application.

**Comment by dogramacigokhan** [comment]
I know it's not an option for a consola app but is there a rule about this app will be a Console application? You can still use console and implement minimize to tray as suggested in here: http://stackoverflow.com/a/752018/1103965

**Comment by eslindsey** [comment]
So far, scuttlebutt says this project will remain a Console project. I submitted a WinForms UI, as have others, and they have been turned down. The solution you linked requires creating a WinForms application. So, it's a no-go.
