### ISSUE TITLE
Doesn't continue to work after connection lost automatically

### ISSUE THREAD

**Issue by sepehrr** [PocketMobsters/PokeMobBot#407]
Hi
Before I disable "StartupWelcomeDelay", when ever I lost connection and app connected again, it told me to press a key to continue (just like welcome page)
Now I disabled "StartupWelcomeDelay" and when I open the app it doesn't ask me to press a key and start working BUT when I lose connection and connect again,  it is STILL waiting for me to press a key to continue (and without showing any message!) !
please make this little bug fixed.
Thanks

**Comment by lyrex** [comment]
Are you sure you set `StartupWelcomeDelay` to false instead of deleting it?
