### ISSUE TITLE
Whitelist of Snipe Channels

### ISSUE THREAD

**Issue by FatSacks** [PocketMobsters/PokeMobBot#412]
It'd be nice to have the ability to whitelist some of the channels that provide snipe coords to have the bot react to them even if the users don't properly format their post. 

For example any channel that is dedicated to 100 IV pokemon only, if someone posts a location string that is incomplete (missing name or IV amount) by virtue of being whitelisted the bot triggers a snipe for that entry.

**Comment by jinkawasaki333** [comment]
@FatSacks Is sniping working well for you right now? Mine is not working at all :/
