### ISSUE TITLE
[Request] Show Version

### ISSUE THREAD

**Issue by moredhel92** [PocketMobsters/PokeMobBot#424]
When bot start say : You already have the newest version, but i want see what version its
Msg as: : You already have the newest version PokeMobBot V1.0

**Comment by igromanru** [comment]
You can find this information under exe properties -> details.

**Comment by moredhel92** [comment]
then my bot no update xD

**Comment by moredhel92** [comment]
i got 1.0.0.0, no autoupdate?

**Comment by igromanru** [comment]
AutoUpdate don't work at the moment.
