### ISSUE TITLE
How to Reset Connection if Bot , has encounter error, of exceeding radius limit?

### ISSUE THREAD

**Issue by masterpowers** [PocketMobsters/PokeMobBot#428]
Ive encountered so many errors, but this one i think is not yet fixed...
it happens when bot snipes, and it get stuck that place for some reason...

you bot will dump an error message you exceed radius limit

and also it will say it will start running after 5 secs...

but never runs... it just stop there... to fix this i need to close everything and restart...

but it should have to be added in the next release where it will auto restart if it face this error.

this is the error
```
(ATTENTION) You're outside of your defined radius! Walking to start (16007464.5484459m away) in 5 seconds. Is your Coords.ini file correct?
```

**Comment by hendrawd** [comment]
I got the issue too, and sometimes it just stopped at some point of time without any more message

**Comment by hendrawd** [comment]
I think for now, if we need to long botting, like before we going to bed, we need to disable sniping. Or make a simple auto restart to restart the bot periodically

**Comment by sandy1608** [comment]
Maybe an option can be added that if this message is logged the bot will try to restart itself?
