### ISSUE TITLE
pokemon renaming

### ISSUE THREAD

**Issue by Lord255** [PocketMobsters/PokeMobBot#429]
hello,
would it be possible to rename pokemons like:
pokemon_lvl_IV, or pokemon_IV_lvl

so things would look like:
pikachu_26_98
pikachu_23_100

i think it would be really good to see if we want to evolve our pokemons later on, manually.
without this, you cannot be sure you are upgrading the best pokemon what you have and what you can get.

**Comment by marcosabruna** [comment]
There is IV calculators everywhere. But would be nice if there is an option to rename the ones that are over a certain IV.

**Comment by Lord255** [comment]
@marcosabruna: i want to know the level as well in the app as well. i dont wanna evolve my magikarp which is low level but has same ammount of cp. in the app i would see i have 5 magikarps with 100% IV, but only diff is some cp. so it would matter which level they are on.

**Comment by d3structor84** [comment]
@marcosabruna This is already possible.

  "RenamePokemon": true,
  "RenameOnlyAboveIv": true,
