### ISSUE TITLE
[Feature Request] Amount of Super & Ultra balls to keep

### ISSUE THREAD

**Issue by Zerotask** [PocketMobsters/PokeMobBot#432]
At the moment you can define only "TotalAmountOfPokeballsToKeep". I set this to 500 and the result was: 498 Pokeball and 2 Superball. It would be better to seperate this:
- TotalAmountOfPokeballsToKeep
- TotalAmountOfSuperballsToKeep
- TotalAmountOfUltraballsToKeep

**Comment by Lord255** [comment]
in 1.0 this worked:
`  "ItemRecycleFilter": [
    {
      "Key": "itemPokeBall",
      "Value": 100
    },
    {
      "Key": "itemGreatBall",
      "Value": 100
    },
    {
      "Key": "itemUltraBall",
      "Value": 100
    },
    {
      "Key": "itemMasterBall",
      "Value": 100
    },`

idk if it's working in further versions, but if not, then would be nice to have such settings.

**Comment by marcosabruna** [comment]
Atleast my bot keeps my ultra balls first before throwing them away. I have over 200 ultra balls.
