### ISSUE TITLE
Evolution not working???

### ISSUE THREAD

**Issue by xfaustx** [PocketMobsters/PokeMobBot#437]
Venonat	- CP: 481  IV: 59.08%   [Best CP: 402  IV: 89.55%] Candies: 312
Venonat	- CP: 364  IV: 47.63%   [Best CP: 402  IV: 89.55%] Candies: 313
Pidgey	- CP: 239  IV: 33.62%   [Best CP: 370  IV: 65.59%] Candies: 427
Pidgey	- CP: 311  IV: 26.25%   [Best CP: 370  IV: 65.59%] Candies: 428
Weedle	- CP: 236  IV: 38.58%   [Best CP: 130  IV: 53.30%] Candies: 417
Weedle	- CP: 103  IV: 16.82%   [Best CP: 130  IV: 53.30%] Candies: 419

**Comment by marcosabruna** [comment]
Keep in mind this   
 "UseLuckyEggsWhileEvolving": true,
  "UseLuckyEggsMinPokemonAmount": 30,    <-The amount of pokemons you will need to have with enough candy in order to activate the evolve process.

**Comment by xfaustx** [comment]
@marcosabruna 
i know bout that... but befor there was an evolution from time to time of lovestect.t like pidgy ratata ect.

**Comment by jarsever** [comment]
👍   This is an issue on my side also.  It will always transfer pokemon that could be evolved.  Instead it never gets to the 30 it needs by default.
