### ISSUE TITLE
**[Suggestion] Put Pokemons In Gyms if Free Spot Available**

### ISSUE THREAD

**Issue by jawad90** [PocketMobsters/PokeMobBot#439]
this gonna take the bot to the next level ! and gonna help you get that daily 10 pokecoins 

so the bot just gonna leave pokemons in each gym who has a free spot and then claim if the cooldown is off (24 or 20h idk) **however** if the cooldown is still on (eg: 6h remaining) the bot gonna put as much pokemons as he can and wait until the cooldown ends and claim !

the only **problem** now is the bot ability to Recognize its team (valor,instinct,mystic)

**Comment by LNSDISCORDER** [comment]
Nope. Stay well away from automating getting the games only source for free to play players to get coins that cost $

**Comment by jawad90** [comment]
lol ok

**Comment by marcosabruna** [comment]
Really? Why would you even play this game if you also want gym taken automatically?

**Comment by Madcroc** [comment]
I do think it's a creative idea, but I agree more with everyone else on the mater that this is going too far.

**Comment by igromanru** [comment]
Automatically take gym is pretty sick, but the bot is only for educational use.
So it's a challenge to write a algorithm for that.
