### ISSUE TITLE
a PokeMobBot bug?

### ISSUE THREAD

**Issue by Sarginal** [PocketMobsters/PokeMobBot#440]
![bez nazvu](https://cloud.githubusercontent.com/assets/20799949/17338357/6f98b8a8-58e7-11e6-9e62-7a585c644589.png)

**Comment by timmiedinnie** [comment]
No pokesniper website is offline, put `UsePokeSnipersLocationServer `to false  and the error goes away.

**Comment by devoknows** [comment]
Change "UsePokeSnipersLocationServer" to false
