### ISSUE TITLE
Evolution

### ISSUE THREAD

**Issue by Leigha888** [PocketMobsters/PokeMobBot#448]
How do I set the bot to evolve ONLY the pokemon on my evolve list, and not everything that can evolve. I want to save up dratini candy, but evolve pidgeys when I reach the threshold I set up.

**Comment by d3structor84** [comment]
Could you paste your config?

**Comment by Leigha888** [comment]
It wouldnt be right because I stopped it but you can tell me what settings to set to do what I want?

**Comment by d3structor84** [comment]
"EvolveAllPokemonWithEnoughCandy": true,
  "EvolveAllPokemonAboveIv": false,

  "PokemonsToEvolve": [
    "pidgey"
  ],

**Comment by Leigha888** [comment]
This will still evolve dratini

**Comment by marcosabruna** [comment]
Not sure why that is happening to you. My dratinis doesn't evolve and i have over 300 candie.

**Comment by Leigha888** [comment]
Marc can you show me the config so I can figure what is going on?

**Comment by Leigha888** [comment]
"KeepPokemonsThatCanEvolve": true,
  "EvolveAllPokemonWithEnoughCandy": true,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAboveIvValue": 95.0,
  "UseLuckyEggsWhileEvolving": true,
  "UseLuckyEggsMinPokemonAmount": 500,

"PokemonsToEvolve": [
    "zubat",
    "pidgey",
    "rattata",
    "caterpie",
    "weedle",
    "paras",
    "staryu",
    "oddish",
    "bellsprout",
    "venonat",
    "spearow",
    "clefairy",
    "sandshrew",
    "eevee",
    "jigglypuff",
    "rhyhorn",
    "meowth",
    "slowpoke",
    "ekans",
    "krabby",
    "drowzee",
    "horsea",
    "goldeen",
    "doduo",
    "diglett",
    "poliwag",
    "koffing",
    "gastly",
    "pikachu",
    "tentacool",
    "mankey",
    "cubone",
    "abra",
    "psyduck"
  ],

With this, it still evolved things not on that list to evolve

**Comment by Valmere** [comment]
"UseLuckyEggsMinPokemonAmount": 500

Unless you purchased inventory space you will never have that many pidgeys.
