### ISSUE TITLE
Transfering

### ISSUE THREAD

**Issue by Trollovenian** [PocketMobsters/PokeMobBot#45]
I have tried to edit Config left and right... PokemonsNotToTransfer, Individual PokemonsTransferFilter, KeepMinIvPercentage (97), KeepMinDuplicatePokemon (1), but still, I have alot of Electabuzz, Jynx, Magmar, Jolteon, Flareon, Exeggutor...

Meybe it has to do something with renaming ?

**Comment by klemax** [comment]
I also have a problem with pokemon filling up my space... My settings are:
"KeepMinCp": 1250,
  "KeepMinDuplicatePokemon": 1,
  "KeepMinIvPercentage": 90.0,
  "KeepPokemonsThatCanEvolve": false,
"TransferDuplicatePokemon": true

Yet I still get this message: "Pokemon Inventory is full! Please transfer Pokemon manually or set TransferDuplicatePokemon to true in settings..."

**Comment by klemax** [comment]
I also have the default "pokemon not to transfer" and "pokemon transfer filter" settings... Yet my space is filled up with all kinds of shitty pokemon

**Comment by ShakyDetox** [comment]
Transfering is not working correct, i have way to much pokemon have to transfer them by hand every 5-6hrs

**Comment by UntilSunrise** [comment]
config issue please read the wiki
