### ISSUE TITLE
Just have Normal Pokeballs

### ISSUE THREAD

**Issue by ShortPT** [PocketMobsters/PokeMobBot#451]
Why the bot just pick normal pokeballs? Don't stay with other types of pokeballs?

**Comment by littlemonster1** [comment]
usually depends on your settings, mine chooses the type or pokeball accordingly

**Comment by ShortPT** [comment]
Mine don't have this options! just "TotalAmountOfPokeballsToKeep"

**Comment by Valmere** [comment]
Ball configuration will be in the next release.
