### ISSUE TITLE
Norton 

### ISSUE THREAD

**Issue by mobotvirus** [PocketMobsters/PokeMobBot#452]
" SONAR.Heuristic.142 "RISK:HIGH" " Can anyone explain why norton deletes my exe file when I launch it?

**Comment by SonicPurge** [comment]
Norton bases some security decisions on how the "Norton community" rates the file. The more people that run it, the more "safe" it is. Since there aren't many people with Norton running the .EXE, it assumes it's a security risk and deletes it. You can restore it in your Norton settings.

**Comment by Jazed** [comment]
Feel free to look through the code, there is no viruses.
