### ISSUE TITLE
[Suggestion] Snipe specific pokemon rather than catch all at snipe location.

### ISSUE THREAD

**Issue by gnought** [PocketMobsters/PokeMobBot#456]
In PoGo.PokeMobBot.Logic/Tasks/SnipePokemonTask.cs

```
var catchablePokemon =
                mapObjects.MapCells.SelectMany(q => q.CatchablePokemons)
                    .Where(q => pokemonIds.Contains(q.PokemonId))
                    .ToList();
```

It seems that the sniping mode will catch all pokemons at the snipe location. Would it be configured to only snipe specific pokemon provided by a location feeder for saving poke balls?

**Comment by marcosabruna** [comment]
I think you can choose which pokemons to ignore. Search the config file.

**Comment by gnought** [comment]
Location feeder always report there is a named pokemon at a specific location, I think it is better to refine the ignore option from global scope to something more specific.

**Comment by torin555** [comment]
.Where(q => pokemonIds.Contains(q.PokemonId))
Means it searches for Pokemon with the IDs it's looking for.
