### ISSUE TITLE
The new version of the bot just transfered all my pokeballs.

### ISSUE THREAD

**Issue by WORMSS** [PocketMobsters/PokeMobBot#459]
```
[21:11:27] [Inventory] Pokeballs: 2 | Greatballs: 44 | Ultraballs: 76 | Masterballs: 0 
[21:11:27] [Inventory] Potions: 7 | Super Potions: 4 | Hyper Potions: 54 | Max Potions: 0 
[21:11:28] 1x ItemRazzBerry 
[21:11:32] 2x ItemPokeBall 
[21:11:38] 44x ItemGreatBall 
[21:11:44] 76x ItemUltraBall
```

The last 3 lines.. 

Is there some glitch in the upgrade to the latest version?

**Comment by Muffican** [comment]
your gonna wanna go down to your config file and then edit "TotalAmountOfPokeballsToKeep"

**Comment by WORMSS** [comment]
Yeah, seems my old config didn't have that option since I was upgrading an older version, and instead of using the default config value when it couldn't find it, it thought the best thing to do was to use 0.

I am manually going through the config now doing a like for like manually since I don't trust it anymore. Told it to never transfer any pokemon either due to another bug I seen here. Again, I don't trust the bot anymore.

**Comment by littlemonster1** [comment]
@WORMSS you should always manually go through your config after updating. You might not want certain default values ... such as in this case. While I agree, a default value of 0 is a little odd, it is hardly the bots fault that you did not check.
