### ISSUE TITLE
Error catching Pokemon when out of higher tier balls.

### ISSUE THREAD

**Issue by Nipper4369** [PocketMobsters/PokeMobBot#460]
When sniping or catching Pokemon it will not use a lower tier ball if it is out of the higher tier balls.

Example:
http://image.prntscr.com/image/1fef8918edbb4f3b818f51015529978e.png

Edit:
Using development as of comment https://github.com/PocketMobsters/PokeMobBot/commit/f894a31b6640906bc6db49b35449d3a72fe7ce83

**Comment by Sethenor** [comment]
Commit 69de16a works fine.
Commit 04cbbd1 breaks it.

**Comment by jjskuld** [comment]
+1 Ran into this bug too

**Comment by Nimryel** [comment]
Fixed it in #463
