### ISSUE TITLE
SkipLagged sniping is broken

### ISSUE THREAD

**Issue by georgi-huklev** [PocketMobsters/PokeMobBot#462]
Settings to reproduce:

  "SnipeAtPokestops": true,
  "UseSnipeLocationServer": false,
  "UsePokeSnipersLocationServer": false,

This should lead to the bot using skipplagged to look for *PokemonToSnipe.pokemon* in *PokemonToSnipe.locations* every *MinDelayBetweenSnipes* if you have at least *MinPokeballsToSnipe*.

What I keep getting is:

[22:13:35] (INFO) [Sniper] Scanning for Snipeable Pokemon at 35.6922104153639,139.694573879242...
[22:13:37] (ERROR) System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.PokeMobBot.Logic.Tasks.SnipePokemonTask.SnipeScanForPokemon(ISession session, Location location) in G:\GIT_Projects\PokeMobBot\PoGo.PokeMobBot.Logic\Tasks\SnipePokemonTask.cs:line 368

I sniffed the communication and the responses are coming in alright. The are quite big though and therefore chunked. Could that be the issue? People have complained here: http://stackoverflow.com/questions/16998/reading-chunked-response-with-httpwebresponse

EDIT: It is not response chunking. Did some tests with very small responses and still the same issue.

**Comment by Cappeen** [comment]
download this -->https://github.com/5andr0/PogoLocationFeeder/releases<-- and open it, while it's open, run PokeMobBot, Sniping should now work

**Comment by aapikz** [comment]
he's talking about manual sniping that use skippedlagged.com... not discord auto sniping... i have the same issue i hope this will fix soon...  necrobot is using the same code.. but somehow its working.. and yes im loving my 200kexp/h with pidgey,ratata sniping

**Comment by ShallowHacker** [comment]
Aapikz, How did you get Necro to work? Both give me the same error!

**Comment by aapikz** [comment]
from he latest clone from github.
