### ISSUE TITLE
antivirus positive

### ISSUE THREAD

**Issue by aeryl1999** [PocketMobsters/PokeMobBot#464]
PokeMobBot.exe keeps giving a positive result. The older builds even necrobot seems to be fine though.

**Comment by igromanru** [comment]
Crappy antivirus. No one of top AntiVIrus programs detect it as virus.
https://virustotal.com/en/file/665eed3f4a240a6b69148fc2230b4f7f5da8c4a81b6baafd0b7817c57c28677d/analysis/

**Comment by aeryl1999** [comment]
weird... im using the updated kaspersky and sysmatec on two devices but on virustotal it says clean which is contrasting to my results.

**Comment by igromanru** [comment]
Sure that you got legal copy of kaspersky?

**Comment by Zerofy** [comment]
https://virustotal.com/en/file/9898b53a58825275be267dfd3adb5b8dd4c435aa8a171f11b7813864b8631ae2/analysis/1470171800/

**Comment by aeryl1999** [comment]
kaspersky quarantines it immediately, but im more concerned to sysmantec as its company grade. I'd rather use the old build that was clean.
