### ISSUE TITLE
[question]PokeMobBot compatible NecroBot?

### ISSUE THREAD

**Issue by adamgyongyosi** [PocketMobsters/PokeMobBot#466]
PokeMobBot compatible NecroBot?

**Comment by igromanru** [comment]
I don't understand the question.

**Comment by adamgyongyosi** [comment]
NecroBot config file compatible  PokeMobBot
and
PokeMobBot config file compatible  NecroBot

**Comment by igromanru** [comment]
I don't think so.

**Comment by adamgyongyosi** [comment]
because I tried to use UseSnipeOnlineLocationServer and not working thx for info
