### ISSUE TITLE
i need full pokemon list?

### ISSUE THREAD

**Issue by vampirictorch** [PocketMobsters/PokeMobBot#472]
hello, I know the pokemon but for example Mr Mime, it does mrMime (case sense with no space) and there are a lot of other pokemon when I try an add into my list ignore or otherwise, it crashes the bot because it will not reconize the pokemon name, could I get an exact list of how they are spelled on the bot for the Pokemon? thanks it is not on the wiki...

**Comment by forReason** [comment]
"venusaur",
      "charizard",
      "blastoise",
      "beedrill",
      "raichu",
      "sandslash",
      "nidoking",
      "nidoqueen",
      "clefable",
      "ninetales",
      "golbat",
      "vileplume",
      "golduck",
      "primeape",
      "arcanine",
      "poliwrath",
      "alakazam",
      "machamp",
      "golem",
      "rapidash",
      "slowbro",
      "farfetchd",
      "muk",
      "cloyster",
      "gengar",
      "exeggutor",
      "marowak",
      "hitmonchan",
      "lickitung",
      "rhydon",
      "chansey",
      "kangaskhan",
      "starmie",
      "mrMime",
      "scyther",
      "magmar",
      "electabuzz",
      "magmar",
      "jynx",
      "gyarados",
      "lapras",
      "ditto",
      "vaporeon",
      "jolteon",
      "flareon",
      "porygon",
      "kabutops",
      "aerodactyl",
      "snorlax",
      "articuno",
      "zapdos",
      "moltres",
      "dragonite",
      "mewtwo",
      "mew"

**Comment by forReason** [comment]
i guess mr.mime is the only one i dont have in

**Comment by vampirictorch** [comment]
thanks! it was my nideran that was messing it up lol... and a few others, thanks works like a charm, essentially disabling everything accept pokestops for my wife, she wants to not have to pay for pokeballs she spent like 40$ on them lol, I for one want to cheat to the next level muhahahahaha lol, thanks again helps set up one for my wife to use haha
