### ISSUE TITLE
It wont login in with my google account!?

### ISSUE THREAD

**Issue by steamlab13** [PocketMobsters/PokeMobBot#477]
It wont login in with my google account!!!
![screenshot_1](https://cloud.githubusercontent.com/assets/20803983/17347813/e32bd272-591a-11e6-9e4d-d4e7dc0bb3d5.png)        
![screenshot_2](https://cloud.githubusercontent.com/assets/20803983/17347822/f092a576-591a-11e6-99dc-f165116eff90.png)

**Comment by steamlab13** [comment]
Sorry for bad English!!

**Comment by steamlab13** [comment]
and yeah is this normal??
![screenshot_3](https://cloud.githubusercontent.com/assets/20803983/17348010/3f44cb9e-591c-11e6-8c10-cf4243a4d335.png)

**Comment by silenthunter93** [comment]
Mine is set to: "GoogleRefreshToken": null,

**Comment by steamlab13** [comment]
@silenthunter93 no its same not working! :(
