### ISSUE TITLE
Error (See image)

### ISSUE THREAD

**Issue by jimconnor** [PocketMobsters/PokeMobBot#479]
I regularly get an error but the bot logs me back in and continues running without any action required.
![bot issue](https://cloud.githubusercontent.com/assets/20804142/17347894/ad828114-58e0-11e6-82b7-a5254499b753.jpg)

What other information would you like (I just downloaded the latest update an hour ago)?

**Comment by Zerstoren** [comment]
At 5 minutes catch current error. Previous 3 hours all work fine.
What happens?

**Comment by jimconnor** [comment]
I don't think I understand the question. Nothing out of the ordinary happened prior to the error. I was not even touching the computer.

**Comment by jimconnor** [comment]
Something about the error made me think of a location issue. I've changed it and have not gotten the error in awhile.

**Comment by R0DaV-D0rIaN** [comment]
It is a human error. When you look up the coordinates, sometimes it tells you the longitude incorrectly. Try going to Google, and looking up the exact coordinates that you put in. If it is not the location that you intended, then make the longitude negative.
