### ISSUE TITLE
Issue with sniping and loss of network.

### ISSUE THREAD

**Issue by Nipper4369** [PocketMobsters/PokeMobBot#481]
If your network hickups or disconencts while a snipe is happens. It will keep you at the snipe coords and spam out of range of target location. 

I only notice this when my network via wireless drops once in a while and if it is during a snipe it will keep me there and spam the message about being out of bounds. Maybe add a teleport when it detects it is out of bounds.

**Comment by Earisu** [comment]
This also happens when there are connection issues with niantic servers and you are sniping.

**Comment by tangdami** [comment]
yes, actually the bot should detect that it is far away from the original point, like 1000 km, then teleport back to the start point.

**Comment by Nipper4369** [comment]
It should yes. But it don't
