### ISSUE TITLE
UseSnipeOnlineLocationServer 

### ISSUE THREAD

**Issue by Zeroema** [PocketMobsters/PokeMobBot#484]
Setting UseSnipeOnlineLocationServer to true will setup automatic sniping with PokeSniper.com. Where i can find that option? I can´t see it in the config.json

**Comment by jinkawasaki333** [comment]
@Zeroema Have you downloaded the latest release? It's inside the config.

**Comment by Zeroema** [comment]
Yes, version v1.1.3

**Comment by torin555** [comment]
It's "UsePokeSnipersLocationServer". The changelog was a typo.

**Comment by jjskuld** [comment]
AFAIK it's not working.  PokeSnipes has DDOS protection enabled, which causes the request to the  API server to be rejected.  The web client needs to be redone to bypass the DDOS protection.

**Comment by Valmere** [comment]
Closing as it's not explicitly a bot issue and support for sniping is currently limited. Try our forums once they're up
