### ISSUE TITLE
keeping a lot of pokeballs only ...

### ISSUE THREAD

**Issue by jawad90** [PocketMobsters/PokeMobBot#490]
i found that the bot is keeping a lot of pokeballs instead of the great or ultra ones which im in such a need because of my high level 

it would be great if we have a feature to specify the amount we want for each type of balls 

i think i can help with the coding i just dont know how or what to do

**Comment by littlemonster1** [comment]
are you running the release or the dev version? release works fine for me, almost down to 0 Pokeballs, 150 great balls and 60 ultra balls

**Comment by Tytn** [comment]
Release seems to be working great for me as well. My inventory atm is 7PBs, 144GBs and 77 UBs.

**Comment by jawad90** [comment]
yes im using the release .....thats weird and it says inventory is full even after lowering how much potions to keep

**Comment by jawad90** [comment]
i just checked the game (without bot) and found only 3 pokeballs and 222 razzberries which we dont have an option to reduce the amount of it in CONFIG file and for the potions its normal

**Comment by Tytn** [comment]
You have an option to reduce the razzberries amount.

>   "TotalAmountOfPokeballsToKeep": 230,
  "TotalAmountOfPotionsToKeep": 30,
  "TotalAmountOfRevivesToKeep": 20,
  "TotalAmountOfBerriesToKeep": 50,
  "RecycleInventoryAtUsagePercentage": 0.96,

Those are my settings, working well, but you can obviously lower the Pokeballs amount. Anyway, as you can see, "TotalAmountOfBerriesToKeep" controls the razz amount.

Probably why it was having issues in the first place.

**Comment by jawad90** [comment]
i hope this helps 
`public ICollection<KeyValuePair<ItemId, int>> ItemRecycleFilter => new[]`
        { 
`            new KeyValuePair<ItemId, int>(ItemId.ItemPokeBall, 20),`
`            new KeyValuePair<ItemId, int>(ItemId.ItemGreatBall, 20),
`
`            new KeyValuePair<ItemId, int>(ItemId.ItemUltraBall, 50),
`
`            new KeyValuePair<ItemId, int>(ItemId.ItemMasterBall, 100),`
`            new KeyValuePair<ItemId, int>(ItemId.ItemPotion, 0),
`
`            new KeyValuePair<ItemId, int>(ItemId.ItemSuperPotion, 0),`
`            new KeyValuePair<ItemId, int>(ItemId.ItemHyperPotion, 20),`

`            new KeyValuePair<ItemId, int>(ItemId.ItemMaxPotion, 50),`
`            new KeyValuePair<ItemId, int>(ItemId.ItemRevive, 10),`
`            new KeyValuePair<ItemId, int>(ItemId.ItemMaxRevive, 50)
`};

**Comment by jawad90** [comment]
@Tytn lol i dont have that .... but why ? i have autoupdate set to ON

**Comment by Tytn** [comment]
Your config is a lot different than mine, probably an older release (I've no clue how the config looked like before, I've started using this yesterday). Try downloading the latest release, maybe the auto-updater isn't working and you still have an older release.

**Comment by KidLoad93** [comment]
"UseGreatBallAboveIv": 80,
  "UseUltraBallAboveIv": 100,
  "UseGreatBallBelowCatchProbability": 0.3,
  "UseUltraBallBelowCatchProbability": 0.15,
  "UseMasterBallBelowCatchProbability": 0.05,
this maybe can help.this save my greatball and ultraball

**Comment by chopraaa** [comment]
@jawad90 Delete `config.json` and restart the bot.

**Comment by Valmere** [comment]
Item configuration is implemented in the next release.
