### ISSUE TITLE
Its keeping pokemon under Iv's

### ISSUE THREAD

**Issue by lilaznkid916** [PocketMobsters/PokeMobBot#491]
Its keeping pokemon like Vaporeon/Dragonite/Snorlax/Lapras with iv's around 60%. Yet i made sure my configs say to release pokemon under 95% iv's

**Comment by torin555** [comment]
some pokemon have settings that override the default setting. Scroll down in your config.

**Comment by lilaznkid916** [comment]
Are you talking about this?
    "Dragonite": {
      "KeepMinCp": 1800,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Vaporeon": {
      "KeepMinCp": 1800,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1

If it is, what should be changed?

**Comment by littlemonster1** [comment]
what version are you running (release/dev) and what are your config settings?

**Comment by torin555** [comment]
Yes that's what I'm talking about. Is their CP above 1800?

**Comment by lilaznkid916** [comment]
Im running release. Don't know how to run the dev one.

Heres my config settings. http://pastebin.com/8jFeq9Qr

**Comment by lilaznkid916** [comment]
No, thats the thing, their CP are below that, yet it doesnt transfer them

**Comment by torin555** [comment]
Found your problem:
"PokemonsNotToTransfer": [
    "charizard",
    "blastoise",
    "ditto",
    "articuno",
    "zapdos",
    "moltres",
    "mewtwo",
    "mew",
    "dragonite",
    "snorlax",
    "vaporeon",
    "arcanine",
    "lapras",
    "gyarados",
    "slowbro",
    "vileplume",
    "victreebel",
    "poliwrath",
    "exeggutor",
    "flareon",
    "muk",
    "machamp",
    "nidoking",
    "nidoqueen",
    "golduck",
    "golem",
    "gengar",
    "rhydon",
    "omastar"
  ],

**Comment by lilaznkid916** [comment]
Oh, what should it be?

**Comment by torin555** [comment]
"Pokemon Not To Transfer" means it doesn't transfer those Pokemon.

**Comment by lilaznkid916** [comment]
But wouldnt pokemon not under that list be transfered? If i have a 100% gyrados, wouldnt it transfer that?

**Comment by littlemonster1** [comment]
no,pokemon on that list will never be transferred. If they are not on that list they are transferred according to the filters you chose.

**Comment by Tytn** [comment]
As long as you have "KeepMinDuplicatePokemon": 1 and "PrioritizeIvOverCp": true, it will always keep your best Pokemon IV wise, ignoring whatever the CP of the duplicates might be.

However, it will never transfer any Pokemon that goes over "KeepMinCp": 2200 OR  "KeepMinIvPercentage": 95.0 that you've set.

**Comment by lilaznkid916** [comment]
Oh okay, i get what you guys are saying. Thanks for the help :)

**Comment by botter112** [comment]
i have "same" problem but i have "Pokemon Not To Transfer"  clear (only with pokemon can catch actually like mew etc) , i have this problem with a lot pokemons ( i have it all on  "PokemonsTransferFilter")
  "Snorlax": {
      "KeepMinCp": 2000,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 4
    },
But i keep catching with less than CP and IV... http://imgur.com/a/C55K6

i have too but 
 "KeepMinCp": 2000,
 "KeepMinIvPercentage": 95.0,

**Comment by torin555** [comment]
Wow you've got every pokemon in the game with custom transfer filters... I'm not sure what the issue would be, is it transferring other pokemon besides the snorlax?

**Comment by botter112** [comment]
I have this problem with a few pokemons  , i have my pokemon bag full ;(

**Comment by Valmere** [comment]
Transferring will be fixed in the next release.
