### ISSUE TITLE
Does the bot farm if out of pokeballs ??

### ISSUE THREAD

**Issue by jawad90** [PocketMobsters/PokeMobBot#495]
he keeps trying to catch pokemons with regular pokeballs..... and thats a problem because you cant catch any of them if they are high cp or iv

**Comment by Tytn** [comment]
>   "HumanizeThrows": true,
  "ThrowAccuracyMin": 0.7,
  "ThrowAccuracyMax": 1.0,
  "ThrowSpinFrequency": 0.75,
  "MaxPokeballsPerPokemon": 10,
  "UseGreatBallAboveIv": 80,
  "UseUltraBallAboveIv": 90,
  "UseGreatBallBelowCatchProbability": 0.4,
  "UseUltraBallBelowCatchProbability": 0.25,
  "UseMasterBallBelowCatchProbability": 0.05,
  "UsePokemonToNotCatchFilter": false,
  "UseBerryMinCp": 200,
  "UseBerryMinIv": 90.0,
  "UseBerryBelowCatchProbability": 0.2,

All of those lines are relative to the Pokeball throwing, adjust them to your liking. Or use mine if you want, they have been working fine for me.

**Comment by torin555** [comment]
I suggest setting your max pokeballs per pokemon to be higher if you aren't catching things with normal pokeballs. Tytn's 10 would probably be enough. Personally I use 30. My logic is that if it's that hard to catch then it's probably worth the pokeballs.

**Comment by Valmere** [comment]
Open an new issue if this persists after the next release.
