### ISSUE TITLE
Pokemon with the same IV transfering seemingly "randomly"

### ISSUE THREAD

**Issue by Tytn** [PocketMobsters/PokeMobBot#496]
So I just noticed this:

> [04:XX:XX] Bellsprout	- CP: 210  IV: 84.98%   [Best CP: 80  IV: 84.98%]

It transfered a 210CP Poké over a 80 one with the same IV percentage. Not a big deal on my case, but it might happen with better Poké as well, as long as it's not overwriten by the "Do not transfer" filters.

**Comment by bmdr38** [comment]
See #513 for proposed fix

**Comment by Tytn** [comment]
Great to see a fix is on the way! Thanks.

**Comment by Valmere** [comment]
Closing as the fix was merged, if the problem persists after the next release open another issue.
