### ISSUE TITLE
Issue in translation.es.json

### ISSUE THREAD

**Issue by genius394** [PocketMobsters/PokeMobBot#50]
The Key "eventFortUsed" don't show the objects, you need to change like this:
"Key": "eventFortUsed",
      "Value": "{0} - PX: {1}, Gemas: {2}, Objetos: {3}"

**Comment by AlessioDP** [comment]
Like that: https://github.com/PocketMobsters/PokeMobBot/pull/57

**Comment by DurtyFree** [comment]
Fixed.
