### ISSUE TITLE
how to add nidoran to "PokemonsToEvolve" field

### ISSUE THREAD

**Issue by KidLoad93** [PocketMobsters/PokeMobBot#500]
i want to add nidoran to "PokemonsToEvolve" field cuz of i have lot of nidoran candy.but when i put nidoran to that the program cannot start cuz of there are 2 kind of nidoran and they have a unicode character after the name.please tell me how.thanks in advance.

**Comment by torin555** [comment]
I believe in more recent commits Nidoran has been modified to use F and M instead of the unicode symbols. But have you tried finding the unicode signs somewhere and pasting them in?

**Comment by KidLoad93** [comment]
i try to put unicode character inside and failed.is "nidoranf" and "nidoranm" work?

**Comment by bmdr38** [comment]
"nidoranmale" and "nidoranfemale" should be enough.

From POGOProtos.Enums:
NidoranFemale = 29,
...
NidoranMale = 32,

**Comment by KidLoad93** [comment]
its work,thanks so much.
