### ISSUE TITLE
[Request] Don't Rename Favorited Pokemon Option

### ISSUE THREAD

**Issue by torin555** [PocketMobsters/PokeMobBot#501]
Can there be an option added to the automatic renaming system to not rename favorited Pokemon? That way we can set nicknames for our perfect Pokemon and still use the automatic renaming system for the rest.

**Comment by codefanatic** [comment]
`// If "RenameOnlyAboveIv" = true only rename pokemon with IV over "KeepMinIvPercentage"
                // Favorites will be skipped
                if ((!session.LogicSettings.RenameOnlyAboveIv || perfection >= session.LogicSettings.KeepMinIvPercentage) &&
                    newNickname != oldNickname && pokemon.Favorite == 0)
                {
                    await session.Client.Inventory.NicknamePokemon(pokemon.Id, newNickname);

                    session.EventDispatcher.Send(new NoticeEvent
                    {
                        Message =
                            session.Translation.GetTranslation(TranslationString.PokemonRename, session.Translation.GetPokemonName(pokemon.PokemonId),
                                pokemon.Id, oldNickname, newNickname)
                    });
                }`

This is already a feature?

**Comment by torin555** [comment]
You're right it is, didn't even notice.
