### ISSUE TITLE
Sniper gives Error instead of using lesser balls for attempts.

### ISSUE THREAD

**Issue by bspencer79** [PocketMobsters/PokeMobBot#505]
When the bot snipes and your settings tell it to use an ultra ball and you dont have any it gives and error.
Prolly should be a way for it to use great balls and then poke balls until u hit ur max pokeballs for each pokemon???

**Comment by torin555** [comment]
What's the error? The bot normally does exactly what you described.

**Comment by bspencer79** [comment]
well before the bot would use great balls if it was out of ultra balls and also poke balls if it was out of the other 2 

    On Wednesday, August 3, 2016 2:05 AM, torin555 <notifications@github.com> wrote:
 

 What's the error? The bot normally does exactly what you described.—

**Comment by torin555** [comment]
Right... So what is it doing for you now?

**Comment by bspencer79** [comment]
ok lets say the sniper picks up a Snorlax that is 2400cp and my config says to use a berry and an ultra ball to catch it.
it uses the berry and if i do not have any ultra balls it gives an error and does not try to catch it with great balls. 

    On Wednesday, August 3, 2016 2:46 AM, torin555 <notifications@github.com> wrote:
 

 Right... So what is it doing for you now?—

**Comment by torin555** [comment]
"What's the error?"

**Comment by bspencer79** [comment]
[Sniper] Sniping a Dragonite with unknown IV at 49.2793782254624,-122.915438871871...[23:05:53] Using Razzberry. Berries left: 6[23:05:54] (Error) | Dragonite, Lvl: 23 | CP: (2220/2300) | IV: 71.90% | Type: Normal | Chance: 3.12% | Dist: 3497640.35m | Used: UltraBall (0 left) | XP: 0 |     On Wednesday, August 3, 2016 3:01 AM, torin555 <notifications@github.com> wrote:
 

 "What's the error?"—

**Comment by jjskuld** [comment]
The error is that the current behavior is wrong - it should try using a great ball instead of doing nothing at all.

**Comment by Valmere** [comment]
#507 should fix this issue, marking as bug for reference and closing.
