### ISSUE TITLE
Sniping Pokeball Logic

### ISSUE THREAD

**Issue by Kosmatik** [PocketMobsters/PokeMobBot#520]
The pokeball sniping logic is fubar in the lastest development build, when there's 1 or 0 itemPokeBall left, but 20> itemGreatBall, the bot still thinks there's "No Pokeballs - We missed a <name> with CP <num>" even though the min pokeball snipe number is 20 and I have well more then 20 great balls.

**Comment by jjskuld** [comment]
This issue is also resolved by Pull #507.

**Comment by Kosmatik** [comment]
Can we get the IV displayed also and not just the CP on the skipped pokemon ala "No Pokeballs - We missed a somename with CP number and IV number"?

**Comment by Valmere** [comment]
#507 was merged and will be in the next release, closing issue.
