### ISSUE TITLE
When discarding potions and revives, use them to heal pokemon instead if possible

### ISSUE THREAD

**Issue by DIolo** [PocketMobsters/PokeMobBot#525]
As it says in the title.  As my pokemon slowly return to me after getting beaten up in gyms, it'd be great if all those potions I'm discarding could be put to work instead.

**Comment by vison99** [comment]
seriously how long would it take for you to use potions yourself if you had the time to beat the gym?

**Comment by DIolo** [comment]
Even with teleport and 0 wait configs, I don't build my supply of max and hyper potions as quickly as I'd like to keep up with my gym crashing.  So I'd love for it to use all the regular and super potions that it's dumping, which do require a pretty fair amount of clicks and time as a human.

**Comment by chopraaa** [comment]
Why even play the game?

**Comment by DIolo** [comment]
I like gym wars throughout the day.  In a big city it's a good back and forth. The less time I need to spend on maintenance, the better.

**Comment by Valmere** [comment]
Gym battling and related features will not be implemented.
