### ISSUE TITLE
Suddendly stop sniping after a while

### ISSUE THREAD

**Issue by Kraker01** [PocketMobsters/PokeMobBot#526]
Hi,

I have configured my BOT just to snipe (setting in "Ignore" every pokemon).

When I start the bot, it try to snipe and catch something but, after a while, he suddendly stops and he just walk  towards pokestops. How can I fix this?

I'm using latest MobBot and latest GUI PogoFeeder

**Comment by chopraaa** [comment]
@Kraker01 There's no setting to ignore every Pokemon...right?

**Comment by Kraker01** [comment]
Yes, there is.  This is mine config.json:

`{
  "AutoUpdate": false,
  "TransferConfigAndAuthOnUpdate": true,
  "DumpPokemonStats": false,
  "AmountOfPokemonToDisplayOnStart": 0,
  "StartupWelcomeDelay": false,
  "TranslationLanguageCode": "en",
  "WebSocketPort": 14251,
  "Teleport": false,
  "DefaultLatitude": 44.059264,
  "DefaultLongitude": 12.568515,
  "DefaultAltitude": 10.0,
  "WalkingSpeedInKilometerPerHour": 300.0,
  "MaxSpawnLocationOffset": 10,
  "MaxTravelDistanceInMeters": 1000,
  "UseGpxPathing": false,
  "GpxFile": "GPXPath.GPX",
  "DelayBetweenPlayerActions": 300,
  "DelayPositionCheckState": 300,
  "DelayPokestop": 300,
  "DelayCatchPokemon": 300,
  "DelayBetweenPokemonCatch": 0,
  "DelayCatchNearbyPokemon": 300,
  "DelayCatchLurePokemon": 300,
  "DelayCatchIncensePokemon": 300,
  "DelayEvolvePokemon": 300,
  "DelayEvolveVariation": 0.3,
  "DelayTransferPokemon": 1000,
  "DelayDisplayPokemon": 1000,
  "DelayUseLuckyEgg": 1000,
  "DelaySoftbanRetry": 1000,
  "DelayRecyleItem": 1000,
  "DelaySnipePokemon": 1000,
  "MinDelayBetweenSnipes": 0,
  "SnipingScanOffset": 0.003,
  "UseEggIncubators": true,
  "RenamePokemon": true,
  "RenameOnlyAboveIv": false,
  "RenameTemplate": "{1}_{0}",
  "TransferDuplicatePokemon": true,
  "PrioritizeIvOverCp": true,
  "KeepMinCp": 1250,
  "KeepMinIvPercentage": 95.0,
  "KeepMinDuplicatePokemon": 1,
  "KeepPokemonsThatCanEvolve": false,
  "EvolveAllPokemonWithEnoughCandy": false,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAboveIvValue": 95.0,
  "UseLuckyEggsWhileEvolving": false,
  "UseLuckyEggsMinPokemonAmount": 30,
  "AutomaticallyLevelUpPokemon": false,
  "LevelUpByCPorIv": "iv",
  "UpgradePokemonCpMinimum": 1000.0,
  "UpgradePokemonIvMinimum": 95.0,
  "HumanizeThrows": false,
  "ThrowAccuracyMin": 0.5,
  "ThrowAccuracyMax": 1.0,
  "ThrowSpinFrequency": 0.75,
  "MaxPokeballsPerPokemon": 6,
  "UseGreatBallAboveIv": 80,
  "UseUltraBallAboveIv": 90,
  "UseGreatBallBelowCatchProbability": 0.5,
  "UseUltraBallBelowCatchProbability": 0.25,
  "UseMasterBallBelowCatchProbability": 0.05,
  "UsePokemonToNotCatchFilter": true,
  "UseBerryMinCp": 450,
  "UseBerryMinIv": 95.0,
  "UseBerryBelowCatchProbability": 0.2,
  "AutoFavoritePokemon": false,
  "FavoriteMinIvPercentage": 95.0,
  "TotalAmountOfPokeballsToKeep": 120,
  "TotalAmountOfPotionsToKeep": 40,
  "TotalAmountOfRevivesToKeep": 30,
  "TotalAmountOfBerriesToKeep": 80,
  "RecycleInventoryAtUsagePercentage": 0.9,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": true,
  "UseTransferIvForSnipe": false,
  "MinPokeballsToSnipe": 0,
  "MinPokeballsWhileSnipe": 0,
  "UseSnipeLocationServer": true,
  "UsePokeSnipersLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "SnipeRequestTimeoutSeconds": 5,
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    }
  ],
  "PokemonsNotToTransfer": [
    "ditto",
    "articuno",
    "zapdos",
    "moltres",
    "mewtwo",
    "mew"
  ],
  "PokemonsToEvolve": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata",
    "spearow",
    "zubat",
    "doduo"
  ],
  "PokemonsToIgnore": [
    "bulbasaur",
    "ivysaur",
    "venusaur",
    "charmander",
    "charmeleon",
    "charizard",
    "squirtle",
    "wartortle",
    "blastoise",
    "caterpie",
    "metapod",
    "butterfree",
    "weedle",
    "kakuna",
    "beedrill",
    "pidgey",
    "pidgeotto",
    "pidgeot",
    "rattata",
    "raticate",
    "spearow",
    "fearow",
    "ekans",
    "arbok",
    "pikachu",
    "raichu",
    "sandshrew",
    "sandslash",
    "nidorina",
    "nidoranFemale",
    "nidoranMale",
    "nidoqueen",
    "nidorino",
    "nidoking",
    "clefairy",
    "clefable",
    "vulpix",
    "ninetales",
    "jigglypuff",
    "wigglytuff",
    "zubat",
    "golbat",
    "oddish",
    "gloom",
    "vileplume",
    "paras",
    "parasect",
    "venonat",
    "venomoth",
    "diglett",
    "dugtrio",
    "meowth",
    "persian",
    "psyduck",
    "golduck",
    "mankey",
    "primeape",
    "growlithe",
    "arcanine",
    "poliwag",
    "poliwhirl",
    "poliwrath",
    "abra",
    "kadabra",
    "alakazam",
    "machop",
    "machoke",
    "machamp",
    "bellsprout",
    "weepinbell",
    "victreebel",
    "tentacool",
    "tentacruel",
    "geodude",
    "graveler",
    "golem",
    "ponyta",
    "rapidash",
    "slowpoke",
    "slowbro",
    "magnemite",
    "magneton",
    "doduo",
    "dodrio",
    "seel",
    "dewgong",
    "grimer",
    "muk",
    "shellder",
    "cloyster",
    "gastly",
    "haunter",
    "gengar",
    "onix",
    "drowzee",
    "hypno",
    "krabby",
    "kingler",
    "voltorb",
    "electrode",
    "exeggcute",
    "exeggutor",
    "cubone",
    "marowak",
    "hitmonlee",
    "hitmonchan",
    "lickitung",
    "koffing",
    "weezing",
    "rhyhorn",
    "rhydon",
    "chansey",
    "tangela",
    "kangaskhan",
    "horsea",
    "seadra",
    "goldeen",
    "seaking",
    "staryu",
    "starmie",
    "scyther",
    "jynx",
    "electabuzz",
    "magmar",
    "pinsir",
    "tauros",
    "magikarp",
    "gyarados",
    "lapras",
    "ditto",
    "eevee",
    "vaporeon",
    "jolteon",
    "flareon",
    "porygon",
    "omanyte",
    "omastar",
    "kabuto",
    "kabutops",
    "aerodactyl",
    "snorlax",
    "articuno",
    "zapdos",
    "moltres",
    "dratini",
    "dragonair",
    "dragonite",
    "mewtwo",
    "mew"
  ],
  "PokemonsTransferFilter": {
    "Venusaur": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 40.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Charizard": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 20.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Blastoise": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 20.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Nidoqueen": {
      "KeepMinCp": 1750,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Nidoking": {
      "KeepMinCp": 1750,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Clefable": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 60.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Vileplume": {
      "KeepMinCp": 1750,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Golduck": {
      "KeepMinCp": 1750,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Arcanine": {
      "KeepMinCp": 2000,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Poliwrath": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Machamp": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Victreebel": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 60.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Golem": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Slowbro": {
      "KeepMinCp": 1750,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Farfetchd": {
      "KeepMinCp": 1000,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Muk": {
      "KeepMinCp": 2000,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Exeggutor": {
      "KeepMinCp": 2250,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Lickitung": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Chansey": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Kangaskhan": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 60.0,
      "KeepMinDuplicatePokemon": 1
    },
    "MrMime": {
      "KeepMinCp": 250,
      "KeepMinIvPercentage": 40.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Scyther": {
      "KeepMinCp": 1750,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Jynx": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Electabuzz": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Magmar": {
      "KeepMinCp": 1750,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Pinsir": {
      "KeepMinCp": 1750,
      "KeepMinIvPercentage": 98.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Tauros": {
      "KeepMinCp": 500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Gyarados": {
      "KeepMinCp": 1750,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Lapras": {
      "KeepMinCp": 2000,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Eevee": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 98.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Vaporeon": {
      "KeepMinCp": 2000,
      "KeepMinIvPercentage": 98.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Jolteon": {
      "KeepMinCp": 2000,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Flareon": {
      "KeepMinCp": 2000,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Porygon": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Aerodactyl": {
      "KeepMinCp": 1750,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Snorlax": {
      "KeepMinCp": 2500,
      "KeepMinIvPercentage": 96.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Dragonite": {
      "KeepMinCp": 2500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    }
  },
  "PokemonToSnipe": {
    "Locations": [
      {
        "Latitude": 38.556807486461118,
        "Longitude": -121.2383794784546
      },
      {
        "Latitude": -33.859019,
        "Longitude": 151.213098
      },
      {
        "Latitude": 47.5014969,
        "Longitude": -122.0959568
      },
      {
        "Latitude": 51.5025343,
        "Longitude": -0.2055027
      }
    ],
    "Pokemon": [
      "venusaur",
      "charizard",
      "blastoise",
      "beedrill",
      "raichu",
      "sandslash",
      "nidoking",
      "nidoqueen",
      "clefable",
      "ninetales",
      "golbat",
      "vileplume",
      "golduck",
      "primeape",
      "arcanine",
      "poliwrath",
      "alakazam",
      "machamp",
      "golem",
      "rapidash",
      "slowbro",
      "farfetchd",
      "muk",
      "cloyster",
      "gengar",
      "exeggutor",
      "marowak",
      "hitmonchan",
      "lickitung",
      "rhydon",
      "chansey",
      "kangaskhan",
      "starmie",
      "mrMime",
      "scyther",
      "magmar",
      "electabuzz",
      "magmar",
      "jynx",
      "gyarados",
      "lapras",
      "ditto",
      "vaporeon",
      "jolteon",
      "flareon",
      "porygon",
      "kabutops",
      "aerodactyl",
      "snorlax",
      "articuno",
      "zapdos",
      "moltres",
      "dragonite",
      "mewtwo",
      "mew"
    ]
  },
  "PokemonToUseMasterball": [
    "articuno",
    "zapdos",
    "moltres",
    "mew",
    "mewtwo"
  ]
}`

**Comment by Kraker01** [comment]
Updated POGO Feeder to latest (0.1.3) but MobBot still stops sniping pokemon

I have to kill all the processes and restart again, then he starts sniping again.

**Comment by jjskuld** [comment]
Pogofeeder also has the issue where a lot of the pokemon do not have an expiration time set.  So PokeMobBot will miss a lot of pokemon.  In my own personal build, I have disabled the expiration time check in order to get more pokemon.  Once I have time, will make a pull request and make the ability to disable expiration time check configurable.

**Comment by Valmere** [comment]
This isn't explicitly a bot issue and support for using feeders right now is limited. Our forums will be up soon, if your problem persists after the bot has been updated post there.
