### ISSUE TITLE
Bot won't return after Pokeballs = 0 and refuse to use other balls

### ISSUE THREAD

**Issue by TehChozinOne** [PocketMobsters/PokeMobBot#529]
I'm using source version dev branch with commits 390
"MinPokeballsWhileSnipe": 0,
"Sniping on skiplagged"

I dont have any pokeballs left but I still have some of Great and Ultra Balls left in the bag but bot refuse to use them 

Bot also throw error "Skiping xxx no pokeballs left" and won't return to default location

**Comment by littlemonster1** [comment]
#463

**Comment by solenrus** [comment]
same issue

**Comment by real8787** [comment]
Same for me, hoping for quick fix.

**Comment by jjskuld** [comment]
I think Pull #507 will fix this issue as well.

**Comment by Valmere** [comment]
Fix was merged and will be in next release, closing.
