### ISSUE TITLE
Bot is misusing Great and Ultra Balls

### ISSUE THREAD

**Issue by Rommedazzle** [PocketMobsters/PokeMobBot#530]
I've changed the config to:
Catch prob. for Great/Ultra at 20/10 %
Use Great/ultra at IV 80/90.

But the bot is still throwing Ultras and Greats on Rattata, Pidgey and so on.

What gives?

**Comment by Nimryel** [comment]
Fixed in #463

**Comment by Rommedazzle** [comment]
Which is the new update? 
Does the program update on its own, or do I download the new version in that case?

**Comment by littlemonster1** [comment]
new release not out yet, Nimryel's PR is not merged yet. If you want to use it pull dev version and nimryels PR.

**Comment by Valmere** [comment]
Closing, issue fixed in next release.
