### ISSUE TITLE
1.1.3 recycle logic still has problem

### ISSUE THREAD

**Issue by vfuyong** [PocketMobsters/PokeMobBot#531]
When using "RecycleInventoryAtUsagePercentage": 0.9, I realized the recycle works when I have fewer inventory items. But when I have more, the recycle never occurs.

I believe the logic to trigger recycle may not happen under some common situation. Please investigate. 

I will propose the following logic:

let n be the number of pokeshops visited
when visited a pokeshop, n = n + 1
when n = 20 (or any other number), trigger a recycle event. Then set n = 0.

Using the above logic, the parameter "RecycleInventoryAtUsagePercentage" can be removed and the logic has no chance to go wrong because only visiting a shop has chance to overflow the inventory.

**Comment by vfuyong** [comment]
In addition, I set to keep 30 berries. When my berry is 40, it does not recycle 10. Instead, it recycles 30? What kind of logic is this?

**Comment by littlemonster1** [comment]
please search the issues first. this is long known and has been reported multiple times. should be fixed in next release. # of pokestops still works for me here (has been the logic so far anyways ...)

**Comment by Valmere** [comment]
Item configuration will be in the next release.
