### ISSUE TITLE
Lucky Egg

### ISSUE THREAD

**Issue by giacomofabbri** [PocketMobsters/PokeMobBot#534]
Hi! That's not a problem, I guess, but I'd like to know how does it work the use of the Lucky Egg during the evolution, I setup to use it and also setup 42 pokemon to evolve, will it do everything by itself or what? Do I need to activate the lucky egg and then I will do it by itself or what??
Thanks for the help
P.S. I tried to use the Discord chat both #helpme and #settings but no one answered me, sorry for the inconvenience!!

**Comment by Tytn** [comment]
Afaik, once you reach the 42 Pokemon that you have candies to evolve mark, it will pop the lucky egg itself and evolve them. I haven't tried the evolution settings yet, so I'm not certain, but that's how it should work.

**Comment by d-moos** [comment]
The bot waits until he has 42 pokemons ready to evolve.
After that he activates the egg (automatically) and starts the evolving process.
I'm using the feature and it's actually pretty cool :)

**Comment by giacomofabbri** [comment]
Ok cool!! So as I imagine it will start the process as soon as 42 pidgey/caterpie/pokemon that need little candy, right??? how many pokemon it's possible to evolve using the bot?? I mean normally it's like 50s in 30m, with the bot it's higher?? Thanks guys

**Comment by Tytn** [comment]
It will start whenever the total of possible evolutions is met, no matter what poké afaik (in your case, 42 is your setting).

How many it can do depends on your timeouts, but someone with a bit more experience using the evolver can probably give you a better estimate.

**Comment by giacomofabbri** [comment]
I just checked and I have over 48 weedle+24 caterpie+57 pidgey to evolve but obv it seems it doesn't work!!
Here my config, maybe I made some mistake, I hope that you can help, thanks mate.

{
  "AutoUpdate": false,
  "TransferConfigAndAuthOnUpdate": true,
  "DumpPokemonStats": true,
  "AmountOfPokemonToDisplayOnStart": 10,
  "StartupWelcomeDelay": false,
  "TranslationLanguageCode": "it",
  "WebSocketPort": 14251,
  "Teleport": false,
  "DefaultLatitude": 45.472339,
  "DefaultLongitude": 9.1778907,
  "DefaultAltitude": 10.0,
  "WalkingSpeedInKilometerPerHour": 14.9,
  "MaxSpawnLocationOffset": 10,
  "MaxTravelDistanceInMeters": 2500,
  "UseGpxPathing": false,
  "GpxFile": "GPXPath.GPX",
  "DelayBetweenPlayerActions": 5000,
  "DelayPositionCheckState": 1000,
  "DelayPokestop": 1000,
  "DelayCatchPokemon": 1000,
  "DelayBetweenPokemonCatch": 2000,
  "DelayCatchNearbyPokemon": 1000,
  "DelayCatchLurePokemon": 1000,
  "DelayCatchIncensePokemon": 1000,
  "DelayEvolvePokemon": 1000,
  "DelayEvolveVariation": 0.3,
  "DelayTransferPokemon": 1000,
  "DelayDisplayPokemon": 1000,
  "DelayUseLuckyEgg": 1000,
  "DelaySoftbanRetry": 1000,
  "DelayRecyleItem": 1000,
  "DelaySnipePokemon": 1000,
  "MinDelayBetweenSnipes": 60000,
  "SnipingScanOffset": 0.003,
  "UseEggIncubators": true,
  "RenamePokemon": false,
  "RenameOnlyAboveIv": true,
  "RenameTemplate": "{1}_{0}",
  "TransferDuplicatePokemon": true,
  "PrioritizeIvOverCp": true,
  "KeepMinCp": 950,
  "KeepMinIvPercentage": 85.0,
  "KeepMinDuplicatePokemon": 1,
  "KeepPokemonsThatCanEvolve": true,
  "EvolveAllPokemonWithEnoughCandy": false,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAboveIvValue": 95.0,
  "UseLuckyEggsWhileEvolving": true,
  "UseLuckyEggsMinPokemonAmount": 42,
  "AutomaticallyLevelUpPokemon": false,
  "LevelUpByCPorIv": "iv",
  "UpgradePokemonCpMinimum": 1000.0,
  "UpgradePokemonIvMinimum": 95.0,
  "HumanizeThrows": true,
  "ThrowAccuracyMin": 0.3,
  "ThrowAccuracyMax": 1.0,
  "ThrowSpinFrequency": 0.7,
  "MaxPokeballsPerPokemon": 10,
  "UseGreatBallAboveIv": 75,
  "UseUltraBallAboveIv": 90,
  "UseGreatBallBelowCatchProbability": 0.4,
  "UseUltraBallBelowCatchProbability": 0.2,
  "UseMasterBallBelowCatchProbability": 0.05,
  "UsePokemonToNotCatchFilter": false,
  "UseBerryMinCp": 900,
  "UseBerryMinIv": 82.0,
  "UseBerryBelowCatchProbability": 0.31,
  "AutoFavoritePokemon": false,
  "FavoriteMinIvPercentage": 90.0,
  "TotalAmountOfPokeballsToKeep": 150,
  "TotalAmountOfPotionsToKeep": 30,
  "TotalAmountOfRevivesToKeep": 40,
  "TotalAmountOfBerriesToKeep": 80,
  "RecycleInventoryAtUsagePercentage": 0.9,
  "SnipeAtPokestops": false,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "MinPokeballsToSnipe": 20,
  "MinPokeballsWhileSnipe": 0,
  "UseSnipeLocationServer": false,
  "UsePokeSnipersLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "SnipeRequestTimeoutSeconds": 5,
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    }
  ],
  "PokemonsNotToTransfer": [
    "ditto",
    "articuno",
    "zapdos",
    "moltres",
    "mewtwo",
    "mew"
  ],
  "PokemonsToEvolve": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata",
    "spearow",
    "zubat",
    "doduo"
  ],
  "PokemonsToIgnore": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata",
    "spearow",
    "zubat",
    "doduo"
  ],
  "PokemonsTransferFilter": {
    "Venusaur": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 40.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Charizard": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 20.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Blastoise": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 20.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Nidoqueen": {
      "KeepMinCp": 1750,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Nidoking": {
      "KeepMinCp": 1750,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Clefable": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 60.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Vileplume": {
      "KeepMinCp": 1750,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Golduck": {
      "KeepMinCp": 1750,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Arcanine": {
      "KeepMinCp": 2000,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Poliwrath": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Machamp": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Victreebel": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 60.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Golem": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Slowbro": {
      "KeepMinCp": 1750,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Farfetchd": {
      "KeepMinCp": 1000,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Muk": {
      "KeepMinCp": 2000,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Exeggutor": {
      "KeepMinCp": 2250,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Lickitung": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Chansey": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Kangaskhan": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 60.0,
      "KeepMinDuplicatePokemon": 1
    },
    "MrMime": {
      "KeepMinCp": 250,
      "KeepMinIvPercentage": 40.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Scyther": {
      "KeepMinCp": 1750,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Jynx": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Electabuzz": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Magmar": {
      "KeepMinCp": 1750,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Pinsir": {
      "KeepMinCp": 1750,
      "KeepMinIvPercentage": 98.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Tauros": {
      "KeepMinCp": 500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Gyarados": {
      "KeepMinCp": 1750,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Lapras": {
      "KeepMinCp": 2000,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Eevee": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 98.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Vaporeon": {
      "KeepMinCp": 2000,
      "KeepMinIvPercentage": 98.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Jolteon": {
      "KeepMinCp": 2000,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Flareon": {
      "KeepMinCp": 2000,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Porygon": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Aerodactyl": {
      "KeepMinCp": 1750,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Snorlax": {
      "KeepMinCp": 2500,
      "KeepMinIvPercentage": 96.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Dragonite": {
      "KeepMinCp": 2500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    }
  },
  "PokemonToSnipe": {
    "Locations": [
      {
        "Latitude": 38.556807486461118,
        "Longitude": -121.2383794784546
      },
      {
        "Latitude": -33.859019,
        "Longitude": 151.213098
      },
      {
        "Latitude": 47.5014969,
        "Longitude": -122.0959568
      },
      {
        "Latitude": 51.5025343,
        "Longitude": -0.2055027
      }
    ],
    "Pokemon": [
      "venusaur",
      "charizard",
      "blastoise",
      "beedrill",
      "raichu",
      "sandslash",
      "nidoking",
      "nidoqueen",
      "clefable",
      "ninetales",
      "golbat",
      "vileplume",
      "golduck",
      "primeape",
      "arcanine",
      "poliwrath",
      "alakazam",
      "machamp",
      "golem",
      "rapidash",
      "slowbro",
      "farfetchd",
      "muk",
      "cloyster",
      "gengar",
      "exeggutor",
      "marowak",
      "hitmonchan",
      "lickitung",
      "rhydon",
      "chansey",
      "kangaskhan",
      "starmie",
      "mrMime",
      "scyther",
      "magmar",
      "electabuzz",
      "magmar",
      "jynx",
      "gyarados",
      "lapras",
      "ditto",
      "vaporeon",
      "jolteon",
      "flareon",
      "porygon",
      "kabutops",
      "aerodactyl",
      "snorlax",
      "articuno",
      "zapdos",
      "moltres",
      "dragonite",
      "mewtwo",
      "mew"
    ]
  },
  "PokemonToUseMasterball": [
    "articuno",
    "zapdos",
    "moltres",
    "mew",
    "mewtwo"
  ]
}

**Comment by popoche** [comment]
Yeah i have the same issue, the bot doesn't seem to count same pokemon to evolve :)

**Comment by Nicte** [comment]
"EvolveAllPokemonWithEnoughCandy": false,

That should be true I think. Read the evolve part of the config here: https://github.com/PocketMobsters/PokeMobBot/wiki/Config#evolution

**Comment by NinjaKemuri** [comment]
@Nicte correct! it does need to be true as well. Keep in mind, currently the bot will only evolve the pokemon you have when it uses the lucky egg. It won't continue evolving during the time the egg is active.

I have a workaround to make it keep evolving evolvable pokemon, but it will stop if the bot is closed/crashes. However, I'll submit a PR for it anyway.

**Comment by Valmere** [comment]
Closing since you found your answer and will be making a new PR for a different issue.
