### ISSUE TITLE
[Question] Is it possible to run this on Mac?

### ISSUE THREAD

**Issue by jinkawasaki333** [PocketMobsters/PokeMobBot#536]
Been running the bot on Windows till now, but I wonder if it works on Mac.

**Comment by igromanru** [comment]
It's possible with mono, but maybe it have to be recompiled.

**Comment by Kampfhamster** [comment]
you could use a windows emulator, works fine for me

**Comment by Sterkoel** [comment]
@Kampfhamster What software are you using exactly? Wine? A Virtual Machine?

**Comment by Kampfhamster** [comment]
Parallels, trying to get it to run with wine

**Comment by Sterkoel** [comment]
@Kampfhamster Virtual Machine then, thank you :)
I'm currently trying to compile it with Mono, I'll keep you updated

**Comment by Kampfhamster** [comment]
Nice,
 it would be interesting if you could create a version of the bot, running on android and iOS using the internal gps for location so you don't have to stare at your cellphone while the bot is doing tasks like evolving, and transferring

**Comment by Valmere** [comment]
It's built with Windows in mind, as kampfhamster said use an emulator for other operating systems. Closing as its not an issue with the bot, further discussion can be done on our forums once they're up.
