### ISSUE TITLE
necrobot appears in the project

### ISSUE THREAD

**Issue by ddrmax** [PocketMobsters/PokeMobBot#54]
In some places in the code, Necrobot is showing up, per example in the update section its saying necrobot v0.5.0 is up to date

**Comment by ddrmax** [comment]
it's showing up in these files
PoGo.PokeMobBot.CLI/Config/Translations/translation.fr.json 
CONTRIBUTING.md 
PoGo.PokeMobBot.CLI/PoGo.PokeMobBot.CLI.csproj

**Comment by EyesReye** [comment]
If im right they copyed Necrobot and now are updating it since Necro stopped the project.

**Comment by ddrmax** [comment]
if i have visual studio set up properly and a little bit better at C# and using github i will pull some request with the files already set up
question : is the project compilable with the 2015 community edition? or rather express?

**Comment by Giswald** [comment]
2015 Community Edition is fine.

**Comment by ddrmax** [comment]
Seems to be corrected in the translation already, closing
