### ISSUE TITLE
I always get this error randomly

### ISSUE THREAD

**Issue by scorpionofwar** [PocketMobsters/PokeMobBot#541]
I always get this error randomly on all of my 10bots

`[19:23:58] (ERROR) System.ArgumentOutOfRangeException: Das angegebene Argument liegt außerhalb des gültigen Wertebereichs.
Parametername: index
   bei Google.Protobuf.Collections.RepeatedField`1.get_Item(Int32 index)
   bei PoGo.PokeMobBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() in G:\GIT_Projects\PokeMobBot\PoGo.PokeMobBot.Logic\Tasks\FarmPokestopsTask.cs:Zeile 81.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei PoGo.PokeMobBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in G:\GIT_Projects\PokeMobBot\PoGo.PokeMobBot.Logic\State\FarmState.cs:Zeile 46.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in G:\GIT_Projects\PokeMobBot\PoGo.PokeMobBot.Logic\State\StateMachine.cs:Zeile 37.`

**Comment by Sokifilou** [comment]
+1

**Comment by Valmere** [comment]
Tagging as a bug for reference and closing, if the error occurs again after the bot has been updated make another issue.
