### ISSUE TITLE
Did the bot take 10 steps back when coming to settings and or features?

### ISSUE THREAD

**Issue by Nipper4369** [PocketMobsters/PokeMobBot#543]
Just wondering did the bot take a few steps back when it comes to settings and or features?

I used to have alot of settings that worked. Like transfering pokemon. It when set to keep min 1250 and 90%IV it would still transfer pokemon with 1250 above over one with 900cp but 85 iv. But before it would keep them all with 90%+ and 1250+cp not just and ones. I know there is a setting ot pick iv over cp which is set to false. 

There is the pokeballs/potions/rev.. Used to have total to keep now we need to set for each type again. 

Heck the pokemon to not capture when set to true it still captures the ones on the do not catch list.

To me its like it took a few steps back to how it was. Right now necro is beating it when it comes to the settings working like they should. A

I know this might sound like a rant. But this is also a major problem and making me use necro over mob. and I have been using mob since it split form necro and all worked fine till the last few days.

Been using necro and looking at the settings and compairing them to older pokemob settigns from a few days ago they match up to how advance they used to be. Like

  "KeepPokemonsThatCanEvolve": false,
  "KeepMinCp": 1250,
  "KeepMinIvPercentage": 90.0,
  "KeepMinOperator": "or",

pokemob used to have that last one being and or but now its not there.

It had
"TotalAmountOfPokeballsToKeep": 160,
  "TotalAmountOfPotionsToKeep": 40,
  "TotalAmountOfRevivesToKeep": 10,
  "TotalAmountOfBerriesToKeep": 120,

Which are no longer there and switch back to setting for each type of item.

**Comment by littlemonster1** [comment]
it seems as if the priority of PokeMobBot is not always having a stable core base of the bot, but advanced futures take a priority. but ... pssh, don't talk about that. they are very sensitive and saying that will get you banned ;)

**Comment by Valmere** [comment]
Item configuration has been added to the dev branch and will be in the next release. I'm also working on alternative transfer methods since it has been slimmed down compared to previous days.
