### ISSUE TITLE
Error that logs me off.

### ISSUE THREAD

**Issue by marcosabruna** [PocketMobsters/PokeMobBot#545]
I been getting this error lately and the bot stop working. Not sure what is it.
![error](https://cloud.githubusercontent.com/assets/20782002/17377808/6a980816-5989-11e6-8553-56f19620f9ff.png)

**Comment by kaeld59** [comment]
Same here

**Comment by mobotvirus** [comment]
same

**Comment by marcosabruna** [comment]
Bump.

**Comment by Valmere** [comment]
Tagging as a bug for reference and closing, if the error occurs again after the bot has been updated make another issue.
