### ISSUE TITLE
Sniping not starting properly

### ISSUE THREAD

**Issue by veritas718** [PocketMobsters/PokeMobBot#55]
Sniping doesnt seem to be starting even though pokefeeder is running and working. 
Does it matter that poke names are lowercase in the config - they had been capitalized in prior configs. That shouldnt be it though because it doesnt say its trying to snipe any locations.

  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": true,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "UseSnipeLocationServer": true,

"PokemonToSnipe": {
    "Locations": [
      {
        "Latitude": 38.556807486461118,
        "Longitude": -121.2383794784546
      },
      {
        "Latitude": -33.859019,
        "Longitude": 151.213098
      },
      {
        "Latitude": 47.5014969,
        "Longitude": -122.0959568
      },
      {
        "Latitude": 51.5025343,
        "Longitude": -0.2055027
      }
    ],
    "Pokemon": [
      "venusaur",
      "charizard",
      "blastoise",
      "beedrill",
...

**Comment by manyunya** [comment]
veritas718   you need to use

"SnipeAtPokestops": true,
 "SnipeIgnoreUnknownIv": true,
 "SnipeLocationServer": "localhost",
 "SnipeLocationServerPort": 16969,
 "UseSnipeLocationServer": **false**,


but,   "SnipeAtPokestops" mode does not work, only works "UseSnipeLocationServer".

**Comment by veritas718** [comment]
so i can only use one? either snipeatpokestops or usesnipelocationserver? but not both together?

**Comment by d3structor84** [comment]
Try:

"SnipeAtPokestops": true,
"SnipeIgnoreUnknownIv": **false**,
"SnipeLocationServer": "localhost",
"SnipeLocationServerPort": 16969,
"UseSnipeLocationServer": true,

**Comment by manyunya** [comment]
only one of the modes has always worked.
it would be good if repaired mode "SnipeAtPokestops" and made it possible to use both modes simultaneously.

**Comment by Esukho** [comment]
better to add pokesnipers.com Feature :) Thats realy nice

**Comment by d3structor84** [comment]
"SnipeAtPokestops" just enables Sniping as stated in the Wiki.

If "UseSnipeLocationServer"is set to true, the Bot uses PogoLocationFeeder.
Otherwise it uses your list in the configs.

Sniping doesn't work for me either if "SnipeIgnoreUnknownIv" is set to true.

**Comment by d3structor84** [comment]
@Esukho
Pokesnipers was added in Necrobot last night.
I prefer the actual update, as it is more updated than pokesnipers if you have enough sources in the config.

**Comment by veritas718** [comment]
I can confirm it works even with SnipeAtPokestops set to false. 
Unknown IV also doesn't seem to be a problem:
[06:18:00] (INFO) [Sniper] Sniping a Arcanine with unknown IV at 40.405205299358,-3.680666366615...
[06:18:04] (PKMN) (CatchSuccess) | (Normal) Arcanine Lvl: 24 CP: (1933/2046) IV: 59.00% | Chance: 6.11% | 5769515.37m dist | with a UltraBall (78 left). | Candies: 10

Its not totally clear when it should snipe, so its hard to tell if it is working as it should.
I just want to catch a Missingo, is that too much to ask for!

**Comment by d3structor84** [comment]
How did you configured sniping now?

**Comment by Zenithxm** [comment]
wew can you give us your config?

**Comment by veritas718** [comment]
{
  "AmountOfPokemonToDisplayOnStart": 10,
  "AutomaticallyLevelUpPokemon": false,
  "AutoUpdate": true,
  "DefaultAltitude": 10.0,
  "DefaultLatitude": 40.785091,
  "DefaultLongitude": -73.968285,
  "Teleport": false,
  "DelayBetweenPlayerActions": 1100,
  "DelayBetweenPokemonCatch": 2000,
  "DelayCatchNearbyPokemon": 400,
  "DelayPositionCheckState": 1000,
  "DelayCatchIncensePokemon": 1000,
  "DelayCatchLurePokemon": 1000,
  "DelayCatchPokemon": 1000,
  "DelayDisplayPokemon": 10,
  "DelayUseLuckyEgg": 1000,
  "DelaySoftbanRetry": 1000,
  "DelayPokestop": 10,
  "DelayRecyleItem": 10,
  "DelaySnipePokemon": 10,
  "DelayTransferPokemon": 10,
  "DumpPokemonStats": true,
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": true,
  "GpxFile": "baston.GPX",
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemRazzBerry",
      "Value": 50
    },
    {
      "Key": "itemBlukBerry",
      "Value": 10
    },
    {
      "Key": "itemNanabBerry",
      "Value": 10
    },
    {
      "Key": "itemWeparBerry",
      "Value": 30
    },
    {
      "Key": "itemPinapBerry",
      "Value": 30
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    }
  ],
  "KeepMinCp": 1250,
  "KeepMinDuplicatePokemon": 2,
  "KeepMinIvPercentage": 90.0,
  "KeepPokemonsThatCanEvolve": false,
  "LevelUpByCPorIv": "iv",
  "MaxPokeballsPerPokemon": 8,
  "MaxSpawnLocationOffset": 1000,
  "MaxTravelDistanceInMeters": 2000,
  "MinDelayBetweenSnipes": 60000,
  "MinPokeballsToSnipe": 20,
  "MinPokeballsWhileSnipe": 0,
  "PokemonsNotToTransfer": [
    "venusaur",
    "charizard",
    "blastoise",
    "nidoqueen",
    "nidoking",
    "clefable",
    "vileplume",
    "arcanine",
    "poliwrath",
    "machamp",
    "victreebel",
    "golem",
    "slowbro",
    "muk",
    "exeggutor",
    "lickitung",
    "chansey",
    "ditto",
    "articuno",
    "zapdos",
    "moltres",
    "mewtwo",
    "mew"
  ],
  "PokemonsToEvolve": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata"
  ],
  "PokemonsToIgnore": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata",
    "spearow",
    "zubat",
    "doduo"
  ],
  "PokemonsTransferFilter": {
    "Golduck": {
      "KeepMinCp": 1800,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Farfetchd": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Krabby": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Kangaskhan": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 60.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Horsea": {
      "KeepMinCp": 1800,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Staryu": {
      "KeepMinCp": 1800,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "MrMime": {
      "KeepMinCp": 1800,
      "KeepMinIvPercentage": 40.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Scyther": {
      "KeepMinCp": 1800,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Jynx": {
      "KeepMinCp": 1800,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Electabuzz": {
      "KeepMinCp": 1800,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Magmar": {
      "KeepMinCp": 1800,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Pinsir": {
      "KeepMinCp": 1800,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Tauros": {
      "KeepMinCp": 1800,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Magikarp": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Gyarados": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 4
    },
    "Lapras": {
      "KeepMinCp": 1800,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 3
    },
    "Eevee": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Vaporeon": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 4
    },
    "Jolteon": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 4
    },
    "Flareon": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 4
    },
    "Porygon": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 60.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Snorlax": {
      "KeepMinCp": 2600,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 6
    },
    "Dragonite": {
      "KeepMinCp": 2600,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 6
    }
  },
  "PokemonToSnipe": {
    "Locations": [
      {
        "Latitude": 38.556807486461118,
        "Longitude": -121.2383794784546
      },
      {
        "Latitude": -33.859019,
        "Longitude": 151.213098
      },
      {
        "Latitude": 47.5014969,
        "Longitude": -122.0959568
      },
      {
        "Latitude": 51.5025343,
        "Longitude": -0.2055027
      }
    ],
    "Pokemon": [
      "venusaur",
      "charizard",
      "blastoise",
      "beedrill",
      "raichu",
      "sandslash",
      "nidoking",
      "nidoqueen",
      "clefable",
      "ninetales",
      "golbat",
      "vileplume",
      "golduck",
      "primeape",
      "arcanine",
      "poliwrath",
      "alakazam",
      "machamp",
      "golem",
      "rapidash",
      "slowbro",
      "farfetchd",
      "eevee",
      "muk",
      "cloyster",
      "gengar",
      "exeggutor",
      "marowak",
      "hitmonchan",
      "lickitung",
      "rhydon",
      "chansey",
      "kangaskhan",
      "starmie",
      "mrMime",
      "scyther",
      "magmar",
      "electabuzz",
      "jynx",
      "gyarados",
      "lapras",
      "ditto",
      "vaporeon",
      "jolteon",
      "flareon",
      "porygon",
      "kabutops",
      "aerodactyl",
      "snorlax",
      "articuno",
      "zapdos",
      "moltres",
      "dragonite",
      "mewtwo",
      "mew",
      "missingno"
    ]
  },
  "PokemonToUseMasterball": [
    "articuno",
    "zapdos",
    "moltres",
    "mew",
    "mewtwo"
  ],
  "PrioritizeIvOverCp": true,
  "RenameOnlyAboveIv": true,
  "RenamePokemon": false,
  "RenameTemplate": "{1}_{0}",
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "StartupWelcomeDelay": false,
  "TotalAmountOfPokebalsToKeep": 120,
  "TotalAmountOfPotionsToKeep": 80,
  "TotalAmountOfRevivesToKeep": 60,
  "TransferConfigAndAuthOnUpdate": true,
  "TransferDuplicatePokemon": true,
  "TranslationLanguageCode": "en",
  "UpgradePokemonCpMinimum": 1000.0,
  "UpgradePokemonIvMinimum": 95.0,
  "UseEggIncubators": true,
  "UseGpxPathing": false,
  "UseGreatBallAboveCp": 750,
  "UseLuckyEggsMinPokemonAmount": 30,
  "UseLuckyEggsWhileEvolving": false,
  "UseMasterBallAboveCp": 1500,
  "UsePokemonToNotCatchFilter": false,
  "UseSnipeLocationServer": true,
  "UseTransferIvForSnipe": true,
  "UseUltraBallAboveCp": 1000,
  "WalkingSpeedInKilometerPerHour": 28.0,
  "WebSocketPort": 14251
}

**Comment by veritas718** [comment]
and the pogo channels are
"ServerChannels": [
    "sniping",
    "high_iv_pokemon",
    "90_plus_iv",
    "coordsbots",
    "rare_pokemon"
  ]

**Comment by d3structor84** [comment]
So at the moment you are just sniping for Pokemons with an iv > 90, right?

"UseTransferIvForSnipe": true,

the rest is close to my config.

**Comment by veritas718** [comment]
[config.txt](https://github.com/PocketMobsters/PokeMobBot/files/392353/config.txt)

**Comment by veritas718** [comment]
yeah, im using UseTransferIv, but where would it be set to only snipe above 90?

**Comment by veritas718** [comment]
so maybe i was confusing SnipeIgnoreUnknownIv for UseTransferIV.. 
Having ingore off and transfer off, Ill see if it tries to catch more- I mean, it should.

**Comment by d3structor84** [comment]
UseTransferIV... uses "KeepMinIvPercentage": 90.0 i think.
So he only catches Pokemons with iv > 90%.

Still doing some testing.

**Comment by veritas718** [comment]
:) 
That was the the problem. Really not paying attention and a not so well named option. 
With both transfer and unknown off, it will encounter the most, and then can transfer after. Which is what I wanted to get more stardust now that auto power up is enabled. 
Now Id like to better understand when it starts checking if there are things to snipe because it still seems to be walking around when it could be sniping.

**Comment by d3structor84** [comment]
To summarize my testings:

"SnipeAtPokestops": true -> enable/disable sniping
"SnipeIgnoreUnknownIv": false -> seems like Bot isn't reading the IV properly as no Spiking appears, when this is set to true
"UseTransferIvForSnipe": false -> doesn't seem to have any effect. In my config "KeepMinIvPercentage" is set to 90.0, but the bot catches Pokemon with an iv less than that anyway.

Could someone confirm this?

**Comment by qroneL** [comment]
hi guys,
i could not able to catch any pokemons with sniper so far. My config settings are like this.

  "UseSnipeLocationServer": true,
  "UseTransferIvForSnipe": false,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,

Any idea what am i doing wrong ? Do i need to join any channels in discord or something like that ?

**Comment by d3structor84** [comment]
yes, you need to enter the channel with your account.

**Comment by Esukho** [comment]
how can i enter the channel ?

**Comment by Zenithxm** [comment]
how i can snipe with join channel?? i don't get it

**Comment by d3structor84** [comment]
Click here: https://discordapp.com/invite/8msqsWV

Register if you have not done yet.

Edit the config.json in PokeFeed-Folder:

`{
  "ServerChannels": [
    "coordsbots",
    "90_plus_iv"
  ],
  "DiscordToken": "",
  "Port": 16969,
  "useToken": false,
  "DiscordUser": "yourdiscordemailaddress",
  "DiscordPassword": "yourdiscordpassword"
}`

You can add more Channels by finding more Discord-Chats that are pronouncing Rare or High-IV Pokemons in chat.
Just search for them in google.

**Comment by Esukho** [comment]
in my Pokemobbot Folder is not a config.json

**Comment by d3structor84** [comment]
you haven't read the wiki right?

download this and extract: https://github.com/5andr0/PogoLocationFeeder/releases/latest

**Comment by Zenithxm** [comment]
oooooo thank you

**Comment by qroneL** [comment]
any idea when manual sniping feature get fixed ?

**Comment by Davaogedy** [comment]
Hey Guys,
Hey d3structor84,

i want to add to my Necrobot / PokeMobBot the sniping with Discord.

I downloaded this PogoLocation Feeder:
https://github.com/5andr0/PogoLocationFeeder/releases/latest

and of course my PokeMobBot:
https://github.com/PocketMobsters/PokeMobBot/releases

But i don't get how i can combine both.... (I am sorry i am new to the bot materia)

This is my Config in my PokeMobBot (copied from veritas718)
[config.txt](https://github.com/PocketMobsters/PokeMobBot/files/392468/config.txt)

BUT... do i have to put everything from the PoGo Location feeder in the normal PokeMobBot folder?

Please Help me :D

**Comment by d3structor84** [comment]
@Davaogedy

Just start PogoLocationFeeder.exe.
On first start it will create a config.json in the same folder.
Edit it to your wishings.
Start with this configuration:

{
"ServerChannels": [
"coordsbots",
"90_plus_iv"
],
"DiscordToken": "",
"Port": 16969,
"useToken": false,
"DiscordUser": "**yourdiscordemailaddress**",
"DiscordPassword": "**yourdiscordpassword**"
}

Open Discord with : https://discordapp.com/
Register if not done yet.

Now you need to join Chats with your Account:
https://discord.gg/VsVrjgr
and/or
https://discord.gg/sTQBGpm


Enter your login-data into config.json.

Your PokeMobBot-Config seems fine.
Personally i would change "UseTransferIvForSnipe" to false, but that is your choice.

Now start the PogoLocationFeeder.exe again.
The Terminal should show "Listening".
After 30 sec - 1 min there should appear entries with pokemons and coordinates.

Now start the Bot again.
In the PogoLocationFeeder-Terminal there should be something like "New connection from 127.0.0.1:53971"

That means the Bot connected to PogoLocationFeeder.

Thats it. Now the Bot should snipe at the locations showing in the PogoLocationFeeder-Terminal.

You can add more channels by joining chats and enter the channels into the config.

**Comment by Davaogedy** [comment]
Thanks man!

I Posted my text and at the Same Moment it worked (lol).

But thanks for the advise with multiple chat rooms and the "UseTransferIvForSnipe". I will definitly change this.

I think this will help a lot of other people:)

Once again, thanks!

**Comment by weda0511** [comment]
I am a netizen from mainland China, I studied for five hours. Still can't automatically grab elf, I've been using the above method or not. Perhaps my English is not good, no full understanding. Looking forward to your help and reply. A netizen from the other end of the earth, my email address is wangwei.0511@qq.com     Technology without borders  (software translation, please forgive me.）

**Comment by UntilSunrise** [comment]
looks like fixed, if not please reopen
