### ISSUE TITLE
problem about Amount Of Berries To Keep

### ISSUE THREAD

**Issue by KidLoad93** [PocketMobsters/PokeMobBot#554]
i had set a value for TotalAmountOfBerriesToKeep in line 74 file config.json 
but the bot  is not work with this parameter but working normal with other.
example i set it 30 but it still increase to 80 and my iventory is full with this berry

**Comment by globus243** [comment]
i second this.

**Comment by jimconnor** [comment]
This was resolved in a recent update. It may appear that the bot updated but this did not resolve for me till I downloaded an entirely new version/zip. Annoying to copy over settings, but it worked for me afterwards.

As the bot is not currently usable, just wait till the next release.

**Comment by Valmere** [comment]
Berry configuration is in the next release.
