### ISSUE TITLE
Error after signin in with google accout..

### ISSUE THREAD

**Issue by vdellevoet** [PocketMobsters/PokeMobBot#557]
Hi Guys,

For a while the bot worked well but since an half an our it is returning this message
[22:02:41] (INFO) Logging in using account Google
[22:02:42] (ERROR) System.UriFormatException: Ongeldige URI: de hostnaam kan niet worden geparseerd.
   bij System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   bij System.Uri..ctor(String uriString, UriKind uriKind)
   bij System.Net.Http.HttpClient.CreateUri(String uri)
   bij PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__1`1.MoveNext() in G:\GIT_Projects\PokeMobBot\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:regel 50
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0`2.MoveNext() in G:\GIT_Projects\PokeMobBot\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:regel 18
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__6`2.MoveNext() in G:\GIT_Projects\PokeMobBot\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:regel 0
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__3.MoveNext() in G:\GIT_Projects\PokeMobBot\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Rpc\Player.cs:regel 52
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij PoGo.PokeMobBot.Logic.State.LoginState.<DownloadProfile>d__2.MoveNext() in G:\GIT_Projects\PokeMobBot\PoGo.PokeMobBot.Logic\State\LoginState.cs:regel 147
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   bij PoGo.PokeMobBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in G:\GIT_Projects\PokeMobBot\PoGo.PokeMobBot.Logic\State\LoginState.cs:regel 114
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in G:\GIT_Projects\PokeMobBot\PoGo.PokeMobBot.Logic\State\StateMachine.cs:regel 37

how can i fix this issue

Thanks alot

**Comment by Spawnguz** [comment]
I have a same problem
