### ISSUE TITLE
Guys new problem help me!!! What is that!??

### ISSUE THREAD

**Issue by steamlab13** [PocketMobsters/PokeMobBot#558]
Can someone help me???
![trouble](https://cloud.githubusercontent.com/assets/20803983/17380555/60281f8c-59d0-11e6-82d6-fd00a5bcd30a.png)

**Comment by AriNubar** [comment]
Have the same problem

**Comment by steamlab13** [comment]
@AriNubar yeah i see! ^_^

**Comment by GreatLordHector** [comment]
same

**Comment by bbekkis** [comment]
Paste this 

> https://raw.githubusercontent.com/PocketMobsters/PokeMobBot/development/PoGo.PokeMobBot.CLI/App.config

into your release folder, into that "PokeMobBot.exe"-conf file. Just replace everything inside it with what you just copied from that site. Worked for me.

**Comment by TheBods** [comment]
@bbekkis Stops the login errors but now shows no useable pokestops in area:

[21:32:56] No usable PokeStops found in your area. Is your maximum distance too small?

**Comment by southdalls20** [comment]
Now its saying no pokestops or usable. HELP!!

**Comment by globus243** [comment]
please watch for other tickets before you open a new one there was already one describing your exact error. 
And why did you post a screenshot that isn't copy-able. Please copy the log next time and use a more speaking title and less punctuation marks.
