### ISSUE TITLE
No Pokestops in your area.

### ISSUE THREAD

**Issue by CharminTP** [PocketMobsters/PokeMobBot#562]
Im having a problem where it just says over and over "(ATTENTION) No usable Pokestops found in your area. Is your maximum distance too small?" And it never goes past this statement.

**Comment by calebkaris** [comment]
same here
i tried reinstalling but then i got "your outside of your defined radius"
and it asked if my coords.ini file was right... but i cant find that

**Comment by jhontheripper** [comment]
i have the same problem, i think its the pokemon go api, doesn't works 0.93 version anymore

**Comment by eviqnine** [comment]
same here...i think they update their servers

**Comment by globus243** [comment]
please watch for other tickets before you open a new one there was already one describing your exact error. 
everybody here is sacrificing his free time so please behave a bit more respectful when asking for help.

**Comment by Zerotask** [comment]
Yea, I also wanted to create a new issue for that :D

**Comment by Timetis1** [comment]
Do you guys know when its gona get fixed or update the bot?

**Comment by jomarocas** [comment]
the bot need update because Niantic change the api

**Comment by papadii** [comment]
waiting an angel can solve this..
