### ISSUE TITLE
[Idea] Use normal Balls befor use better Balls until Limit

### ISSUE THREAD

**Issue by JPH-Systems** [PocketMobsters/PokeMobBot#564]
I don´t know how to post an idea, so I did it here (sorry).

When I set my limit for normal Pokeballs to 100 but I have 120 and the Bot want to catch an Pokemon but want to use a better Pokeball, can it first use 20 normal Pokeballs instead to throw it away or use more normal Pokeballs until it reaches the limit of 100. These balls are already "trash" and the bot can use this "trash" without limits. 
Maybe you can also add new limits. At 150 it starts to throw it away until 100 and between 100 and 150 it uses only normal balls until it reaches 100 and then it uses his normal limits (use a berry/better ball or flew). When it reaches 150, it trow 50 balls away (when its time for it).

**Comment by Bananab0y** [comment]
This is a little confusing to me.

- If you use 20 normal Pokeballs on a 1500+ CP Pokemon, chances are that the Pokemon is gonna flee. It's better to just recycle them to make space for Greatballs and Ultraballs since their catchrate is higher. The bot saves up on Great- and Ultraballs by recycling away excessive normal Pokeballs so it can use the better balls rather than the normal ones.

- You can set when to throw which ball in the config from line 71-78.

**Comment by mistnin1** [comment]
Idk if this is the same problem that you're happening, but with mine the bot seems to be choosing to use any and all ultra balls first regardless of the pokemons power. EX: it used an ultra ball to catch a low level abra. 
Once ultra balls are depleted the bot starts using great balls until those too are depleted. No matter what changes I have made to the config this has not changed.

**Comment by Valmere** [comment]
Change your settings for when the bot should use ultraballs.

**Comment by JPH-Systems** [comment]
It´s not the problem when to use a great or a ultra ball. I think its a waste to use a great ball on a pidgey or on a rattata. I think the bot can waste normal pokeballs on that pokemons, when the bot recycles these balls in a few pokestops. I only catch pidgeys to farm XP and later to use a lucky egg and evolve some.

My config is not perfect yet but i doesn´t see an option to set some filters for some specific pokemons. I seen only an option for pokemons not to catch and a transfer filter. 
A good start is to add an option like "PokemonToUseMasterball" only for normal pokeballs.

**Comment by Valmere** [comment]
That's not efficient. Whatever the pokemon is does not matter, using a higher ball against higher CP pokemon results in a higher catch chance.
