### ISSUE TITLE
No Usable Pokestops

### ISSUE THREAD

**Issue by UraharaKisuke07** [PocketMobsters/PokeMobBot#565]
Been showing this error for the past 10 minutes. 
> (EGG) Incubator status update: 2.56 KM left
> No usable Pokestops found in your area. Is your maximum distance too small? 
.... and so on. 
1) Max distance is set to 3000 m.
2) Speed is 15 km/hr
3) I can use Pokestops and catch pokemons (in the coords listed in config file) while using Nox ie. I'm not softbanned.

**Comment by linuscool2** [comment]
Same here
