### ISSUE TITLE
An error message appears every time I start the executable.

### ISSUE THREAD

**Issue by youcantbreakmysoul** [PocketMobsters/PokeMobBot#566]
"No usable PokeStops found in your area. Is your maximum distance too small?"
This message Appears over and over every time i start the launcher, and it's not soft ban because i tried to play in Nox and It works fine, i can take PokeStops and all the stuff, this error appears when i started my computer, i used for 2 days till today, and all worked good .

**Comment by UraharaKisuke07** [comment]
Niantic changed their API. Everyone's having this issue.

**Comment by ruddock** [comment]
already 2 topics about this issue, Devs are on it.

**Comment by marty455** [comment]
Yep, everybody has this issue. My bot also recycled all his pokeballs and potions, not sure if this is related to the API change.

**Comment by UraharaKisuke07** [comment]
AFAIK the recycling is unique to some users. I have the exact same number of items as I had before the error started to appear.
