### ISSUE TITLE
no pokestops

### ISSUE THREAD

**Issue by amcos** [PocketMobsters/PokeMobBot#567]
i try to enter the bot but its say no pokestops in the area the distans to small pliz fix

**Comment by JPH-Systems** [comment]
Can you read other Topics? Niantic changed the API and the devs are on it.

**Comment by Leo3dprinter** [comment]
same here 

[15:01:01] (EGG) Incubator status update: 2.00km left
[15:01:02] (ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?

**Comment by amcos** [comment]
yea yea

**Comment by JPH-Systems** [comment]
i think so. Look on the Code page and look on "Latest commit eb1c6ab 2 hours ago" When a new commit is out, start your bot and when the error is not fix, look what others are writing in issues.

**Comment by amcos** [comment]
ohhhh ok ty :)

**Comment by legend6868** [comment]
It means we need to wait for a new release or where I can fix by myself.

**Comment by Niro007** [comment]
I was botting just fine this morning till a few minutes ago with the following message.
"No usable pokestops found in your area. Is your maximum distance too small?"

On another note when asking these developers if they are working on it they are let's just be a bit more patient cause most of the time they don't get paid with these kinds of projects.

TY

**Comment by xSkrom** [comment]
That's good now ?

**Comment by kdevine** [comment]
I have the latest development branch and it is still not working.  It is pulling in the correct stuff from the API but all the arrays are empty...

**Comment by xSkrom** [comment]
Okay :)
