### ISSUE TITLE
No PokeStops to visit here

### ISSUE THREAD

**Issue by mewtowman** [PocketMobsters/PokeMobBot#568]
the bot give me this message  when a click star :/  any solution?

" No PokeStops to visit here, please stop the bot and change your location."
"No nearby useful locations found. Please wait 10 seconds."

**Comment by sredlin** [comment]
known issure after server update

please read the other posts before posting the same question over and over again

**Comment by JPH-Systems** [comment]
https://github.com/PocketMobsters/PokeMobBot/issues/560
https://github.com/PocketMobsters/PokeMobBot/issues/561
https://github.com/PocketMobsters/PokeMobBot/issues/562
https://github.com/PocketMobsters/PokeMobBot/issues/566

Chose one and read.

**Comment by marty455** [comment]
There are literally like 4 other posts right now saying the same thing you did
