### ISSUE TITLE
red error on bot 

### ISSUE THREAD

**Issue by BlueskyMet** [PocketMobsters/PokeMobBot#571]
[00:04:11] System.IO.FileNotFoundException: Impossibile trovare il file 'C:\Users\Trebia\Desktop\mobot BlueskyMet\GPXPath.GPX'.
Nome file: 'C:\Users\Trebia\Desktop\mobot BlueskyMet\GPXPath.GPX'
   in System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   in System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   in System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   in System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   in System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   in System.IO.File.ReadAllText(String path)
   in PoGo.PokeMobBot.Logic.Tasks.FarmPokestopsGpxTask.GetGpxTracks(ISession session) in G:\GIT_Projects\PokeMobBot\PoGo.PokeMobBot.Logic\Tasks\FarmPokestopsGPXTask.cs:riga 161
   in PoGo.PokeMobBot.Logic.Tasks.FarmPokestopsGpxTask.<Execute>d__1.MoveNext() in G:\GIT_Projects\PokeMobBot\PoGo.PokeMobBot.Logic\Tasks\FarmPokestopsGPXTask.cs:riga 0
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in PoGo.PokeMobBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in G:\GIT_Projects\PokeMobBot\PoGo.PokeMobBot.Logic\State\FarmState.cs:riga 42
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in G:\GIT_Projects\PokeMobBot\PoGo.PokeMobBot.Logic\State\StateMachine.cs:riga 37

We need wait for new release of bot ?

**Comment by Austeri** [comment]
Yes, you need to wait for a new release.

**Comment by calebkaris** [comment]
any idea how long that might be people?

**Comment by Valmere** [comment]
It will be ready when its ready, but @BlueskyMet's problem seems to be a GPX file not being found.
