### ISSUE TITLE
New user, How long does update take?

### ISSUE THREAD

**Issue by tintin250** [PocketMobsters/PokeMobBot#573]
I just started using this yesterday and I love it, wondering how long is usually takes for an update.

**Comment by anthonytoorie** [comment]
The entire api was changed. Probably tomorrow?

**Comment by achmad2688** [comment]
is it works? can you update it faster? 😀😀😀

**Comment by howcanihelp** [comment]
dude, they are already doing this for free.
keep it cool and respect their timing.
they also have other things to do in their lifes.

**Comment by Valmere** [comment]
Follow progress in the #announcement channel in our discord
