### ISSUE TITLE
Is their a response to the no usable pokestops glitch 

### ISSUE THREAD

**Issue by teamrockettroll** [PocketMobsters/PokeMobBot#577]
or maybe a api fir soon, i saw it saw fixed this morning but I think my bots updated auto ?

**Comment by Edaught** [comment]
Well like the others issues that already been opened that you have might not seen. The nice developers on this project are currently trying to fix the problem.

It seems that a change in the api made it different to get the pokestops

**Comment by teamrockettroll** [comment]
thanks for the info, do you know how to turn it off and just have it walk around and catch poks

**Comment by naxxoll** [comment]
can i leaf the bot open will it update it's self ?

**Comment by XHusHX** [comment]
the notice always "no usable pokestop" although i have moved to another coordinate

**Comment by GreenGoblinz** [comment]
this bug is being worked on by the developers, they've suggested no one login to their bots for the time being.

**Comment by XHusHX** [comment]
oke thanks to developer who fix this bug

**Comment by rrobert45** [comment]
http://otakukart.com/animeblog/2016/08/03/minimum-scanning-time-doubled-see-effects/

**Comment by mistnin1** [comment]
Something I've noticed is in the coding the "distance I can travel option is gone.

**Comment by teamrockettroll** [comment]
im currently in the discord as coldblooded if you need me..

**Comment by OkkieDokkie** [comment]
that the bot already works? 
i just open and still no found pokestop usable .. why..?
