### ISSUE TITLE
Does not load fully, help!?

### ISSUE THREAD

**Issue by Kristianqq** [PocketMobsters/PokeMobBot#578]
![image](https://cloud.githubusercontent.com/assets/20826837/17385486/3de00e36-59e3-11e6-9d7a-65bfa865dd42.png)

**Comment by popoche** [comment]
Omg please read before post :/

**Comment by Edaught** [comment]
This problem has been reported multiple times already. If you could at least try to read the other recent issues before posting that would be great.

**Comment by xSkrom** [comment]
Where we can see when the new version is okay ?

**Comment by lalmanzar** [comment]
Maybe just wait and check the release page to see when the app is updated....
https://github.com/PocketMobsters/PokeMobBot/releases
