### ISSUE TITLE
so one question

### ISSUE THREAD

**Issue by hadithekilla** [PocketMobsters/PokeMobBot#581]
so are the developers are working on a fix at the moment?

**Comment by popoche** [comment]
Wait a little, they are human.

**Comment by jinkawasaki333** [comment]
People need to sleep. They owe us nothing to fix the bot.

**Comment by hadithekilla** [comment]
i know that

**Comment by xSkrom** [comment]
Please what's the time in USA now ? I'm french

**Comment by xSkrom** [comment]
or london if the devs are english

**Comment by hadithekilla** [comment]
^ 8:10 pm

**Comment by BunyaminS** [comment]
U are already ahead of most of the non-cheaters, chill

**Comment by XHusHX** [comment]
im indonesian....here is 7.12 am

**Comment by XHusHX** [comment]
hi USA and french people....nice to meet you in this moment

**Comment by xSkrom** [comment]
Me it's 2:00 am, hi everybody

**Comment by naxxoll** [comment]
me too ^^

**Comment by jinkawasaki333** [comment]
Go to Discord to chat. Here is not the place.

**Comment by XHusHX** [comment]
when the bot is fix bro?

**Comment by renenguyen0** [comment]
what is the discord chat invite?

**Comment by Salvatrucha** [comment]
How i can join to discord chat?
