### ISSUE TITLE
Can someone point me to the restful call that is failing?

### ISSUE THREAD

**Issue by anthonytoorie** [PocketMobsters/PokeMobBot#584]
I am a programmer but am lazy. I want to help this project out.

**Comment by solbiee** [comment]
https://github.com/PocketMobsters/PokeMobBot/commit/eb1c6abff719db20d652e32f781931c7a6b0f544

**Comment by solbiee** [comment]
that and we think niantic changed api

**Comment by anthonytoorie** [comment]
where is the item1 class . can we look at that?

**Comment by anthonytoorie** [comment]
yes they did the responses are not the same

**Comment by anthonytoorie** [comment]
afaik* someone else tested this
