### ISSUE TITLE
there is no bot.exe

### ISSUE THREAD

**Issue by dogalmadensuyu** [PocketMobsters/PokeMobBot#587]
i just downloaded the bot but i cant start it because of there is not a bot.exe

**Comment by ShallowHacker** [comment]
The bots dont work anyways dude.

**Comment by xfaustx** [comment]
https://www.youtube.com/watch?v=2I33k8vV3Sk

**Comment by vison99** [comment]
best question i have ever seen +1

**Comment by azkataphrakt** [comment]
@dogalmadensuyu download the release and not the source

**Comment by Valmere** [comment]
Bots are not working at the moment.
