### ISSUE TITLE
Nox is behaving and having simlar issues as PokeMobBot

### ISSUE THREAD

**Issue by Niro007** [PocketMobsters/PokeMobBot#588]
Just checked again and it still says the same thing.. so i decided to go manually and do Nox again and weird thing is that i do not see any damn gym's nor pokestops and on top of that the keyboard arrows stopped working on Nox itself (but not on the actual PC) and to finish it off it says no GPS on top.

I may jump the gun here but i think Niatic is honing in and may do some bans sooner than we think.  
: (

Anyone else experiencing anything like this?

**Comment by kuntoharr** [comment]
I have the same problem, but it just said that my maximum distance is too small. so anyone can help?

**Comment by R0DaV-D0rIaN** [comment]
same, even though location is correct

**Comment by UraharaKisuke07** [comment]
Guys please read the previous thread. It's a known issue and devs are working on it. please don't make duplicate posts.

**Comment by howcanihelp** [comment]
nor quadruplicate posts, nor 10x...
