### ISSUE TITLE
Necrobot stopped working and is stuck

### ISSUE THREAD

**Issue by aetherfire** [PocketMobsters/PokeMobBot#589]
![image](https://cloud.githubusercontent.com/assets/20830846/17390291/66fcc0b4-59d1-11e6-9724-c61c0ddfec15.png)
My bot gets stuck at telling me how long my eggs have left to hatch and then says no usable pokestops found in your area. and then loops.

Im using a normal bot to level an account and hatch eggs and its catches pretty much everything for exp and such. But idk why it's getting stuck atm. Ive logged in and cleared my bag except pokeballs, and ive cleaned my pokemon tab.

**Comment by UraharaKisuke07** [comment]
Please read  previous threads and close this.

**Comment by Hemil96** [comment]
same problem from last night
