### ISSUE TITLE
"SnipeAtPokestops" mode does not work, only works "UseSnipeLocationServer".

### ISSUE THREAD

**Issue by manyunya** [PocketMobsters/PokeMobBot#59]
"SnipeAtPokestops" mode does not work, only works "UseSnipeLocationServer".
  made it possible to use both modes simultaneously.

**Comment by DeadlyOG** [comment]
without a pokesnipe location server used, just keep getting "no pokemon found to snipe" no matter how many coords and pokemon are entered in the config.

**Comment by jakesmurf** [comment]
This is basically a duplicate issue to #88.  

The reason that this is happening is because pokevision is down and that is what the bot uses to scan your snipe locations for targets.  #88 is a request for an alternative web source for targets from pokevision, which should fix this issue.

**Comment by Afraidium** [comment]
@DurtyFree Please close.
