### ISSUE TITLE
FUTURE BANS ???

### ISSUE THREAD

**Issue by teamrockettroll** [PocketMobsters/PokeMobBot#591]
https://plus.google.com/+Ingress/posts/EaAmBqfBQck
maybe jumping from place to place wont work so well if you want to keep account

**Comment by XHusHX** [comment]
what the

**Comment by strids89** [comment]
You realize this is from May ?

**Comment by Ryzison** [comment]
"shared 3 months ago"

**Comment by XHusHX** [comment]
fyuh that scared dude

**Comment by XHusHX** [comment]
but that shared 3 months ago

**Comment by teamrockettroll** [comment]
fuck lol sorry guys youre right, but we should still expect something soon
