### ISSUE TITLE
NO pokestops found,always says 

### ISSUE THREAD

**Issue by chito241993** [PocketMobsters/PokeMobBot#596]
It doesnt capture pokemons,even farm pokestops...i set the maximun distance at 40000 and keep saying there are no pokestops in the middle of london,its too small,what can i do?

**Comment by richieza** [comment]
@chito241993 server changed API time - bots need to be updated - many threads about exact same issue

**Comment by chito241993** [comment]
So,bot isnt working right now?

**Comment by jinkawasaki333** [comment]
@chito241993 Yeah so just jump out of your window.

**Comment by xGR1MMZx** [comment]
We need it
