### ISSUE TITLE
No usable PokeStop found in your area. Is you maximum distance too small?

### ISSUE THREAD

**Issue by Radvanszki** [PocketMobsters/PokeMobBot#597]
Hi,

Since this morning Ihave received these messages for all locations. Could you please help me out? Max dist as per config file is 1000 meter. I have modified to 10,000 the issue is the same.

**Comment by richieza** [comment]
@Radvanszki Servers changed API time - bots need to be updated, 
many other threads about this.

**Comment by jinkawasaki333** [comment]
@Radvanszki Just quit playing Pokemon Go.

**Comment by Radvanszki** [comment]
@jinkawasaki333, good idea, many thanks :D Please do the same.

**Comment by jinkawasaki333** [comment]
Yeap I did xD
Sold 4 accounts for 3000+ USD
