### ISSUE TITLE
Please Close "Issues" section until API fix update is implemented

### ISSUE THREAD

**Issue by Emuuung** [PocketMobsters/PokeMobBot#598]
This issue-farming and asking for ETA or demanding for a fix... needs to stop.

**Comment by ShallowHacker** [comment]
No kidding.

**Comment by StDeamon** [comment]
How about we keep a ticket open,  so we can all know when the fix is made ?
or is there some way to get an automatic update?

**Comment by jinkawasaki333** [comment]
@StDeamon The thing is those people don't read others' ticket and keep submitting the same question.

**Comment by ShallowHacker** [comment]
Because they're morons. Lol

**Comment by XHusHX** [comment]
i think this is end of bots :'(
