### ISSUE TITLE
Problem with WebSocket

### ISSUE THREAD

**Issue by nilsabegg** [PocketMobsters/PokeMobBot#6]
Hey guys,

I thought about building a GUI for the bot and started playing around with angular and websocket. But I don't get it to work with the bot.
It's neither working in Edge, Firefox or Chrome.
This is the console error of chrome:
WebSocket connection to 'ws://127.0.0.1:14251/' failed: Error during WebSocket handshake: net::ERR_CONNECTION_RESET

Stackoverflow says that the implemented library in the server must be buggy.
 Is the websocket feature actually meant to be used?!

Thanks in advance for any help.

Regards
Nils

**Comment by Afraidium** [comment]
It certainly worked before the fork check out [necrobot visualizer](https://github.com/nicoschmitt/necrobotvisualizer) implementation.

**Comment by nicoschmitt** [comment]
I'm the owner of the visualizer. Please check what I do, fork it change it, send pull request if it's not far from what you want.

Also: it is wss://localhost:14251 (2 s).

**Comment by nilsabegg** [comment]
Ok, thank you...I already checked your visualizer when I posted this. It was not working either...my Firewall was blocking Port 14251.

**Comment by nicoschmitt** [comment]
if the bot and my app are on the same machine, firewall should not be blocking it. it should work.
