### ISSUE TITLE
Pokestop not found in the area

### ISSUE THREAD

**Issue by luongo9087** [PocketMobsters/PokeMobBot#603]
Hi! this morning the bot continue to give me the message below.. i've tried to change the coordinates, but it doesn't change nothing.. The maximum area that i have set is of 15km..

![immagine](https://cloud.githubusercontent.com/assets/20836403/17397838/32ff9084-5a3a-11e6-99e8-3ecc22786cad.png)

**Comment by Emuuung** [comment]
Read other issues BEFORE posting new ones.

**Comment by jinkawasaki333** [comment]
@luongo9087 It means that Niantic found out that you used bot, and therefore has banned your account

**Comment by PassiveModding** [comment]
@jinkawasaki333 niantic has not banned the account, thay changed their api calls which now stops bots from working

**Comment by exodia6666** [comment]
@jinkawasaki333 just STFU

**Comment by sim59** [comment]
Just insane how fast people can post their problem !

**Comment by luongo9087** [comment]
wait, wait! sorry! this is my first thread here!! the next time i'll not make this HUUUUUUGE mistake xD

**Comment by jinkawasaki333** [comment]
@PassiveModding I know 100% what is going on, and you know what? I read other people's problems instead of posting my own problem. Instead of cursing these dumbasses, I'll just troll 💃 

@exodia6666 Yeah yeah.. I'll STF and FYMS.. ;)

**Comment by exodia6666** [comment]
@jinkawasaki333 just grow up and find another place to troll

**Comment by jinkawasaki333** [comment]
@exodia6666 Instead of commenting on threads, shouldn't you be better finding out the Unknown6 so these people can STFU?

**Comment by jinkawasaki333** [comment]
@exodia6666 P.S: Read #598, moron :)

**Comment by exodia6666** [comment]
@jinkawasaki333 sorry have no time to argues with a baby.

**Comment by xGR1MMZx** [comment]
You think it's gonne be fix when ?

**Comment by jinkawasaki333** [comment]
@exodia6666 Yeah so fuck off

**Comment by XHusHX** [comment]
i think for further no one bots maybe

**Comment by bongohead101** [comment]
@xGR1MMZx  #573

**Comment by kaeld59** [comment]
Read the previous issue before posting new one...

**Comment by Liquidated** [comment]
i just come here for the lulz now...
botting 101...
Step 1: Look for your issue under the issues tab
Step 2: DONT FUCKING POST YOUR ISSUE IF THERE ARE 3,572 EXACT SAME OTHER ONES POSTED
Step 3: Patiently wait for the fix so that you can continue fucking up a beautiful game with the rest of us
Step 4: Harry Potter GO comes out
NEW ISSUE: Oh god my harry potter isn't farming fucking horcrux's what should i do?!
Step 5: REPEAT THE FIRST 3 FUCKING STEPS
