### ISSUE TITLE
API related? Reverse engineering?

### ISSUE THREAD

**Issue by YoghurtMuncher** [PocketMobsters/PokeMobBot#604]
The guys at PokéMesh appearently have reversed unknown6 self.pokemongodev

submitted 14 minutes ago by zero1918

Just gonna drop a link to their page for anyone interested. I'm not a dev, not a friend of theirs, just a follower of this whole big situation.

Here, check for yourselves: https://m.facebook.com/pokemesh/

**Comment by XHusHX** [comment]
i don't understand italian language ...whats means dude can you explain?

**Comment by carsonwu2016** [comment]
IT MEANS WE STILL HAVE HOPE FOR BOTTING

**Comment by Antsx3** [comment]
Im not sure weather i should be happy or angry that i started botting legit 2 days b4 this update

**Comment by XHusHX** [comment]
YEEEEEEEEAAAAAAAAAYYYYYYYYY

**Comment by YvesHenri** [comment]
PokeMesh does not use the API, its crowdsourced. And yes, there's hope. It's just about time, so be patient. Please.

**Comment by XHusHX** [comment]
patient is the key for success right?

**Comment by darranhall** [comment]
@YvesHenri if it were crowdsourced they would have no need for the API, correct? So why would they reverse engineer the API for no reason?

**Comment by matant94** [comment]
PokéMesh team have reversed the new contro sistem, as they say, "Reversed!... this means we aren't dead as any other map, pogo tool (for the moment) now take another long coffee, we need to implement"

**Comment by Valmere** [comment]
We're following updates on possible solutions just like everyone else, thanks though
