### ISSUE TITLE
Account not verified! Exiting

### ISSUE THREAD

**Issue by meciu** [PocketMobsters/PokeMobBot#61]
Initializing Rocket logger at time 7/31/2016 12:23:45 PM...
[12:23:45] Perfect! You already have the newest Version 0.5.0
[12:23:45] Logging in using Ptc
[12:23:46] Account not verified! Exiting...

Account is activated for sure, I'm logged in with PoGo app on android.

**Comment by meciu** [comment]
Thanks for answer!

Tried to even change email adress and then activate with recieved link but still no changes, yesterday I was able to log in ..

**Comment by voignar** [comment]
I happen to me the same and have the active account

**Comment by kyfranky** [comment]
try this sir, just copy paste and change the username and password

{
  "AuthType": "ptc",
  "GoogleRefreshToken": null,
  "PtcUsername": "youruser",
  "PtcPassword": "yourpass",
  "GoogleUsername": null,
  "GooglePassword": null
}

**Comment by roms78** [comment]
I have the same problem with Ptc account, 
will try @kyfranky idea, thanks

**Comment by meciu** [comment]
@kyfranky Thank you! It worked!

**Comment by jinkawasaki333** [comment]
I also have the same problem, tried everything here but nothing works.. :/

**Comment by kyfranky** [comment]
@jinkawasaki333 are you using ptc ? if yes, use this maybe it wil work

`{
  "AuthType": "ptc",
  "GooglePassword": null,
  "GoogleRefreshToken": null,
  "GoogleUsername": null,
  "PtcPassword": "pass",
  "PtcUsername": "user"
}`
