### ISSUE TITLE
No useable pokestops found in your area

### ISSUE THREAD

**Issue by bradandrews4** [PocketMobsters/PokeMobBot#610]
My max travel distance is set to 9900 now and my lat and lng are both set correctly and there are plenty of pokestops around the area...

I think this is probably due to pokemon updating their app? Can someone confirm if this is an issue or just something ive done wrong?

**Comment by Valmere** [comment]
Read the bold text in the readme or join discord and read through the announcements. The bot is not working at the moment.

**Comment by bradandrews4** [comment]
Oh sorry, you must have only just added that bolded text or I'm blind?! lool.... >.< And I've joined discord but not sure how to access the announcements tbh? 
@Valmere

**Comment by bradandrews4** [comment]
wait nvm again -_-

**Comment by bradandrews4** [comment]
I cant read ffs >...<
