### ISSUE TITLE
can't make it work

### ISSUE THREAD

**Issue by dexteralin** [PocketMobsters/PokeMobBot#611]
the bot keep says there are no pokestops in my area but it is set in central park, and i tried even with teleportation on and doesn't work , can anyone relate/help??

**Comment by antfuentes87** [comment]
Please stop making issues about this, or any other **USELESS** issues... @PocketMobsters if you want help closing these types of issues, I would be more than willing to give you a hand.

**Comment by HEADH0NCH0** [comment]
Everyone currently has this problem. They are working on fixing it.
