### ISSUE TITLE
Cant catch any Pokemon anymore

### ISSUE THREAD

**Issue by Pilskopf** [PocketMobsters/PokeMobBot#612]
Hey Guys i know the bot is not working at the moment. But when i log in manually i cant catch any pokemon. Anytime after throwing a ball it cancels imediatly and goes on the map screen with an red error message on the top. I can use pokestops and fight in areana´s  but catching pokemon is impossible. Everytime i get an error.
Do you know the Problem? May i be banned? Would be glad if someone could help.

**Comment by FXStrato** [comment]
https://www.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/

**Comment by Valmere** [comment]
Delete your location history and the apps cache/data. Closing as it's not bot related
