### ISSUE TITLE
Poke Stops 0

### ISSUE THREAD

**Issue by Pauloozzy** [PocketMobsters/PokeMobBot#616]
Every time i try to use appers it.

[16:55:52] (ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?

**Comment by GitClucked** [comment]
Waiting for the "close" lol. Please read previous topics....

**Comment by adriendomoison** [comment]
Same issue here

**Comment by flariann** [comment]
Long story short, new version of pokemon go "blocked" all bots, just wait untill they release a new version of the bot guys...

**Comment by GitClucked** [comment]
Go back to the Issues listing... In the Search bar. Make sure you search for closed issues as well. and what Flariann said.

**Comment by joeyd55** [comment]
closed. Oh wait..
