### ISSUE TITLE
API Changes. Is this the end?

### ISSUE THREAD

**Issue by Patheoff** [PocketMobsters/PokeMobBot#617]
So we are all aware of the recent update for Go and how the bot is not working for anyone. Is this the end for this kind of bots? or this specific one? I know devs are working on it but what is the likelihood of it happening? From what ive been reading it seems slim.

**Comment by marcosabruna** [comment]
Why would it be the end? Bots takes time to make. There wasn't a bot the day Pokemon Go was launched. New API means new encrypted codes. All you have to do is wait for hackers to figure out the codes and then wait for an update.
