### ISSUE TITLE
DOESNT WORk

### ISSUE THREAD

**Issue by lorenzofatto** [PocketMobsters/PokeMobBot#619]
the app says that it cant find any pokeshop 
how can i do?

**Comment by markkremer17** [comment]
same here

**Comment by bowerous** [comment]
yes i have

**Comment by SwipeDaScreen** [comment]
Also cannot find any pokestops

**Comment by SwipeDaScreen** [comment]
Keeps saying "No pokestops were found. Is your radition to small? i also cannot find it in the config

**Comment by UraharaKisuke07** [comment]
If you can't find any pokestops near you then that means you're permanently banned.

**Comment by richieza** [comment]
delete everything then read all the previous posts

**Comment by GitClucked** [comment]
Jesus christ.. Do people not know how to read....

**Comment by tickl3r** [comment]
this is getting ridiculous..

**Comment by Ryzison** [comment]
learn to read before you post

#618

**Comment by jinkawasaki333** [comment]
@lorenzofatto Yeah you have been banned permanently. If you login from your smartphone, it will seem that it is usable, but Niantic will track your IP and GPS, track your address and sue you. So be careful and delete the app as soon as possible.

**Comment by jonsnowwatch** [comment]
step 1: close the bot.
step 2: how about actually play pokemon go for a change while the devs are working 24/7 trying to help your lazy ass

**Comment by GitClucked** [comment]
How about we get a real mod in here to close the topic? -_-

**Comment by Sanskritmp** [comment]
Sometime soon, the Issues tab will be closed with the people spamming that it doesn't work.
Niantic just updated their API, so it would usually take 24-48 or more before it's reverse engineered. So wait up and don't spam
On a side note, turn off your bots until further ado.

**Comment by Flariann** [comment]
Oh for fucks sake, not this again...

**Comment by lorenzofatto** [comment]
i think im not banned 'cause 
i ve created a new account without enter in this by phon 
but the program still say that there arnt any pokeshop near
