### ISSUE TITLE
"PokeMobBot stop working"

### ISSUE THREAD

**Issue by xfaustx** [PocketMobsters/PokeMobBot#63]
Today i got this "PokeMobBot Client For Pokemon Go Stop working"
![error](https://cloud.githubusercontent.com/assets/20742596/17275991/683c9f18-5723-11e6-9ad7-ebff18129ccf.jpg)

**Comment by Sylencer90** [comment]
Same issue as in the old necro. Well done.

**Comment by jeffsnow88** [comment]
I have the same issue, with both.

**Comment by xfaustx** [comment]
@ghost 
https://github.com/PocketMobsters/PokeMobBot/issues/75

**Comment by Fenixxia** [comment]
This happens sometimes, but with one important characteristic: program execution time in multiples of 30 minutes within a few seconds.

**Comment by xfaustx** [comment]
@Fenixxia 5h47min i got this one.

**Comment by cherzong** [comment]
I keep getting this also with the CMD crashing/freezing and giving me errors. Only on PTC account only not Google in less than 2 hours or so. The error gives me...
\AppData\Local\Temp\WERD7C9.tmp.mdmp
\AppData\Local\Temp\WERD71C.tmp.appcompat.txt
\AppData\Local\Temp\WERCB29.tmp.WERInternalMetadata.xml

**Comment by UntilSunrise** [comment]
should be resolved, if not please reopen
