### ISSUE TITLE
Inventory Recycling

### ISSUE THREAD

**Issue by GTXMike** [PocketMobsters/PokeMobBot#66]
Since the inventory management changed bot is only keeping Pokeballs on my account and removes all great and ultra pokeballs, very depressing. Noticed it today :/

**Comment by Gripexus** [comment]
Same here! It uses all high Pokeballs and just take normal Pokeballs... i got 300 normal and 10 great... startet with much more.

**Comment by cyan** [comment]
just add recycling limiter for each type, and change the maxpokeballtokeep to a combined number of all type of ball to keep, i work great for me

**Comment by GTXMike** [comment]
CP limits
