### ISSUE TITLE
Max distance

### ISSUE THREAD

**Issue by jeffsnow88** [PocketMobsters/PokeMobBot#70]
Hello :)

One question, sometimes I note the message "no usable poketop found in your area, is your max distance too small?". And when i log in game using my smartphone, i note that map is tottaly empty, even knowing that there is a lot of pokestop there (central park). Anyone knows what's going on?

**Comment by EyesReye** [comment]
I had this aswell, Let the bot run for a couple minutes and it should be fixed.

**Comment by jeffsnow88** [comment]
thanks!
