### ISSUE TITLE
Problem with the AutoLevelUp function

### ISSUE THREAD

**Issue by imyhxy** [PocketMobsters/PokeMobBot#8]
When I set the AutoLevelUp true, It make a high possible to get red code and make the bot bootloop.

**Comment by ShawnHardwick** [comment]
Keep in mind this was a newly implemented feature from Necrobot's 4.0 release. If you could supply us with the the red text, we could try to replicate it.

**Comment by imyhxy** [comment]
`[12:35:57] (ERROR) System.NullReferenceException: 未将对象引用设置到对象的实例。**(Object reference not set to an instance of an object.)**
   在 PoGo.PokeMobBot.Logic.Tasks.LevelUpPokemonTask.<Execute>d__0.MoveNext() 位置**(Location)** C:\Users\Trent\Documents\GitHub\PokeMobBot\PoGo.PokeMobBot.Logic\Tasks\LevelUpPokemonTask.cs:行号 **(Line number)**39
--- 引发异常的上一位置中堆栈跟踪的末尾 **(Raised in the previous location of the exception stack trace to the end of)**---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 PoGo.PokeMobBot.Logic.State.FarmState.<Execute>d__0.MoveNext() 位置 C:\Users\Trent\Documents\GitHub\PokeMobBot\PoGo.PokeMobBot.Logic\State\FarmState.cs:行号 26
--- 引发异常的上一位置中堆栈跟踪的末尾 **(Raised in the previous location of the exception stack trace to the end of)**---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() 位置 C:\Users\Trent\Documents\GitHub\PokeMobBot\PoGo.PokeMobBot.Logic\State\StateMachine.cs:行号 36`
I'm using a Chinese system, so I added some Comments.

**Comment by bmdr38** [comment]
Well, the current iteration of the upgrade task is pretty terrible. But in this case, it is choking on the fact that you (probably) have a pokemon that is at its at its max level and cannot be upgraded at this time. If you are coding inclined and want a quick fix, you can remove the logging line that is throwing this. Otherwise you should disable upgrading until either my PR is accepted or it is fixed by another

**Comment by imyhxy** [comment]
@bmdr38 I think you've found the problem, I have set the UpgradeAboveIv to 99.0, and there just several Pokemons meet that factor, and some of them already hit the highest level. So when the bot randomly choose a Pokemon to level up, it's high possible to choose a highest level Pokemon to level up. That make sense.

**Comment by forReason** [comment]
I made a fix in #127 . merge must be accepted still

It happens most often when you got only 1-2 pokemon to levelup

**Comment by UntilSunrise** [comment]
duplicate
