### ISSUE TITLE
Pokeminer vs PokeMobBot

### ISSUE THREAD

**Issue by jeffsnow88** [PocketMobsters/PokeMobBot#83]
Hi all!

I'm not sure if i'm doing anything wrong, but capture is taking big delays between then, it's hard for the bot to find pokemons (using 15km/h, based in Central Park). However, if you compare to the bot's that have interface with pokeminer, it goes directly to the pokemon location, so I get lot more pokemons.

However, i think PokeMobBot have more features and see more stable. Is there any chance to implement a interface with pokeminer in order to read sql db with poke locations, including priority for rare pokemons?

I'm doing very low exp/hour, due the fact the bot take longs to find a poke, even in Central Park.

Thank you all.

**Comment by ddrmax** [comment]
have you tested with the new teleport function?
and if you think the walking speed is the problem, why not put at least the initial walking speed (50)

**Comment by Anyrainel** [comment]
I guess right now the system is just lack of good enough routing algorithm. A good one should be able to find something even without the location db. Changing the radius of farming could have influence on this problem. If you want to partly solve it, you could have a try on modifying the max distance.

**Comment by aeryl1999** [comment]
I went as far as setting the following on a test accounts.
"Teleport": true,
  "DelayBetweenPlayerActions": 500,
  "DelayBetweenPokemonCatch": 200,
  "DelayCatchNearbyPokemon": 100,
  "DelayPositionCheckState": 100,
  "DelayCatchIncensePokemon": 100,
  "DelayCatchLurePokemon": 100,
  "DelayCatchPokemon": 100,
  "DelayDisplayPokemon": 100,
  "DelayUseLuckyEgg": 100,
  "DelaySoftbanRetry": 100,
  "DelayPokestop": 100,
  "DelayRecyleItem": 100,
  "DelaySnipePokemon": 100,
  "DelayTransferPokemon": 100,

Averaging 100K+ exp per hour with the evolve list. As for the softbans, it does happen but sorts out after 10 seconds. Adjust settings if you're using it on your main.
![untitled](https://cloud.githubusercontent.com/assets/20621766/17277265/2f9fd78a-5771-11e6-9d92-fc79e0f51364.jpg)

**Comment by UntilSunrise** [comment]
isnt really an issue
