### ISSUE TITLE
IApiFailureStrategy/ApiOperation

### ISSUE THREAD

**Issue by kidoyang** [PocketMobsters/PokeMobBot#87]
PokeMobBot-master\PoGo.PokeMobBot.Logic\Common\ApiFailureStrategy.cs

Error	CS0246	The type or namespace name 'IApiFailureStrategy' could not be found (are you missing a using directive or an assembly reference?)	
Error	CS0246	The type or namespace name 'ApiOperation' could not be found (are you missing a using directive or an assembly reference?)

Anyone got same issue?

**Comment by RoseFlunder** [comment]
I bet you tried to setup source code via zip files? Just try out the variant with git and everything should be fine.

**Comment by TBK0000** [comment]
You need to get the API fork that yamashi made - https://github.com/yamashi/PokemonGoAPI

**Comment by UntilSunrise** [comment]
follow the source code setup manual:
https://github.com/PocketMobsters/PokeMobBot/wiki/Source-Code
