### ISSUE TITLE
Account not verified!

### ISSUE THREAD

**Issue by domuk** [PocketMobsters/PokeMobBot#9]
Since updating to the latest Necrobot/PokeMobBot, I can no longer login to my accounts;
Initializing Rocket logger at time 7/31/2016 4:31:03 AM...
[04:31:04] Perfect! You already have the newest Version 0.5.0
[04:31:04] Logging in using Ptc
[04:31:05] Account not verified! Exiting...

If I down grade my bot to v0.3.3 it works perfectly, I have validated the account on my phone and also via email so I do not know how my account is not verified, any ideas what would cause this to happen. I think the last version that worked for me was v0.3.3, and any version after this I get the above error.

**Comment by crazynever** [comment]
Checks if you did not reverse the location of the password and user in file auth

**Comment by domuk** [comment]
Yep, exactly that :+1: 
The old template had it as
  "AuthType": "ptc",
  "GoogleRefreshToken": null,
  "PtcUsername": "*****",
  "PtcPassword": "******",
  "GoogleUsername": null,
  "GooglePassword": null

The new one
  "AuthType": "ptc",
  "GooglePassword": null,
  "GoogleRefreshToken": null,
  "GoogleUsername": null,
  "PtcPassword": "*******",
  "PtcUsername": "*******"

Swapped it around and all sorted.
