### ISSUE TITLE
[Suggestions] AutoFill the new config data from the old one.

### ISSUE THREAD

**Issue by Fenixxia** [PocketMobsters/PokeMobBot#90]
Dear developers. Is it possible to make so that when you change the Config file and add new functions, or something like that was made up of these parameters from the same functions with the old Config file? And the new functions may have the flag "enter data".
The parsing of the old and the new autocomplete feature in those functions that have not changed?

With each release we as users have more and more rows to fine tune the config. On the one hand it is good, the system more flexible. However, many of us would agree that to fill it every time already very tired and tiring. And if the client is not a bot, but a few? But if these few bots have different settings in the configs?
With respect to your work.

**Comment by TheHaliax** [comment]
@Fenixxia This is already implemented with this line   "TransferConfigAndAuthOnUpdate": true, in the current config.
