### ISSUE TITLE
locaiton snipe

### ISSUE THREAD

**Issue by wang81129896** [PocketMobsters/PokeMobBot#99]
I use the code source to complie programe. Now the problem is that the bot will not go snipe with snipelocation service. I have set the
 "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": true,
  "UseTransferIvForSnipe": true,
  "UseSnipeLocationServer": true,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
and also use the pogolocationfeeder. the Pogolocationfeeder can get informaiton from discord just the Bot dont catch.

If i use the Release version then the bot will work. The problem is that the bot will always catch pokemon who is above 300cp with greatball.

**Comment by UntilSunrise** [comment]
was a discord issue
